/**
 * Achievements — pure derivations of already-persisted progress (game stats,
 * lesson completion, puzzle solves). No new gameplay state: each badge's
 * `test(s)` reads a summary object the app builds from existing storage.
 * scripts/test-chess.mjs checks every badge is well-formed and reachable.
 * @module achievements
 */
  export const CHESS_ACHIEVEMENTS = [
    { id: "first-lesson", nameKey: "ach.first-lesson.n", descKey: "ach.first-lesson.d", icon: "🎓", name: "初学乍练", desc: "完成第 1 课",
      test: (s) => s.lessonsDone >= 1 },
    { id: "all-lessons", nameKey: "ach.all-lessons.n", descKey: "ach.all-lessons.d", icon: "📚", name: "规则通关", desc: "完成全部教学课程",
      test: (s) => s.lessonsTotal > 0 && s.lessonsDone >= s.lessonsTotal,
      progress: (s) => [s.lessonsDone, s.lessonsTotal] },
    { id: "first-puzzle", nameKey: "ach.first-puzzle.n", descKey: "ach.first-puzzle.d", icon: "🧩", name: "初试身手", desc: "解出第 1 道题",
      test: (s) => s.puzzleSolvedCount >= 1 },
    { id: "puzzle-10", nameKey: "ach.puzzle-10.n", descKey: "ach.puzzle-10.d", icon: "🎯", name: "战术之眼", desc: "累计解出 10 道题",
      test: (s) => s.puzzleSolvedCount >= 10, progress: (s) => [s.puzzleSolvedCount, 10] },
    { id: "puzzle-30", nameKey: "ach.puzzle-30.n", descKey: "ach.puzzle-30.d", icon: "🎪", name: "熟能生巧", desc: "累计解出 30 道题",
      test: (s) => s.puzzleSolvedCount >= 30, progress: (s) => [s.puzzleSolvedCount, 30] },
    { id: "puzzle-75", nameKey: "ach.puzzle-75.n", descKey: "ach.puzzle-75.d", icon: "🏹", name: "百炼成钢", desc: "累计解出 75 道题",
      test: (s) => s.puzzleSolvedCount >= 75, progress: (s) => [s.puzzleSolvedCount, 75] },
    { id: "all-mates", nameKey: "ach.all-mates.n", descKey: "ach.all-mates.d", icon: "♛", name: "杀法大师", desc: "解出全部杀王题",
      test: (s) => s.matesTotal > 0 && s.matesSolved >= s.matesTotal,
      progress: (s) => [s.matesSolved, s.matesTotal] },
    { id: "all-tactics", nameKey: "ach.all-tactics.n", descKey: "ach.all-tactics.d", icon: "⚡", name: "战术行家", desc: "解出全部战术母题",
      test: (s) => s.tacTotal > 0 && s.tacSolved >= s.tacTotal,
      progress: (s) => [s.tacSolved, s.tacTotal] },
    { id: "all-real", nameKey: "ach.all-real.n", descKey: "ach.all-real.d", icon: "🎯", name: "实战眼", desc: "解出全部实战战术题",
      test: (s) => s.realTotal > 0 && s.realSolved >= s.realTotal,
      progress: (s) => [s.realSolved, s.realTotal] },
    { id: "all-openings", nameKey: "ach.all-openings.n", descKey: "ach.all-openings.d", icon: "📖", name: "开局博士", desc: "背完全部开局线路",
      test: (s) => s.opTotal > 0 && s.opSolved >= s.opTotal,
      progress: (s) => [s.opSolved, s.opTotal] },
    { id: "first-win", nameKey: "ach.first-win.n", descKey: "ach.first-win.d", icon: "🏆", name: "首胜", desc: "人机对弈赢下第 1 局",
      test: (s) => s.wins >= 1 },
    { id: "win-10", nameKey: "ach.win-10.n", descKey: "ach.win-10.d", icon: "👑", name: "常胜将军", desc: "人机累计胜 10 局",
      test: (s) => s.wins >= 10, progress: (s) => [s.wins, 10] },
    { id: "extreme-win", nameKey: "ach.extreme-win.n", descKey: "ach.extreme-win.d", icon: "🔥", name: "屠龙", desc: "在「极限」难度赢一局",
      test: (s) => s.extremeWins >= 1 },
    { id: "veteran", nameKey: "ach.veteran.n", descKey: "ach.veteran.d", icon: "⏳", name: "身经百战", desc: "人机累计对局 50 局",
      test: (s) => s.games >= 50, progress: (s) => [s.games, 50] },
    { id: "completionist", nameKey: "ach.completionist.n", descKey: "ach.completionist.d", icon: "🌟", name: "圆满", desc: "解锁上面全部成就",
      test: (s) => s.otherUnlocked >= s.otherTotal && s.otherTotal > 0,
      progress: (s) => [s.otherUnlocked, s.otherTotal] },
  ];
