/**
 * 残局训练营：90 个标准残局（v8-1-plan T2 的 60 个，v8-3-plan T5 又加了 30 个）。
 *
 * Built into js/chunk-endgames.js (scripts/bundle.mjs) and fetched the first
 * time the lesson list or 「我的」 asks for it — none of it is in bundle.js.
 *
 * Every position is set up from the student's chair: White, to move. Where
 * the book diagram has Black defending, the colours are swapped (the source
 * line says so). `goal` is what the student has to reach against the engine
 * at full strength — "win", or "draw" (hold it). What counts as reaching it is
 * endgame-rules.js.
 *
 * `v` is how the verdict was checked when this file was written, never at
 * run time (no tablebase ships):
 *   - "tb": the Syzygy tables. ≤ 4 men, the local 3–4-piece WDL files (the
 *     5-piece set could not be fetched from here — v8-1-plan §9 M3); 5–7
 *     men, the full set's answer from tablebase.lichess.ovh, asked in CI
 *     (v8-2-plan §9 M2) — their Stockfish rows stay on file beside it;
 *   - "sf": more than 7 men, no table anywhere: a deep native Stockfish
 *     search with the 3–4-piece tables attached, the verdict (mate /
 *     tablebase score for a win, 0.00 for a draw) the same at two depths;
 *   - "pend": 5–7 men, so far only that same deep search — the online
 *     table has not been asked yet (v8-3-plan T5: tablebase.lichess.ovh is
 *     refused here, so verify-endgames.yml asks it in CI). The card says so;
 *     once the answer agrees, the item becomes "tb".
 * scripts/verify-endgames.py writes docs/endgames-verified.json from this
 * file; test-endgames.mjs holds each `goal` and `v` to that record — and
 * `key`, where a tip names the moves that work, to the table's list of the
 * moves that keep the result — and test-endgames-play.mjs plays each one
 * out to its goal.
 *
 * Words are [zh-CN, en, ja] — the chunk carries all three so a language
 * switch needs no second fetch. `n` name, `tip` the idea, `src` where the
 * position comes from.
 * @module endgames
 */
  const GROUPS = [
    { id: "kp", n: ["王兵残局", "King and pawn", "キングとポーン"] },
    { id: "rp", n: ["车的残局", "Rook endings", "ルークのエンドゲーム"] },
    { id: "mi", n: ["轻子残局", "Minor pieces", "マイナーピース"] },
    { id: "qu", n: ["后的残局", "Queen endings", "クイーンのエンドゲーム"] },
    { id: "dr", n: ["理论和棋", "Theoretical draws", "理論的ドロー"] },
  ];

  const THEORY = ["标准残局理论", "Standard endgame theory", "標準的なエンドゲーム理論"];
  const ONE = ["按主题摆出的教学局面；查表确认，只有提示里点到的着法能达到目标",
    "Set up for the theme; the tablebase confirms that only the moves the tip names reach the goal",
    "テーマ用に配置した局面。ヒントに挙げた手だけが目標に届くことをテーブルベースで確認済み"];
  const FLIP = (s) => [s[0] + "（黑白互换，你执白）", s[1] + " (colours swapped: you play White)", s[2] + "（白黒を入れ替え、あなたが白）"];

  const ITEMS = [
    // —— 王兵 ——
    { id: "kp-keysq", g: "kp", fen: "8/8/3k4/8/8/3K4/3P4/8 w - - 0 1", goal: "win", v: "tb",
      n: ["关键格", "Key squares", "キー・スクエア"],
      tip: ["兵在第 2 横线时，它前面两格的 c4、d4、e4 就是关键格：王站上去，不管对方怎么走，兵都能升变。先走王，兵最后推。",
        "With the pawn on d2, c4, d4 and e4 are its key squares: put your king on one and the pawn queens whatever Black does. King first, pawn last.",
        "d2 のポーンのキー・スクエアは c4・d4・e4。キングがそこに立てば、相手が何をしてもポーンは昇格する。キングが先、ポーンは最後。"],
      src: THEORY },
    { id: "kp-sixth", g: "kp", fen: "3k4/8/3K4/3P4/8/8/8/8 w - - 0 1", goal: "win", v: "tb",
      n: ["王上第 6 横线", "King on the sixth", "6 段目のキング"],
      tip: ["王站在兵前面的第 6 横线（不是边兵），轮到谁走都必胜。王先走开给兵让路，小心别把对方王逼和。",
        "A king on the sixth rank in front of a non-rook pawn wins whoever is to move. Step aside for the pawn, and mind the stalemate.",
        "ルークポーン以外なら、ポーンの前の 6 段目にキングがいれば手番に関係なく勝ち。キングがわきによけて道を空ける。ステイルメイトに注意。"],
      src: THEORY },
    { id: "kp-tempo", g: "kp", fen: "8/3k4/8/3K4/8/3P4/8/8 w - - 0 1", goal: "win", v: "tb",
      n: ["兵的等着", "The spare tempo", "ポーンの待ち手"],
      tip: ["两王正面相对时，轮到谁走很要紧。这里兵还能走一步「等着」：d3–d4 把走棋的义务还给对方，你的王就能绕过去。",
        "Kings face to face: who is to move decides it. Here the pawn has a spare step — d3–d4 hands the move back to Black, and your king gets past.",
        "キング同士が向かい合うときは手番がすべて。ここではポーンに待ち手がある：d3–d4 で手番を相手に返せば、キングが回り込める。"],
      src: THEORY },
    { id: "kp-far", g: "kp", fen: "4k3/8/8/8/8/8/4P3/4K3 w - - 0 1", goal: "win", v: "tb", key: ["Kd2", "Kf2"],
      n: ["先上王，后推兵", "King before pawn", "キングが先、ポーンは後"],
      tip: ["王和兵都在起点。只有王往前走（Kd2 或 Kf2）才赢：抢在黑王之前站上关键格。先推兵就只能和棋。",
        "Both on their home squares. Only a king move (Kd2 or Kf2) wins: reach the key squares before Black's king does. Pushing the pawn first only draws.",
        "キングもポーンも初期位置。勝つのはキングを進める手（Kd2 か Kf2）だけ。相手より先にキー・スクエアへ。先にポーンを突くとドロー。"],
      src: THEORY },
    { id: "kp-square", g: "kp", fen: "8/8/8/P7/4k3/8/8/7K w - - 0 1", goal: "win", v: "tb",
      n: ["方块规则", "The rule of the square", "スクエアの法則"],
      tip: ["以兵到升变格的距离为边长画一个方块：对方王走不进这个方块，兵就能自己跑到底。马上推兵！",
        "Draw the square from the pawn to its queening rank. If Black's king cannot step into it, the pawn runs home alone. Push now!",
        "ポーンから昇格段までを一辺とする正方形を描く。相手キングがその中に入れなければ、ポーンは一人で走り切る。すぐ突く！"],
      src: THEORY },
    { id: "kp-rookpawn", g: "kp", fen: "8/1K1k4/8/P7/8/8/8/8 w - - 0 1", goal: "win", v: "tb",
      n: ["边兵：先占住角落", "Rook pawn: hold the corner", "ルークポーン：隅を押さえる"],
      tip: ["边兵最容易和棋：对方王一钻进角落就赢不了。你的王已经挡在 b7，守住了 a8 —— 别让开，兵慢慢推上来。",
        "A rook pawn draws once the defender reaches the corner. Your king on b7 already holds a8 — keep it there and walk the pawn up.",
        "ルークポーンは相手キングが隅に入ればドロー。あなたのキングは b7 で a8 を押さえている。そこを離れずにポーンを進めよう。"],
      src: THEORY },
    { id: "kp-opposition", g: "kp", fen: "8/4K3/6k1/4p3/4P3/8/8/8 w - - 0 1", goal: "win", v: "tb", key: ["Ke6"],
      n: ["抢先吃兵", "Win the blocked pawn", "止まったポーンを取る"],
      tip: ["两个兵顶住了，谁的王先吃到对方的兵谁赢。只有 Ke6：王贴上去攻击 e5，黑王来不及保护它。吃掉兵后按关键格的办法赢。",
        "The pawns are locked; the king that wins the other pawn wins the game. Only Ke6: it hits e5 and Black's king is too late to guard it. Then win as with key squares.",
        "ポーン同士がぶつかっている。先に相手のポーンを取ったほうが勝つ。正解は Ke6 だけ：e5 を狙い、黒キングは守りに間に合わない。取った後はキー・スクエアの要領で。"],
      src: ONE },
    { id: "kp-race", g: "kp", fen: "4K3/6k1/8/P7/7p/8/8/8 w - - 0 1", goal: "win", v: "tb", key: ["a6"],
      n: ["兵赛跑", "The pawn race", "ポーンの競走"],
      tip: ["双方都冲兵，你先升变。黑兵也会变后，但你的新后站在 a8，正好沿大斜线看住 h1。唯一的赢法是 a6。",
        "Both pawns run and yours queens first. Black's will queen too — but your new queen on a8 watches h1 down the long diagonal. Only a6 wins.",
        "両者ポーンを突き合い、こちらが先に昇格する。黒も昇格するが、a8 の新クイーンが長い対角線で h1 を見ている。勝ちは a6 だけ。"],
      src: ONE },
    { id: "kp-outside", g: "kp", fen: "8/8/3k4/6p1/P2K2P1/8/8/8 w - - 0 1", goal: "win", v: "tb",
      n: ["外线通路兵", "The outside passed pawn", "外側のパスポーン"],
      tip: ["a 兵离黑王最远。用它把黑王引到棋盘另一边，你的王趁机去吃 g5，再回来。",
        "The a-pawn is far from Black's king. Use it to drag the king across the board, and let your own king take g5 meanwhile.",
        "a ポーンは黒キングから最も遠い。それで相手キングを反対側へ引きつけ、その間にこちらのキングが g5 を取りに行く。"],
      src: THEORY },
    { id: "kp-protected", g: "kp", fen: "8/8/3k4/3P3p/4P3/8/6K1/8 w - - 0 1", goal: "win", v: "tb",
      n: ["受保护的通路兵", "The protected passed pawn", "守られたパスポーン"],
      tip: ["d5 有 e4 保护，黑王既吃不掉它，也不敢离开它。你的王可以放心去吃 h 兵，再回来护送。",
        "e4 guards d5, so Black's king can neither take it nor leave it. Your king is free to go and win the h-pawn, then come back.",
        "d5 は e4 に守られ、黒キングは取ることも離れることもできない。こちらのキングは安心して h ポーンを取りに行ける。"],
      src: THEORY },
    { id: "kp-breakthrough", g: "kp", fen: "6k1/ppp5/8/PPP5/8/8/8/6K1 w - - 0 1", goal: "win", v: "sf",
      n: ["三兵突破", "The breakthrough", "ブレイクスルー"],
      tip: ["三兵对三兵：b6！ 不管黑方怎么吃，总有一个兵冲过去。黑王离得太远，赶不回来。",
        "Three against three: b6! However Black captures, one pawn gets through, and Black's king is too far away to catch it.",
        "3 対 3：b6！ 黒がどう取っても 1 本は抜けていき、黒キングは遠すぎて間に合わない。"],
      src: THEORY },
    { id: "kp-majority", g: "kp", fen: "8/8/5kp1/8/5PP1/5K2/8/8 w - - 0 1", goal: "win", v: "tb",
      n: ["二打一", "Two against one", "2 対 1"],
      tip: ["用两个兵换掉对方唯一的兵，留下一个通路兵；王走在兵的前面护送。",
        "Trade one of your two pawns for Black's only one and keep a passed pawn, with your king walking in front of it.",
        "2 本のうち 1 本を相手の 1 本と交換してパスポーンを残し、キングがその前を歩いて護衛する。"],
      src: THEORY },
    // v8-3-plan T5: the camp's second part — four more pawn endings
    { id: "kp-trebuchet", g: "kp", fen: "8/1K6/3p4/3Pk3/8/8/8/8 w - - 0 1", goal: "win", v: "tb", key: ["Kc6"],
      n: ["谁走谁输", "The trébuchet", "トレビュシェ"],
      tip: ["两个王各自攻击对方的兵时，谁走谁输。只有 Kc6：保护 d5、攻击 d6，把走棋的义务交给黑方 —— 黑王一离开 e5，d6 就是你的。",
        "When each king attacks the other's pawn, whoever has to move loses. Only Kc6: it guards d5, hits d6 and hands Black the move — once Black's king leaves e5, d6 is yours.",
        "両キングが互いのポーンを狙う形では、手番の側が負ける。正解は Kc6 だけ：d5 を守りつつ d6 を狙い、手番を黒に渡す。黒キングが e5 を離れれば d6 が取れる。"],
      src: ONE },
    { id: "kp-distant", g: "kp", fen: "8/6k1/8/8/8/8/3P3K/8 w - - 0 1", goal: "win", v: "tb", key: ["Kg3"],
      n: ["远距离对王", "Distant opposition", "遠いオポジション"],
      tip: ["隔得远也有对王：两王在同一条线上，中间隔奇数个格子。只有 Kg3：和 g7 的黑王隔三格相对。它往哪边走你就跟到哪边，王先赶到兵的前面。",
        "Opposition works at a distance too: kings on one line with an odd number of squares between. Only Kg3, three squares from the king on g7. Follow it wherever it goes, and your king gets in front of the pawn first.",
        "離れていてもオポジションはある：同じ線上で間のマスが奇数。正解は Kg3 だけ：g7 の黒キングと 3 マス空けて向かい合う。相手が動いた方へ付いていき、先にポーンの前に出る。"],
      src: ONE },
    { id: "kp-detour", g: "kp", fen: "3k1K2/2p5/2P5/8/8/8/8/8 w - - 0 1", goal: "win", v: "tb", key: ["Kf7"],
      n: ["王绕一步", "The king's detour", "キングの回り道"],
      tip: ["你的王想去 e7，可 d8 的黑王守着它。只有 Kf7：黑王只能退到 c8，你再走 Ke7、Kd7，一步步把它从 c7 兵旁挤开。",
        "Your king wants e7, but Black's king on d8 guards it. Only Kf7: Black's king can only go to c8, and Ke7 and Kd7 then push it away from the c7 pawn.",
        "白キングは e7 に行きたいが、d8 の黒キングが守っている。正解は Kf7 だけ：黒キングは c8 へ下がるしかなく、続く Ke7・Kd7 で c7 のポーンから押しのける。"],
      src: ONE },
    { id: "kp-outflank", g: "kp", fen: "8/6k1/3p4/3P4/7K/8/8/8 w - - 0 1", goal: "win", v: "tb", key: ["Kg5"],
      n: ["对王，再绕过去", "Opposition, then outflank", "オポジションから回り込む"],
      tip: ["只有 Kg5：先和 g7 的黑王正面对王。它一让开，你就从旁边绕过去（往 f6、e6 走），去吃 d6。",
        "Only Kg5: first take the opposition against the king on g7. When it gives way, walk round it (towards f6 and e6) and go for d6.",
        "正解は Kg5 だけ：まず g7 の黒キングとオポジションを取る。相手が譲ったら横から回り込み（f6・e6 方面へ）、d6 を取りに行く。"],
      src: ONE },

    // —— 车 ——
    { id: "rp-krk", g: "rp", fen: "4k3/8/8/8/8/8/8/R3K3 w - - 0 1", goal: "win", v: "tb",
      n: ["车杀王", "Rook and king mate", "ルークでのメイト"],
      tip: ["车切一条线当围栏；王走上去和黑王正面相对时，车将军把它逼退一行，一直逼到底线将死。",
        "The rook fences off a line. When your king faces Black's, a rook check pushes it back a rank — all the way to the edge, and mate.",
        "ルークで 1 列を仕切る。キング同士が向かい合った瞬間にルークでチェックして 1 段下げ、端まで追い詰めてメイト。"],
      src: THEORY },
    { id: "rp-lucena", g: "rp", fen: "1K1k4/1P6/8/8/8/8/r7/2R5 w - - 0 1", goal: "win", v: "tb",
      n: ["卢塞纳：搭桥", "Lucena: building a bridge", "ルセナ：橋をかける"],
      tip: ["车放到第 4 横线准备「搭桥」，王从兵前走出来；黑车从侧面将军时，用车挡住，兵就能升变。",
        "Put your rook on the fourth rank to build a bridge, then walk the king out from in front of the pawn; when the black rook checks from the side, block with your rook.",
        "ルークを 4 段目に置いて「橋」を準備し、キングをポーンの前から出す。黒ルークが横からチェックしてきたらルークで遮る。"],
      src: ["卢塞纳局面（Salvio 1634 年书中记载）", "The Lucena position (recorded by Salvio, 1634)", "ルセナ・ポジション（サルヴィオ、1634 年）"] },
    { id: "rp-lucena2", g: "rp", fen: "3K4/3P2k1/8/8/8/8/2r5/4R3 w - - 0 1", goal: "win", v: "tb",
      n: ["卢塞纳：王被困在兵前", "Lucena: the king in front", "ルセナ：ポーンの前のキング"],
      tip: ["你的车在 e 线挡住黑王。王先从兵前走出来，躲开侧面的将军；需要时照样用车搭桥。",
        "Your rook on the e-file keeps Black's king away. Get your king out from in front of the pawn, dodge the side checks, and bridge with the rook when you must.",
        "e ファイルのルークが黒キングを遮っている。まずキングをポーンの前から出し、横からのチェックをかわす。必要なら同じく橋をかける。"],
      src: ["卢塞纳局面的变体", "A variant of the Lucena position", "ルセナ・ポジションの変形"] },
    { id: "rp-cutoff", g: "rp", fen: "r7/8/6k1/3P4/3K4/8/8/4R3 w - - 0 1", goal: "win", v: "tb",
      n: ["用车切断王", "Cutting off the king", "キングを遮断する"],
      tip: ["车在 e 线把黑王关在王翼。王护着兵往前走；黑车从后面将军时，王往车那边靠着躲。",
        "The rook on the e-file shuts Black's king out on the kingside. Advance king and pawn together; when the black rook checks from behind, hide towards it.",
        "e ファイルのルークが黒キングをキングサイドに閉じ込める。キングとポーンで前進し、後ろからのチェックはルークの方へ寄ってかわす。"],
      src: THEORY },
    { id: "rp-skewer", g: "rp", fen: "R7/P3k3/8/8/8/8/6K1/r7 w - - 0 1", goal: "win", v: "tb",
      n: ["七线兵的串击", "The seventh-rank skewer", "7 段目のスキュア"],
      tip: ["Rh8！ 黑车吃 a7 的话，Rh7+ 串击把车赢回来。黑王不在 g7、h7，这一招就成立。",
        "Rh8! If the black rook takes on a7, Rh7+ skewers it. With Black's king off g7 and h7, the trick works.",
        "Rh8！ 黒ルークが a7 を取れば Rh7+ のスキュアでルークを取り返す。黒キングが g7・h7 にいないから成立する。"],
      src: THEORY },
    { id: "rp-behind", g: "rp", fen: "R7/8/K7/8/3p4/8/8/5k2 w - - 0 1", goal: "win", v: "tb", key: ["Rd8"],
      n: ["车对兵：绕到兵后", "Rook v pawn: get behind it", "ルーク対ポーン：後ろに回る"],
      tip: ["唯一的赢法是 Rd8：车绕到兵的后面，兵走得越远，车看得越牢；你的王从 a6 赶回来。",
        "Only Rd8 wins: the rook goes behind the pawn, which the further it runs the better the rook holds it, while your king hurries back from a6.",
        "勝つのは Rd8 だけ。ルークはポーンの後ろへ。ポーンが進むほどルークはよく利く。その間にキングが a6 から戻る。"],
      src: ONE },
    { id: "rp-check", g: "rp", fen: "8/8/4K3/1R6/3p4/2k5/8/8 w - - 0 1", goal: "win", v: "tb", key: ["Rc5+"],
      n: ["车对兵：先将一军", "Rook v pawn: check first", "ルーク対ポーン：まずチェック"],
      tip: ["只有 Rc5+ 能赢：先将军逼黑王表态，它往哪边走，车就从哪边切断；你的王赶过来收拾兵。",
        "Only Rc5+ wins: check first to make the king choose a side, then cut it off on that side while your king comes for the pawn.",
        "勝つのは Rc5+ だけ。まずチェックで黒キングに方向を決めさせ、その側をルークで遮断し、キングがポーンを取りに来る。"],
      src: ONE },
    { id: "rp-front", g: "rp", fen: "8/1K6/8/8/5p2/1R6/7k/8 w - - 0 1", goal: "win", v: "tb", key: ["Rf3"],
      n: ["车对兵：挡在兵前", "Rook v pawn: block it", "ルーク対ポーン：前をふさぐ"],
      tip: ["唯一的赢法是 Rf3：车站到兵的前面把它拦住，黑王来护兵的工夫，你的王从后面赶来。",
        "Only Rf3 wins: the rook stands in front of the pawn, and while Black's king comes to help it, your king comes up behind.",
        "勝つのは Rf3 だけ。ルークがポーンの前をふさぎ、黒キングが助けに来る間にこちらのキングが追いつく。"],
      src: ONE },
    { id: "rp-pin", g: "rp", fen: "8/K7/R7/8/8/8/3n2k1/8 w - - 0 1", goal: "win", v: "tb", key: ["Ra2"],
      n: ["车对马：牵制", "Rook v knight: the pin", "ルーク対ナイト：ピン"],
      tip: ["Ra2！ 马和王在同一横线上，马被钉住了。黑王来保护它之前，你的王赶过去。",
        "Ra2! Knight and king share a rank, so the knight is pinned. Bring your king over before Black's can protect it.",
        "Ra2！ ナイトとキングが同じ段にいてピンされる。黒キングが守りに来る前に、こちらのキングが向かう。"],
      src: ONE },
    { id: "rp-dominate", g: "rp", fen: "3k4/8/8/4K3/8/n7/8/2R5 w - - 0 1", goal: "win", v: "tb", key: ["Rc5"],
      n: ["车困马", "Rook v knight: domination", "ルーク対ナイト：封じ込め"],
      tip: ["马离王太远就危险。只有 Rc5 能赢：车看住 b5、c4、c2，马只剩一个格子，王再过来收网。",
        "A knight far from its king is in danger. Only Rc5 wins: the rook covers b5, c4 and c2, leaving the knight one square, and your king closes the net.",
        "キングから遠いナイトは危ない。勝つのは Rc5 だけ。ルークが b5・c4・c2 を押さえてナイトの行き場を一つにし、キングで仕留める。"],
      src: ONE },
    { id: "rp-skewer-b", g: "rp", fen: "3K1k2/8/R7/5b2/8/8/8/8 w - - 0 1", goal: "win", v: "tb", key: ["Rf6+"],
      n: ["车对象：串击", "Rook v bishop: the skewer", "ルーク対ビショップ：スキュア"],
      tip: ["Rf6+！ 将军的同时攻击 f5 的象，黑王一让开，车就把象吃掉。",
        "Rf6+! The check also hits the bishop on f5; once the king steps aside, the rook takes it.",
        "Rf6+！ チェックと同時に f5 のビショップを狙う。キングがよければビショップを取れる。"],
      src: ONE },
    { id: "rp-pawns", g: "rp", fen: "8/r7/5PP1/8/8/K7/8/2k5 w - - 0 1", goal: "win", v: "tb",
      n: ["连兵胜车", "Two pawns beat the rook", "連結ポーンがルークに勝つ"],
      tip: ["两个连着的兵到了第 6 横线，车一个人挡不住。先让王躲开车的将军（往兵那边走），兵再推。",
        "Two connected pawns on the sixth are too much for a lone rook. Escape the checks first — walk towards your pawns — then push.",
        "6 段目の連結ポーン 2 本は、ルーク 1 枚では止められない。まずチェックをかわし（ポーンの方へ歩く）、それから突く。"],
      src: THEORY },
    // v8-3-plan T5: ten more rook endings — seven of them five-man positions
    // still waiting for the online table (`pend`, see the top of this file)
    { id: "rp-saavedra", g: "rp", fen: "8/8/1KP5/3r4/8/8/8/k7 w - - 0 1", goal: "win", v: "tb", key: ["c7"],
      n: ["萨维德拉", "Saavedra", "サーベドラ"],
      tip: ["c7！ 黑车从后面不停将军，王顺着往下躲到 c2。黑车再走 d4，是等你变后时 Rc4+ 弃车逼和 —— 这时变成车（c8=R），威胁 Ra8 将杀。",
        "c7! The rook checks from behind; walk your king down to c2. If it then goes to d4, waiting for c8=Q Rc4+ and stalemate, promote to a rook instead (c8=R), threatening Ra8 mate.",
        "c7！ 後ろからのチェックはキングを c2 まで下げてかわす。ルークが d4 に来たら、c8=Q には Rc4+ でステイルメイトの狙い。ルークに昇格（c8=R）して Ra8 メイトを狙う。"],
      src: ["萨维德拉（1895）", "Saavedra (1895)", "サーベドラ（1895 年）"] },
    { id: "rp-knight", g: "rp", fen: "3K4/2P5/3k4/8/8/8/8/7r w - - 0 1", goal: "draw", v: "tb", key: ["c8=N+"],
      n: ["升变成马", "Promote to a knight", "ナイトに昇格"],
      tip: ["黑方威胁 Rh8 将杀，c8=Q 正好被 Rh8 将死。只有 c8=N+ 能守和：带将升变成马，之后王和马站在一起，车对马守得住。",
        "Black threatens Rh8 mate, and c8=Q walks straight into it. Only c8=N+ holds: promote to a knight with check, then keep king and knight together — rook against knight is a draw.",
        "黒は Rh8 メイトを狙っており、c8=Q ではそのままメイト。引き分けにできるのは c8=N+ だけ：チェックでナイトに昇格し、キングとナイトを離さなければルーク対ナイトは守れる。"],
      src: ONE },
    { id: "rp-kingrun", g: "rp", fen: "8/8/8/7K/1kp5/8/8/R7 w - - 0 1", goal: "win", v: "tb", key: ["Kg4"],
      n: ["车对兵：王走斜线", "Rook v pawn: the king's diagonal", "ルーク対ポーン：キングは斜めに"],
      tip: ["有王护送的兵，车一个人拦不住，你的王得赶回来。只有 Kg4 能赢：斜着走，既靠近兵，又朝着兵要去的底线。",
        "The rook alone cannot stop a pawn escorted by its king; yours has to come back. Only Kg4 wins: go diagonally, towards the pawn and towards the rank it is heading for.",
        "キングに護衛されたポーンはルーク一人では止められず、キングを戻す必要がある。勝つのは Kg4 だけ：斜めに進み、ポーンにも、ポーンが向かう 1 段目にも近づく。"],
      src: ONE },
    { id: "rp-longside", g: "rp", fen: "R7/8/8/8/4p3/4k3/7r/5K2 w - - 0 1", goal: "draw", v: "pend",
      n: ["长边防守", "The long-side defence", "ロングサイドの守り"],
      tip: ["你的王在兵的短边（f、g、h 线），车就该在长边（a 线）。从远处横着将军：车和黑王隔三条线以上，黑王就躲不开将军。",
        "Your king is on the pawn's short side (the f-, g- and h-files), so your rook belongs on the long side, the a-file. Check from the side, from far away: three files or more from the king, and it cannot escape the checks.",
        "キングがポーンのショートサイド（f・g・h ファイル）にいるので、ルークはロングサイド（a ファイル）へ。遠くから横にチェックする：3 ファイル以上離れていれば、黒キングはチェックから逃げられない。"],
      src: FLIP(THEORY) },
    { id: "rp-shortside", g: "rp", fen: "2k5/8/4K3/4P3/8/8/7r/R7 w - - 0 1", goal: "win", v: "pend",
      n: ["对方的车在短边", "Their rook on the short side", "相手のルークがショートサイド"],
      tip: ["黑王去了长边（c8），车只好留在短边（h 线），离你的王太近，横着将军不起作用。王护着兵往前走，再用车把黑王挡在远处。",
        "Black's king went to the long side (c8), leaving its rook the short side (the h-file) — too close to your king for side checks to work. Walk king and pawn forward, and use your rook to keep Black's king away.",
        "黒キングはロングサイド（c8）へ行き、ルークはショートサイド（h ファイル）に残った。近すぎて横からのチェックは効かない。キングとポーンで前進し、ルークで黒キングを遠ざける。"],
      src: THEORY },
    { id: "rp-backrank", g: "rp", fen: "1r2k3/R7/4PK2/8/8/8/8/8 w - - 0 1", goal: "win", v: "pend",
      n: ["底线防守挡不住中心兵", "Back rank v centre pawn", "8 段目の守りは中央ポーンに負ける"],
      tip: ["黑车守底线、王在兵前，这种被动防守挡不住中心兵：Rg7（或 Rh7）威胁在第 8 横线将杀，黑王只好走 d8，车再将军就串击到 b8 的车。",
        "Rook on the back rank, king in front of the pawn: against a centre pawn that passive defence fails. Rg7 (or Rh7) threatens mate on the eighth rank; the king has to go to d8, and the rook's check then skewers the rook on b8.",
        "ルークは 8 段目、キングはポーンの前。この受け身の守りは中央ポーンには通用しない。Rg7（か Rh7）で 8 段目のメイトを狙えば、キングは d8 へ行くしかなく、ルークのチェックが b8 のルークへのスキュアになる。"],
      src: THEORY },
    { id: "rp-backrank-g", g: "rp", fen: "8/8/8/8/8/5kp1/r7/1R4K1 w - - 0 1", goal: "draw", v: "pend",
      n: ["底线防守：g 兵守得住", "Back rank v g-pawn: it holds", "1 段目の守り：g ポーンなら持つ"],
      tip: ["车守第 1 横线、王在兵前。对中心兵这样会输，对 g 兵却守得住：王在 g1、h1 之间走，车沿第 1 横线来回，有机会就从侧面将军。",
        "Rook on the first rank, king in front of the pawn. Against a centre pawn this passive defence loses; against a g-pawn it holds: king between g1 and h1, rook along the first rank, checking from the side when it can.",
        "ルークは 1 段目、キングはポーンの前。中央ポーンなら負けるこの受けも、g ポーンなら持つ。キングは g1・h1 の間、ルークは 1 段目を往復し、機会があれば横からチェック。"],
      src: FLIP(THEORY) },
    { id: "rp-tarrasch", g: "rp", fen: "r7/6k1/P7/8/8/3K4/8/R7 w - - 0 1", goal: "win", v: "pend",
      n: ["车在通路兵后面", "Rook behind the passed pawn", "パスポーンの後ろのルーク"],
      tip: ["塔拉什的原则：车要放在通路兵的后面。你的车从 a1 推着兵，黑车只能堵在前面；黑王离得远，你的王走到 b7 附近，黑车就守不住了。",
        "Tarrasch's rule: rooks belong behind passed pawns. Yours pushes from a1 and Black's is stuck in front; with Black's king far away, your king walks up to b7 and the rook cannot hold.",
        "タラッシュの原則：ルークはパスポーンの後ろに。こちらは a1 から押し、黒ルークは前でふさぐしかない。黒キングが遠いので、キングが b7 付近まで来ればルークは持たない。"],
      src: THEORY },
    { id: "rp-apawn-far", g: "rp", fen: "K7/P3k3/8/8/1r6/8/8/7R w - - 0 1", goal: "win", v: "pend",
      n: ["边兵：对方的王太远", "Rook pawn: the king too far", "ルークポーン：キングが遠すぎる"],
      tip: ["你的王被关在 a8。黑王在 e7，离得太远：Rh8 再 Rb8，挡住黑车、给王让出 b7，兵就能升变。黑王要是在 d7、c7，这就是和棋。",
        "Your king is shut in on a8. Black's king on e7 is too far: Rh8 and Rb8 block the black rook and free b7 for your king, and the pawn goes through. With Black's king on d7 or c7 it would be a draw.",
        "キングは a8 に閉じ込められている。黒キングは e7 で遠すぎる：Rh8 から Rb8 で黒ルークを遮り、キングに b7 を空ければポーンは昇格できる。黒キングが d7・c7 にいればドロー。"],
      src: THEORY },
    { id: "rp-apawn-near", g: "rp", fen: "7r/1R6/8/8/8/8/p2K4/k7 w - - 0 1", goal: "draw", v: "pend",
      n: ["边兵：把王关在角上", "Rook pawn: keep the king in the corner", "ルークポーン：キングを隅に閉じ込める"],
      tip: ["黑王困在 a1，出口是 b1、b2。你的车守住 b 线，王守在 c1、c2 一带，黑方就赢不了。车被赶走时先从侧面将军，再回到 b 线。",
        "Black's king is stuck on a1, its exits b1 and b2. Hold the b-file with your rook and keep your king near c1/c2, and Black cannot win. If the rook is chased off, check from the side first, then go back to the b-file.",
        "黒キングは a1 に閉じ込められ、出口は b1・b2。ルークで b ファイルを押さえ、キングを c1・c2 付近に置けば黒は勝てない。ルークを追われたら、まず横からチェックして b ファイルへ戻る。"],
      src: FLIP(THEORY) },

    // —— 轻子 ——
    { id: "mi-bb", g: "mi", fen: "8/8/8/4k3/8/8/8/KBB5 w - - 0 1", goal: "win", v: "tb",
      n: ["双象杀王", "Two bishops mate", "2 ビショップのメイト"],
      tip: ["两个象并排站在相邻的斜线上织成一张网，王在后面帮忙，把黑王一步步赶进任意一个角落将死。",
        "Side by side on neighbouring diagonals the bishops make a net; with your king's help, drive Black's king into any corner and mate.",
        "2 つのビショップを隣り合う対角線に並べて網を作り、キングの助けで黒キングをどの隅へでも追い込んでメイト。"],
      src: THEORY },
    { id: "mi-bn", g: "mi", fen: "8/8/8/4k3/8/8/8/KBN5 w - - 0 1", goal: "win", v: "tb",
      n: ["象马杀王", "Bishop and knight mate", "ビショップとナイトのメイト"],
      tip: ["只能在和象同色的角落将死（这里是 a8 或 h1）。先把黑王赶到边上，再用马的 W 形路线把它推向对的角落。50 回合内要完成。",
        "Mate only happens in a corner of the bishop's colour (a8 or h1 here). Drive the king to the edge, then walk it to the right corner with the knight's W-manoeuvre — inside fifty moves.",
        "メイトできるのはビショップと同じ色の隅（ここでは a8 か h1）。まず黒キングを端へ追い、ナイトの W 字の動きで正しい隅へ運ぶ。50 手以内に。"],
      src: THEORY },
    { id: "mi-bn-corner", g: "mi", fen: "7k/8/5K2/8/8/8/8/5BN1 w - - 0 1", goal: "win", v: "tb",
      n: ["象马杀王：错的角落", "Bishop and knight: the wrong corner", "B+N：間違った隅"],
      tip: ["黑王躲在 h8，可你的象走白格，h8 是黑格 —— 在这个角杀不了。要沿着底线把它赶到 a8。",
        "Black's king sits on h8, but your bishop is light-squared and h8 is dark: no mate there. Herd it along the edge to a8.",
        "黒キングは h8 にいるが、あなたのビショップは白マス、h8 は黒マス。この隅ではメイトできない。端に沿って a8 へ追う。"],
      src: THEORY },
    { id: "mi-bp", g: "mi", fen: "7k/8/8/7P/8/8/3B4/6K1 w - - 0 1", goal: "win", v: "tb",
      n: ["对色的象", "The right bishop", "正しい色のビショップ"],
      tip: ["h 兵加黑格象：升变格 h8 是黑格，象控制得到它，黑王在角落里挡不住。王过来，兵推上去。",
        "An h-pawn with a dark-squared bishop: the queening square h8 is dark, the bishop covers it, and the king in the corner cannot hold it. Bring the king, push the pawn.",
        "h ポーンと黒マスのビショップ。昇格マス h8 は黒マスでビショップが利くので、隅のキングでは止められない。キングを寄せてポーンを進める。"],
      src: THEORY },
    { id: "mi-bp-run", g: "mi", fen: "8/8/4K3/8/7P/5B1k/8/8 w - - 0 1", goal: "win", v: "tb", key: ["h5"],
      n: ["错色象也能赢", "The wrong bishop can still win", "違う色のビショップでも勝てる"],
      tip: ["象不对色（白格象，h8 是黑格），但黑王还在兵的后面。只有马上 h5 才赢：黑王追不上，也钻不进角落。",
        "Wrong bishop (light, and h8 is dark) — but Black's king is behind the pawn. Only h5 at once wins: the king can neither catch it nor reach the corner.",
        "ビショップの色は違う（白マス、h8 は黒マス）が、黒キングはポーンの後ろ。すぐ h5 だけが勝ち：追いつけず、隅にも入れない。"],
      src: ONE },
    { id: "mi-np", g: "mi", fen: "4k3/8/8/8/4P3/2N5/8/4K3 w - - 0 1", goal: "win", v: "tb",
      n: ["马兵对王", "Knight and pawn", "ナイトとポーン"],
      tip: ["王护兵，马看住黑王想站的格子，稳步推进。黑王被赶到角落时小心逼和。",
        "King guards the pawn, knight takes away the squares Black's king wants; advance steadily, and watch for stalemate once the king is cornered.",
        "キングがポーンを守り、ナイトは黒キングの行きたいマスを奪う。着実に進め、隅に追い込んだらステイルメイトに注意。"],
      src: THEORY },
    { id: "mi-np-guard", g: "mi", fen: "8/8/8/8/4k1K1/4P3/7N/8 w - - 0 1", goal: "win", v: "tb", key: ["Nf1"],
      n: ["马从后面护兵", "The knight guards from behind", "ナイトが後ろから守る"],
      tip: ["只有 Nf1 能赢：马从后面保护 e3 兵，黑王吃不到它，你的王腾出手来。",
        "Only Nf1 wins: the knight guards e3 from behind, Black's king cannot take it, and your king is free to act.",
        "勝つのは Nf1 だけ。ナイトが後ろから e3 を守り、黒キングは取れず、こちらのキングが自由になる。"],
      src: ONE },
    { id: "mi-np-king", g: "mi", fen: "8/8/5k2/5P2/8/3K4/8/1N6 w - - 0 1", goal: "win", v: "tb", key: ["Ke4"],
      n: ["王先护兵", "King to the pawn first", "まずキングでポーンを守る"],
      tip: ["只有 Ke4 能赢：f5 兵马上就要被吃，王先去保护它，马再慢慢过来。",
        "Only Ke4 wins: f5 is about to fall, so the king guards it first and the knight follows later.",
        "勝つのは Ke4 だけ。f5 は取られそうなので、まずキングで守り、ナイトは後からゆっくり来る。"],
      src: ONE },
    { id: "mi-n-stop", g: "mi", fen: "8/8/8/8/2k5/8/2p3K1/3N4 w - - 0 1", goal: "draw", v: "tb", key: ["Ne3+"],
      n: ["马拦兵：带将的双击", "Knight v pawn: the forking check", "ナイト対ポーン：チェックの両当たり"],
      tip: ["只有 Ne3+ 能守和：将军的同时看住 c2，下一步把兵吃掉就是和棋。",
        "Only Ne3+ holds: the check also covers c2, and taking the pawn next move is a draw.",
        "引き分けにできるのは Ne3+ だけ。チェックと同時に c2 を押さえ、次にポーンを取ればドロー。"],
      src: ONE },
    { id: "mi-n-stop2", g: "mi", fen: "8/8/8/8/8/1N6/5p1K/3k4 w - - 0 1", goal: "draw", v: "tb", key: ["Kg2"],
      n: ["马拦兵：王来帮忙", "Knight v pawn: the king helps", "ナイト対ポーン：キングの助け"],
      tip: ["马离得太远，只有王能救：Kg2 看住 f1，马再绕回来。",
        "The knight is too far away; only the king saves it: Kg2 covers f1, and the knight comes round after.",
        "ナイトは遠すぎる。救えるのはキングだけ：Kg2 で f1 を押さえ、ナイトは後から戻る。"],
      src: ONE },
    { id: "mi-b-stop", g: "mi", fen: "8/8/8/2B5/4k3/8/2p5/6K1 w - - 0 1", goal: "draw", v: "tb", key: ["Ba3"],
      n: ["象拦兵", "Bishop v pawn", "ビショップ対ポーン"],
      tip: ["只有 Ba3 能守和：象站上 a3–c1 这条斜线守住升变格，黑兵永远变不了后。",
        "Only Ba3 holds: on the a3–c1 diagonal the bishop guards the queening square for good.",
        "引き分けにできるのは Ba3 だけ。a3–c1 の対角線から昇格マスをずっと守る。"],
      src: ONE },
    { id: "mi-b-stop2", g: "mi", fen: "8/8/6B1/8/8/8/5pK1/4k3 w - - 0 1", goal: "draw", v: "tb", key: ["Bd3"],
      n: ["象拦兵：看住 f1", "Bishop v pawn: watch f1", "ビショップ対ポーン：f1 を見張る"],
      tip: ["只有 Bd3 能守和：象从 d3 看住 f1，王也盯着它，黑兵过不去。",
        "Only Bd3 holds: from d3 the bishop covers f1, the king watches it too, and the pawn cannot get through.",
        "引き分けにできるのは Bd3 だけ。d3 から f1 を押さえ、キングも見張るのでポーンは進めない。"],
      src: ONE },
    // v8-3-plan T5: ten more minor-piece endings
    { id: "mi-p-vs-n", g: "mi", fen: "8/6k1/4n3/PK6/8/8/8/8 w - - 0 1", goal: "win", v: "tb", key: ["Kb6"],
      n: ["马拦不住边兵", "The knight and the rook pawn", "ナイトとルークポーン"],
      tip: ["马最怕边兵：在棋盘边上它能走的格子少。只有 Kb6：王先看住 c7、b7、a7，马找不到拦兵的格子，兵再推上去。",
        "A knight hates rook pawns: on the edge it has few squares. Only Kb6: your king covers c7, b7 and a7, the knight finds no square in front of the pawn, and the pawn walks in.",
        "ナイトはルークポーンが苦手：盤の端では行けるマスが少ない。正解は Kb6 だけ：キングが c7・b7・a7 を押さえればナイトはポーンの前に出られず、ポーンは進んでいく。"],
      src: ONE },
    { id: "mi-n-trapped", g: "mi", fen: "8/8/8/8/3k4/p7/8/n1K5 w - - 0 1", goal: "draw", v: "tb", key: ["Kb1"],
      n: ["困在角上的马", "The knight in the corner", "隅に閉じ込められたナイト"],
      tip: ["黑马缩在 a1 角上，a3 的兵也帮不了它。只有 Kb1：王贴住马，抢在黑王过来之前吃掉马或兵 —— 剩下的子力赢不了你。",
        "The knight is stuck in the a1 corner and the a3 pawn cannot help it. Only Kb1: stay on top of the knight and take it (or the pawn) before Black's king arrives — what is left cannot beat you.",
        "a1 の隅のナイトは身動きが取れず、a3 のポーンも助けにならない。正解は Kb1 だけ：ナイトに張り付き、黒キングが来る前にナイトかポーンを取る。残りの駒では勝てない。"],
      src: ONE },
    { id: "mi-wrong-race", g: "mi", fen: "8/8/1b6/8/7p/8/3K4/1k6 w - - 0 1", goal: "draw", v: "tb", key: ["Ke2"],
      n: ["错色象：抢进角落", "Wrong bishop: race to the corner", "違う色のビショップ：隅へ急ぐ"],
      tip: ["黑象走黑格，h 兵的升变格 h1 却是白格：你的王进了这个角就是和棋。只有 Ke2：经过 f3 赶到兵前（e3 有象看着）。",
        "Black's bishop runs on dark squares, but the h-pawn queens on h1, a light square: get your king into that corner and it is a draw. Only Ke2, on via f3 to the front of the pawn (the bishop covers e3).",
        "黒のビショップは黒マス、h ポーンの昇格マス h1 は白マス。キングがこの隅に入ればドロー。正解は Ke2 だけ：f3 を通ってポーンの前へ急ぐ（e3 はビショップが利いている）。"],
      src: FLIP(THEORY) },
    { id: "mi-bp-save", g: "mi", fen: "8/2k5/2P5/8/8/8/8/KB6 w - - 0 1", goal: "win", v: "tb", key: ["Be4"],
      n: ["象兵对王：先保住兵", "Bishop and pawn: save the pawn first", "ビショップとポーン：まずポーンを守る"],
      tip: ["黑王正在攻击 c6。只有 Be4 能赢：象从 e4 保护兵，你的王再从 a1 赶过来，护送兵升变。",
        "Black's king is attacking c6. Only Be4 wins: the bishop guards the pawn from e4 while your king comes all the way from a1 to see it home.",
        "黒キングが c6 を狙っている。勝つのは Be4 だけ：ビショップで e4 からポーンを守り、その間にキングが a1 から駆けつけて昇格を助ける。"],
      src: ONE },
    { id: "mi-same-b", g: "mi", fen: "8/2P3k1/1K2b3/8/B7/8/8/8 w - - 0 1", goal: "win", v: "pend",
      n: ["同色象：挡住斜线", "Same-coloured bishops: block the diagonal", "同色ビショップ：対角線をふさぐ"],
      tip: ["黑象沿 h3–c8、a6–c8 两条斜线看住 c8。王先走到 d6 护住 d7，再用 Bd7 挡住一条；黑象换到另一条上，王再绕过去把它赶开，兵就能升变。",
        "Black's bishop guards c8 along two diagonals, h3–c8 and a6–c8. Bring your king to d6 to cover d7 and block one with Bd7; when the bishop switches to the other, go round with the king and chase it off, and the pawn queens.",
        "黒ビショップは h3–c8 と a6–c8 の 2 本で c8 を守る。キングを d6 に運んで d7 を守り、Bd7 で 1 本をふさぐ。ビショップがもう 1 本に移ったら、キングで回り込んで追い払えばポーンは昇格する。"],
      src: THEORY },
    { id: "mi-opp-b", g: "mi", fen: "8/8/8/K2b4/7B/4pk2/8/8 w - - 0 1", goal: "draw", v: "pend",
      n: ["异色象：一条斜线就够", "Opposite bishops: one diagonal is enough", "異色ビショップ：対角線 1 本で足りる"],
      tip: ["两个象颜色不同，黑象永远碰不到你的黑格。象始终看住 e1（沿 h4–e1 或 a5–e1 斜线），黑兵就变不了后；王远一点也不要紧。",
        "The bishops run on different colours, so Black's can never touch your dark squares. Keep yours guarding e1 (on the h4–e1 or a5–e1 diagonal) and the pawn never queens — your king being far away does not matter.",
        "ビショップの色が違うので、黒ビショップはこちらの黒マスに手を出せない。ビショップで e1 を守り続ければ（h4–e1 か a5–e1 の対角線）、ポーンは昇格できない。キングが遠くても構わない。"],
      src: FLIP(THEORY) },
    { id: "mi-b-vs-n", g: "mi", fen: "8/5k2/P1n5/8/2K5/3B4/8/8 w - - 0 1", goal: "win", v: "pend",
      n: ["象兵对马", "Bishop and pawn v knight", "ビショップとポーン対ナイト"],
      tip: ["白格象看住升变格 a8，马只能从 b6、c7 或者堵在 a7 拦兵 —— 都是你的王走得到的格子。王走过去把马赶开，兵就推得上去；黑王在 f7，赶不回来。",
        "Your light-squared bishop covers a8, so the knight can only stop the pawn from b6, c7 or by sitting on a7 — all squares your king can reach. Walk over, drive it off and push; Black's king on f7 is too far away.",
        "白マスのビショップが a8 を押さえるので、ナイトがポーンを止めるには b6・c7 か a7 に陣取るしかない。どれもキングで届くマス。キングで追い払ってポーンを進める。f7 の黒キングは遠すぎる。"],
      src: THEORY },
    { id: "mi-b-vs-np", g: "mi", fen: "8/8/8/7B/2n5/3pk3/8/K7 w - - 0 1", goal: "draw", v: "pend",
      n: ["象对马兵：看住斜线", "Bishop v knight and pawn", "ビショップ対ナイトとポーン"],
      tip: ["你的王一时赶不过来，只能靠象：象在 h5–d1 斜线上看住 d1，兵就变不了后。马来挡斜线，就换到另一条（a4–d1）；实在不行就用象换掉兵。",
        "Your king cannot get there in time, so it is all the bishop: on the h5–d1 diagonal it guards d1 and the pawn cannot queen. If the knight blocks the diagonal, switch to the other one (a4–d1); if all else fails, give the bishop for the pawn.",
        "キングはすぐには間に合わず、頼りはビショップ。h5–d1 の対角線で d1 を守ればポーンは昇格できない。ナイトが対角線をふさいだらもう 1 本（a4–d1）へ。最後はビショップをポーンと交換すればよい。"],
      src: FLIP(THEORY) },
    { id: "mi-n-block", g: "mi", fen: "8/8/8/1b6/8/3pk3/3N4/2K5 w - - 0 1", goal: "draw", v: "pend",
      n: ["马堵在兵前", "The knight blockade", "ナイトの封鎖"],
      tip: ["马堵在兵前面的 d2。这是黑格，黑方的白格象永远赶不走它；马就算被逼着走开，也要一直看住 d2、d1。王守在旁边护着马，黑方就没有突破口。",
        "The knight sits on d2, in front of the pawn — a dark square, which Black's light-squared bishop can never attack. If it has to move, keep it watching d2 and d1, and keep your king close to guard it: Black has no way through.",
        "ナイトはポーンの前の d2 に陣取る。黒マスなので、黒の白マスビショップには攻められない。動かされても d2・d1 を見張り続け、キングをそばに置いて守れば、黒に突破口はない。"],
      src: FLIP(THEORY) },
    { id: "mi-n-vs-n", g: "mi", fen: "8/5n2/3P4/2K5/2N5/8/6k1/8 w - - 0 1", goal: "win", v: "pend",
      n: ["马兵对马", "Knight and pawn v knight", "ナイトとポーン対ナイト"],
      tip: ["黑王在 g2，远得帮不上忙。马上推 d7，黑马只能去 d8 堵着；你的马去攻击它（比如 Ne5、Nc6），王守住它能逃去的格子，兵就能升变。",
        "Black's king on g2 is too far to help. Push d7 at once and the knight can only blockade on d8; attack it with your knight (Ne5, Nc6) while your king covers its escape squares, and the pawn queens.",
        "g2 の黒キングは遠くて役に立たない。すぐ d7 と突けば、黒ナイトは d8 でふさぐしかない。こちらのナイトで攻め（Ne5・Nc6）、キングで逃げ場を押さえればポーンは昇格する。"],
      src: THEORY },

    // —— 后 ——
    { id: "qu-kqk", g: "qu", fen: "4k3/8/8/8/8/8/8/Q3K3 w - - 0 1", goal: "win", v: "tb",
      n: ["后杀王", "Queen and king mate", "クイーンでのメイト"],
      tip: ["后和黑王保持马步距离锁住它，一圈圈缩小它的地盘；王走近以后在边线将死。别把它逼和。",
        "Keep the queen a knight's move from Black's king to box it in, shrink the box, then bring your king and mate on the edge. Avoid stalemate.",
        "クイーンを黒キングからナイトの一跳びの位置に置いて閉じ込め、囲いを狭める。キングを寄せて端でメイト。ステイルメイトに注意。"],
      src: THEORY },
    { id: "qu-epawn", g: "qu", fen: "Q7/8/2K5/8/8/8/4p3/5k2 w - - 0 1", goal: "win", v: "tb",
      n: ["后对七线中心兵", "Queen v centre pawn on the seventh", "クイーン対 7 段目の中央ポーン"],
      tip: ["连续将军，逼黑王站到兵的前面（e1）挡住自己的兵；每逼一次，你的王就走近一步。",
        "Check, check, until Black's king has to stand in front of its own pawn (on e1); each time it does, your king takes a step closer.",
        "チェックを続けて黒キングを自分のポーンの前（e1）に立たせる。そうなるたびに、こちらのキングが一歩近づく。"],
      src: THEORY },
    { id: "qu-dpawn", g: "qu", fen: "8/2K5/8/8/8/8/2kp4/Q7 w - - 0 1", goal: "win", v: "tb",
      n: ["后对 d 兵", "Queen v d-pawn", "クイーン対 d ポーン"],
      tip: ["同一个办法：将军、牵制，逼黑王站到 d1 挡住兵，每赢到一步就让王靠近。",
        "The same method: check and pin until the king must block its pawn on d1, and use every such tempo to bring your king closer.",
        "同じ方法：チェックとピンで黒キングを d1 に立たせてポーンをふさがせ、その一手ごとにキングを近づける。"],
      src: THEORY },
    { id: "qu-apawn", g: "qu", fen: "Q7/8/8/3K4/8/8/p7/1k6 w - - 0 1", goal: "win", v: "tb",
      n: ["后对边兵：王离得近", "Queen v rook pawn, king close", "クイーン対ルークポーン：キングが近い"],
      tip: ["边兵本来能靠逼和守住，但你的王已经够近。先将军，再把王带过来，在逼和之前将死。",
        "A rook pawn usually saves itself by stalemate, but your king is close enough. Check first, bring the king, and mate before stalemate comes into it.",
        "ルークポーンはふつうステイルメイトで助かるが、こちらのキングが十分近い。まずチェック、キングを寄せ、ステイルメイトの前にメイト。"],
      src: THEORY },
    { id: "qu-cpawn", g: "qu", fen: "8/8/8/4K3/3Q4/1k6/2p5/8 w - - 0 1", goal: "win", v: "tb", key: ["Qa1"],
      n: ["后对 c 兵：王离得近", "Queen v c-pawn, king close", "クイーン対 c ポーン：キングが近い"],
      tip: ["只有 Qa1 能赢：后看住 c1 和整条底线。c 兵的逼和招数只在你的王离得远时才管用。",
        "Only Qa1 wins: the queen covers c1 and the whole back rank. The c-pawn's stalemate trick only works when your king is far away.",
        "勝つのは Qa1 だけ。クイーンが c1 と 1 段目全体を押さえる。c ポーンのステイルメイトの手は、キングが遠いときだけ通用する。"],
      src: ONE },
    { id: "qu-fpawn", g: "qu", fen: "8/8/5K2/8/7Q/4k3/5p2/8 w - - 0 1", goal: "win", v: "tb", key: ["Qc4"],
      n: ["后对 f 兵", "Queen v f-pawn", "クイーン対 f ポーン"],
      tip: ["只有 Qc4 能赢：后从 c4 看住 f1 所在的斜线，黑兵变不了后，然后王走过来。",
        "Only Qc4 wins: from c4 the queen watches the diagonal through f1, so the pawn cannot queen, and your king walks over.",
        "勝つのは Qc4 だけ。c4 から f1 を通る対角線を押さえて昇格を防ぎ、それからキングが歩いてくる。"],
      src: ONE },
    { id: "qu-qvr", g: "qu", fen: "2Q5/8/3r4/4k3/8/8/8/4K3 w - - 0 1", goal: "win", v: "tb",
      n: ["后对车", "Queen v rook", "クイーン対ルーク"],
      tip: ["先把黑王逼到边上；车一离开王的保护，就用带将军的双击把它赢下来，再用后杀王。",
        "Drive the king to the edge first; the moment the rook strays from its king, win it with a forking check, then mate.",
        "まず黒キングを端へ。ルークがキングの守りを離れた瞬間、チェックの両当たりで取り、それからメイト。"],
      src: THEORY },
    { id: "qu-qvr-quiet", g: "qu", fen: "Q7/K1k5/8/8/1r6/8/8/8 w - - 0 1", goal: "win", v: "tb", key: ["Qe8"],
      n: ["后对车：安静的一步", "Queen v rook: the quiet move", "クイーン対ルーク：静かな一手"],
      tip: ["唯一的赢法是不将军的 Qe8：先把好格子都占住，让黑方自己走出破绽。",
        "The only win is the quiet Qe8: take the good squares first and let Black be the one who has to loosen something.",
        "勝つのはチェックしない Qe8 だけ。先に良いマスを占め、黒に自分から崩れさせる。"],
      src: ONE },
    { id: "qu-qvb", g: "qu", fen: "8/8/3kb3/8/8/8/8/K5Q1 w - - 0 1", goal: "win", v: "tb",
      n: ["后对象", "Queen v bishop", "クイーン対ビショップ"],
      tip: ["用后把王和象分开，找一个能同时将军又攻击象的格子。",
        "Use the queen to split king and bishop, then find a square that checks and attacks the bishop at once.",
        "クイーンでキングとビショップを引き離し、チェックとビショップ攻撃を同時にかけるマスを探す。"],
      src: THEORY },
    { id: "qu-qvn", g: "qu", fen: "8/8/3kn3/8/8/8/8/K5Q1 w - - 0 1", goal: "win", v: "tb",
      n: ["后对马", "Queen v knight", "クイーン対ナイト"],
      tip: ["马离王一远就容易被捉双：把黑王赶到边上，再找将军兼捉马的一步。",
        "A knight that strays from its king gets forked: push the king to the edge and look for the check that also hits the knight.",
        "キングから離れたナイトは両当たりを食う。黒キングを端に追い、チェックとナイト攻撃を兼ねる手を探す。"],
      src: THEORY },
    { id: "qu-skewer", g: "qu", fen: "7q/8/8/8/3k4/8/8/1Q4K1 w - - 0 1", goal: "win", v: "tb", key: ["Qb2+", "Qa1+"],
      n: ["后对后：大斜线串击", "Queen v queen: the long diagonal", "クイーン対クイーン：長い対角線"],
      tip: ["Qb2+（或 Qa1+）沿大斜线将军，黑王一让开，h8 的后就归你了。",
        "Qb2+ (or Qa1+) checks down the long diagonal; when the king steps off it, the queen on h8 is yours.",
        "Qb2+（または Qa1+）で長い対角線からチェック。キングがよければ h8 のクイーンが取れる。"],
      src: ONE },
    { id: "qu-skewer2", g: "qu", fen: "8/4q3/8/2k5/8/5Q2/8/7K w - - 0 1", goal: "win", v: "tb", key: ["Qa3+"],
      n: ["后对后：斜线串击", "Queen v queen: the diagonal skewer", "クイーン対クイーン：対角線のスキュア"],
      tip: ["只有 Qa3+ 能赢：王和后站在同一条斜线上，将军以后吃 e7 的后。",
        "Only Qa3+ wins: king and queen share a diagonal, so check, and take the queen on e7.",
        "勝つのは Qa3+ だけ。キングとクイーンが同じ対角線上にいるので、チェックして e7 のクイーンを取る。"],
      src: ONE },
    // v8-3-plan T5: six more of queen against pawn
    { id: "qu-bpawn", g: "qu", fen: "8/8/5K2/8/8/8/1pk5/7Q w - - 0 1", goal: "win", v: "tb",
      n: ["后对 b 兵", "Queen v b-pawn", "クイーン対 b ポーン"],
      tip: ["b 兵和中心兵一样能赢：连续将军，逼黑王站到 b1 挡住自己的兵，每赢到一步，你的王就走近一步。",
        "A knight's pawn loses like a centre pawn: check after check, drive Black's king onto b1 in front of its pawn, and use each free move to bring your king a step closer.",
        "b ポーンも中央ポーンと同じく勝てる：チェックを続けて黒キングを b1（ポーンの前）に追い込み、手が空くたびにキングを一歩近づける。"],
      src: THEORY },
    { id: "qu-gpawn", g: "qu", fen: "K7/8/8/8/8/8/6pk/Q7 w - - 0 1", goal: "win", v: "tb",
      n: ["后对 g 兵", "Queen v g-pawn", "クイーン対 g ポーン"],
      tip: ["你的王远在 a8，但 g 兵没有逼和的招：把黑王逼到 g1 挡住兵，王一步步走过来，再把兵吃掉。",
        "Your king is far away on a8, but a g-pawn has no stalemate trick: force Black's king onto g1 in front of the pawn, walk your king over, and take the pawn.",
        "キングは a8 と遠いが、g ポーンにはステイルメイトの手がない。黒キングを g1 に追い込み、キングを一歩ずつ寄せてポーンを取る。"],
      src: THEORY },
    { id: "qu-f-draw", g: "qu", fen: "8/5P2/8/6K1/8/8/k7/2q5 w - - 0 1", goal: "draw", v: "tb", key: ["Kf6", "Kg6"],
      n: ["f 兵对后：王贴着兵", "f-pawn v queen: stay by the pawn", "f ポーン対クイーン：ポーンのそばに"],
      tip: ["对方的王离得远，象前兵（c、f 兵）就有逼和的招。只有 Kf6 或 Kg6 守得住：王贴着兵，被将军就往 h8 角上躲 —— 后吃 f7 就是逼和。",
        "With the enemy king far away, a bishop's pawn (c or f) has a stalemate trick. Only Kf6 or Kg6 holds: stay next to the pawn and, when checked, hide in the h8 corner — Qxf7 is then stalemate.",
        "相手キングが遠ければ、ビショップポーン（c・f）にはステイルメイトの手がある。守れるのは Kf6 か Kg6 だけ：ポーンのそばにいて、チェックされたら h8 の隅へ。Qxf7 はステイルメイトになる。"],
      src: FLIP(THEORY) },
    { id: "qu-h-draw", g: "qu", fen: "8/6KP/8/8/8/8/k5q1/8 w - - 0 1", goal: "draw", v: "tb", key: ["Kf7", "Kf8", "Kh8"],
      n: ["h 兵对后", "h-pawn v queen", "h ポーン対クイーン"],
      tip: ["边兵最好守：王钻进 h8 角，后怎么将军也赢不了，一不小心就是逼和。只有 Kf7、Kf8、Kh8 守得住：王不能离开兵。",
        "A rook's pawn is the easiest to hold: with your king in the h8 corner the queen cannot win, and one slip is stalemate. Only Kf7, Kf8 or Kh8 holds: the king must not leave the pawn.",
        "ルークポーンが一番守りやすい：キングが h8 の隅にいればクイーンは勝てず、うっかりするとステイルメイト。守れるのは Kf7・Kf8・Kh8 だけ。キングはポーンから離れない。"],
      src: FLIP(THEORY) },
    { id: "qu-hpawn", g: "qu", fen: "8/1Q6/8/3K4/8/8/6kp/8 w - - 0 1", goal: "win", v: "tb", key: ["Kd4+", "Ke5+"],
      n: ["后对 h 兵：闪将", "Queen v h-pawn: the discovered check", "クイーン対 h ポーン：開き王手"],
      tip: ["你的王挡在后的大斜线上。只有 Kd4+ 或 Ke5+ 能赢：王让开斜线、闪出将军，同时走近一步。边兵的逼和招只在你的王离得远时才管用。",
        "Your king stands on the queen's long diagonal. Only Kd4+ or Ke5+ wins: step off it with a discovered check, gaining a step. A rook's pawn only draws when your king is far away.",
        "キングがクイーンの長い対角線をふさいでいる。勝つのは Kd4+ か Ke5+ だけ：対角線からどいて開き王手をかけつつ一歩近づく。ルークポーンが引き分けになるのはキングが遠いときだけ。"],
      src: ONE },
    { id: "qu-race", g: "qu", fen: "K7/8/8/2P3p1/8/5k2/8/8 w - - 0 1", goal: "win", v: "tb", key: ["c6"],
      n: ["先变后，再对兵", "Queen first, then the pawn", "先に昇格、それからポーン"],
      tip: ["只有 c6：你先变后，黑兵这时才到 g2。剩下的是后对七线 g 兵 —— 没有逼和的招，用将军把黑王逼到兵前，你的王再走过来。",
        "Only c6: you queen first, when Black's pawn has only reached g2. What is left is queen against a g-pawn on the seventh — no stalemate trick there: check the king in front of its pawn and bring yours over.",
        "正解は c6 だけ：先に昇格し、黒ポーンはまだ g2。残るのはクイーン対 7 段目の g ポーン。ステイルメイトの手はないので、チェックで黒キングをポーンの前に追い込み、キングを寄せる。"],
      src: ONE },

    // —— 理论和棋 ——
    { id: "dr-philidor", g: "dr", fen: "r7/8/8/4k3/4p3/1R6/8/4K3 w - - 0 1", goal: "draw", v: "tb",
      n: ["菲利多尔防守", "The Philidor defence", "フィリドールの守り"],
      tip: ["车守住你的第 3 横线，不让黑王过来；黑兵一推到第 3 横线，车立刻回到底线，从后面不停将军。",
        "Keep your rook on your third rank so Black's king cannot come forward; the moment the pawn reaches that rank, drop the rook to the back and check from behind.",
        "ルークを自陣 3 段目に置いて黒キングを入れない。ポーンがその段まで来たら、すぐルークを最下段へ下げて後ろからチェックを続ける。"],
      src: ["菲利多尔（1777）", "Philidor (1777)", "フィリドール（1777 年）"] },
    { id: "dr-reti", g: "dr", fen: "7K/8/k1P5/7p/8/8/8/8 w - - 0 1", goal: "draw", v: "tb",
      n: ["列蒂的名题", "Réti's study", "レティのスタディ"],
      tip: ["王看上去追不上 h 兵，但 Kg7 斜着走，同时向 h 兵和自己的 c 兵靠拢 —— 两个目标一起追，总能赶上一个。",
        "The king looks too slow for the h-pawn, but Kg7 walks the diagonal towards both the h-pawn and your own c-pawn — chasing two goals at once, it reaches one.",
        "キングは h ポーンに追いつけないように見えるが、Kg7 から斜めに進めば h ポーンと自分の c ポーンの両方に近づける。二つを同時に追えば、どちらかには間に合う。"],
      src: ["列蒂 1921 年排局", "Réti, 1921", "レティ、1921 年"] },
    { id: "dr-opposition", g: "dr", fen: "8/8/8/3pk3/8/5K2/8/8 w - - 0 1", goal: "draw", v: "tb", key: ["Ke3"],
      n: ["对王守和", "Hold with the opposition", "オポジションで守る"],
      tip: ["只有 Ke3 能守和：和黑王正面对王。之后它往哪边走，你就跟着对到哪边；兵过来时王站在它前面。",
        "Only Ke3 holds: take the opposition. Wherever Black's king goes, oppose it again, and keep your king in front of the pawn.",
        "引き分けにできるのは Ke3 だけ。黒キングと正面で向かい合う。相手がどちらへ行っても向かい合い続け、ポーンの前にキングを置く。"],
      src: ONE },
    { id: "dr-corner", g: "dr", fen: "8/8/8/8/p7/1k6/8/3K4 w - - 0 1", goal: "draw", v: "tb", key: ["Kc1"],
      n: ["边兵：钻进角落", "Rook pawn: into the corner", "ルークポーン：隅に入る"],
      tip: ["只有 Kc1 能守和：王往 a1、b1 那个角落走。只要王进了角，边兵就赢不了。",
        "Only Kc1 holds: head for the a1/b1 corner. Once your king is in it, a rook pawn cannot win.",
        "引き分けにできるのは Kc1 だけ。a1・b1 の隅へ向かう。キングが隅に入れば、ルークポーンでは勝てない。"],
      src: ONE },
    { id: "dr-wrongbishop", g: "dr", fen: "4kb2/8/8/8/7p/8/8/7K w - - 0 1", goal: "draw", v: "tb",
      n: ["错色象", "The wrong bishop", "違う色のビショップ"],
      tip: ["黑方的象走黑格，而升变格 h1 是白格。你的王守在 h1、g1、h2 这个角里不出来，他们多一个象也赢不了。",
        "Black's bishop is dark-squared and the queening square h1 is light. Keep your king in the h1 corner and the extra bishop cannot win.",
        "黒のビショップは黒マス、昇格マス h1 は白マス。キングを h1 の隅から出さなければ、ビショップが多くても勝てない。"],
      src: FLIP(THEORY) },
    { id: "dr-rvb", g: "dr", fen: "8/8/8/8/3k2r1/6B1/8/6K1 w - - 0 1", goal: "draw", v: "tb", key: ["Kf2", "Kg2", "Kh2"],
      n: ["象对车：对的角落", "Bishop v rook: the right corner", "ビショップ対ルーク：正しい隅"],
      tip: ["车在捉象：王先走到象旁边保护它（Kf2、Kg2、Kh2 都行）。之后守在和象不同色的角落附近（h1 是白格，你的象走黑格），车就找不到将死。",
        "The rook attacks your bishop: first bring the king next to it (Kf2, Kg2 or Kh2 all hold). Then stay near the corner opposite in colour to your bishop (h1 is light, your bishop dark) and the rook finds no mate.",
        "ルークがビショップを狙っている。まずキングをそばに寄せて守る（Kf2・Kg2・Kh2 のどれでもよい）。その後はビショップと違う色の隅（h1 は白マス、ビショップは黒マス）の近くにいれば、ルークはメイトできない。"],
      src: ONE },
    { id: "dr-rvn", g: "dr", fen: "8/8/8/4k3/8/8/1r6/5N1K w - - 0 1", goal: "draw", v: "tb", key: ["Kg1", "Nh2"],
      n: ["马对车：马不离王", "Knight v rook: stay together", "ナイト対ルーク：離れない"],
      tip: ["马要紧贴着王（只有 Kg1 或 Nh2 守得住）。马一离开王，车就会把它捉住或牵制。",
        "Keep knight and king together (only Kg1 or Nh2 holds). A knight that leaves its king gets caught or pinned.",
        "ナイトはキングのそばに（守れるのは Kg1 か Nh2 だけ）。キングから離れたナイトはルークに捕まるかピンされる。"],
      src: THEORY },
    { id: "dr-qc", g: "dr", fen: "6q1/2P5/3K4/8/8/3k4/8/8 w - - 0 1", goal: "draw", v: "tb", key: ["Kd7"],
      n: ["c 兵对后", "c-pawn v queen", "c ポーン対クイーン"],
      tip: ["只有 Kd7 能守和：王护住升变格。c 兵有逼和的招：王躲进 a8 角落时，对方吃兵就是逼和。",
        "Only Kd7 holds: the king guards the queening square. The c-pawn has a stalemate resource — with your king in the a8 corner, taking the pawn stalemates.",
        "引き分けにできるのは Kd7 だけ。キングで昇格マスを守る。c ポーンにはステイルメイトの手がある：キングが a8 の隅にいればポーンを取るとステイルメイト。"],
      src: ONE },
    { id: "dr-qa", g: "dr", fen: "8/P7/1K6/8/q7/2k5/8/8 w - - 0 1", goal: "draw", v: "tb", key: ["Kb7"],
      n: ["边兵对后", "Rook pawn v queen", "ルークポーン対クイーン"],
      tip: ["只有 Kb7 能守和：王守在 a8、b7 这一角。后想吃掉兵，往往就先把你逼和了。",
        "Only Kb7 holds: stay in the a8/b7 corner. To take the pawn the queen usually has to stalemate you first.",
        "引き分けにできるのは Kb7 だけ。a8・b7 の隅にいれば、クイーンはポーンを取る前にステイルメイトにしてしまう。"],
      src: ONE },
    { id: "dr-kpvr", g: "dr", fen: "8/8/8/3K4/4P3/8/4k3/7r w - - 0 1", goal: "draw", v: "tb", key: ["e5"],
      n: ["兵加王对车", "King and pawn v rook", "キングとポーン対ルーク"],
      tip: ["只有马上推 e5 能守和：王护着兵往前走，黑王离得远，最后黑车只能拿自己换掉你的兵。",
        "Only e5 at once holds: king and pawn go forward together, Black's king is far, and in the end the rook has to give itself for the pawn.",
        "引き分けにできるのはすぐ e5 だけ。キングとポーンで前進し、黒キングは遠く、最後はルークを捨ててポーンを取るしかない。"],
      src: ONE },
    { id: "dr-apawn", g: "dr", fen: "R7/6k1/8/8/8/8/p5K1/r7 w - - 0 1", goal: "draw", v: "tb",
      n: ["车在兵前：王守 g2、h2", "Rook in front: king on g2/h2", "兵の前のルーク：キングは g2・h2"],
      tip: ["对方的车堵在自己兵的前面。你的车留在 a 线从后面盯着兵，王只在 g2、h2 两格之间来回走：王离开这两格，就可能吃到串击。",
        "Black's rook is stuck in front of its own pawn. Keep your rook behind the pawn on the a-file and shuffle the king between g2 and h2 — anywhere else invites a skewer.",
        "黒ルークは自分のポーンの前に詰まっている。ルークは a ファイルで後ろから見張り、キングは g2・h2 の間だけを往復する。他のマスではスキュアを食う。"],
      src: FLIP(THEORY) },
    { id: "dr-vancura", g: "dr", fen: "8/6k1/8/8/8/p4R2/6K1/r7 w - - 0 1", goal: "draw", v: "tb",
      n: ["万丘拉防守", "The Vančura defence", "ヴァンチュラの守り"],
      tip: ["车从侧面（f3）盯住 a 兵，王守在 g2、h2 一带。对方的王过来护兵时，从侧面将军把它赶开。",
        "The rook watches the a-pawn from the side (f3) while your king stays near g2/h2. When Black's king comes to help the pawn, check it away from the side.",
        "ルークは横（f3）から a ポーンを見張り、キングは g2・h2 付近に。黒キングがポーンを助けに来たら、横からチェックして追い払う。"],
      src: FLIP(["万丘拉（1924）", "Vančura (1924)", "ヴァンチュラ（1924 年）"]) },
  ];

  export const CHESS_ENDGAMES = { GROUPS, ITEMS };
