/**
 * Curated ECO opening book — mainstream openings only, matched by SAN prefix.
 * Entry: [eco, id, moves, idea?] where moves is space-joined canonical chess.js
 * SAN and `id` indexes CHESS_OPENING_NAMES below (and the -en / -ja tables)
 * (scripts/test-chess.mjs verifies every line is legal and canonical).
 * The deepest matching prefix wins, so variation entries shadow their parents.
 * @module openings
 */
  export const CHESS_OPENINGS = [
    // A — flank openings
    ["A00", "polish-sokolsky-opening", "b4"],
    ["A00", "grobs-attack", "g4"],
    ["A00", "hungarian-opening", "g3"],
    ["A00", "van-t-kruijs-opening", "e3"],
    ["A00", "dunst-opening", "Nc3"],
    ["A01", "larsens-opening", "b3"],
    ["A02", "birds-opening", "f4"],
    ["A03", "birds-opening", "f4 d5"],
    ["A04", "reti-opening", "Nf3"],
    ["A05", "reti-opening", "Nf3 Nf6"],
    ["A06", "reti-opening", "Nf3 d5"],
    ["A07", "kings-indian-attack", "Nf3 d5 g3"],
    ["A09", "reti-opening", "Nf3 d5 c4"],
    ["A10", "english-opening", "c4"],
    ["A15", "english-opening", "c4 Nf6"],
    ["A20", "english-opening", "c4 e5"],
    ["A30", "english-opening-symmetrical-variation", "c4 c5"],
    ["A40", "queens-pawn-opening", "d4"],
    ["A43", "old-benoni-defense", "d4 c5"],
    ["A45", "indian-defense", "d4 Nf6"],
    ["A45", "trompowsky-attack", "d4 Nf6 Bg5"],
    ["A46", "indian-defense", "d4 Nf6 Nf3"],
    ["A48", "london-system", "d4 Nf6 Nf3 g6 Bf4"],
    ["A51", "budapest-gambit", "d4 Nf6 c4 e5"],
    ["A53", "old-indian-defense", "d4 Nf6 c4 d6"],
    ["A56", "benoni-defense", "d4 Nf6 c4 c5"],
    ["A57", "benko-volga-gambit", "d4 Nf6 c4 c5 d5 b5",
      "黑方弃 b 兵抢开 a/b 线,用两个车和象在后翼制造持久压力 —— 用一个兵换来长期主动权。"],
    ["A60", "modern-benoni", "d4 Nf6 c4 c5 d5 e6",
      "黑方接受空间劣势,换取 e6 破坏白方兵链、并计划 ...b5 在后翼反击。"],
    ["A80", "dutch-defense", "d4 f5"],
    // —— 1.15: flank main lines, deep enough to drill ——
    ["A08", "kings-indian-attack-main-line", "Nf3 d5 g3 Nf6 Bg2 e6 O-O Be7 d3 O-O Nbd2 c5 e4 Nc6 Re1 b5 e5 Nd7",
      "把国王印度防御反过来白方下:同一套形状可以对付黑方几乎所有回应,推 e4-e5 之后直接冲王翼。"],
    ["A13", "reti-opening-main-line", "Nf3 d5 c4 e6 g3 Nf6 Bg2 Be7 O-O O-O b3 c5 Bb2 Nc6 e3 b6 Nc3 Bb7",
      "白方先不推中心兵,而是用两个象从远处瞄准中心,等黑方定型了再决定推 d4 还是 e4。"],
    ["A29", "english-opening-reversed-sicilian", "c4 e5 Nc3 Nf6 Nf3 Nc6 g3 d5 cxd5 Nxd5 Bg2 Nb6 O-O Be7 a3 O-O b4 Be6",
      "把西西里的黑方局面反过来白方下,还多一步先手。理解英国式最快的路,就是先理解西西里。"],
    ["A34", "english-symmetrical-main-line", "c4 c5 Nf3 Nf6 Nc3 d5 cxd5 Nxd5 g3 Nc6 Bg2 Nc7 O-O e5 d3 Be7 Nd2 O-O",
      "两边阵型对称,谁先打破对称谁就要承担后果。这类局面考的不是记忆,是判断什么时候该出手。"],
    ["A45", "trompowsky-attack-main-line", "d4 Nf6 Bg5 Ne4 Bf4 d5 e3 c5 Bd3 Nc6 Nf3 Qb6 c4 Qxb2 O-O e6 cxd5 exd5",
      "白方第二回合就出象,把黑方拖出所有印度防御的准备。第七回合 c4 干脆把 b2 送出去:黑后跑去吃兵的这几步,白方全用来出子。"],
    ["A48", "london-system-vs-kings-indian", "d4 Nf6 Nf3 g6 Bf4 Bg7 e3 O-O Be2 d6 h3 Nbd7 O-O Re8 c4 e5 Bh2 exd4",
      "同一套伦敦形状对付王翼象型:Bf4 提前占住 e5 这个格子,h3 给象留 h2 的退路。"],
    ["A58", "benko-gambit-accepted", "d4 Nf6 c4 c5 d5 b5 cxb5 a6 bxa6 Bxa6 Nc3 d6 e4 Bxf1 Kxf1 g6 g3 Bg7",
      "黑方送掉一个兵,把 a 线和 b 线全部打开,两个车和象一直压着白方后翼下整盘棋。兵没了,压力永远在。"],
    ["A70", "modern-benoni-main-line", "d4 Nf6 c4 c5 d5 e6 Nc3 exd5 cxd5 d6 e4 g6 Nf3 Bg7 Be2 O-O O-O Re8",
      "黑方接受空间上的劣势,换来 e 线的车、g7 的象和后翼 ...b5 的多数兵。要主动,不要舒服。"],
    ["A88", "dutch-defence-leningrad", "d4 f5 g3 Nf6 Bg2 g6 Nf3 Bg7 O-O O-O c4 d6 Nc3 c6 d5 e5 dxe6 Bxe6",
      "黑方把国王印度的象型接到荷兰的 f5 兵上:g7 象顺长斜线,f 线开着,王翼的攻势有两条路。"],
    ["A97", "dutch-defence-classical", "d4 f5 g3 Nf6 Bg2 e6 Nf3 Be7 O-O O-O c4 d6 Nc3 Qe8 Re1 Qh5 e4 fxe4",
      "黑方第一回合就把王翼的兵推出去争 e4,代价是 e8-h5 斜线上永远的一点松。要攻王的人下这个。"],
    // B — semi-open games
    ["B00", "kings-pawn-opening", "e4"],
    ["B00", "nimzowitsch-defense", "e4 Nc6"],
    ["B01", "scandinavian-defense", "e4 d5"],
    ["B02", "alekhines-defense", "e4 Nf6"],
    ["B04", "alekhines-defense-modern-variation", "e4 Nf6 e5 Nd5 d4 d6 Nf3",
      "黑方故意让马被兵追赶,引诱白方兵过度前进,再回头攻击这些过伸的兵。"],
    ["B06", "modern-defense", "e4 g6"],
    ["B07", "pirc-defense", "e4 d6"],
    ["B07", "pirc-defense", "e4 d6 d4 Nf6 Nc3"],
    ["B10", "caro-kann-defense", "e4 c6"],
    ["B12", "caro-kann-defense-advance-variation", "e4 c6 d4 d5 e5"],
    ["B13", "caro-kann-defense-exchange-variation", "e4 c6 d4 d5 exd5 cxd5",
      "交换后结构对称、局面清晰:白方靠小优势和快速出子,黑方求稳求简。"],
    ["B13", "caro-kann-exchange-main", "e4 c6 d4 d5 exd5 cxd5 Bd3 Nc6 c3 Nf6 Bf4 Bg4 Qb3 Qc8 Nd2 e6",
      "交换变例的全部要点在 b7:白方用 Bd3+Qb3 逼黑方后守在 c8,再抢先把子出完。结构对称,先手就是全部资本。"],
    ["B15", "caro-kann-defense", "e4 c6 d4 d5 Nc3"],
    ["B18", "caro-kann-defense-classical-variation", "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5",
      "黑方先解决「坏象」问题:把 c8 象抢在 e6 兵之前调出来,再稳步补齐阵型。"],
    ["B20", "sicilian-defense", "e4 c5"],
    ["B21", "smith-morra-gambit", "e4 c5 d4 cxd4 c3"],
    ["B22", "sicilian-defense-alapin-variation", "e4 c5 c3"],
    ["B23", "closed-sicilian", "e4 c5 Nc3"],
    ["B27", "sicilian-defense", "e4 c5 Nf3"],
    ["B30", "sicilian-defense", "e4 c5 Nf3 Nc6"],
    ["B33", "sicilian-defense-sveshnikov-variation", "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5",
      "黑方用 ...e5 抢占中心并把白马赶走,代价是 d5 格永久变弱 —— 尖锐的空间换弱格交易。"],
    ["B34", "sicilian-defense-accelerated-dragon", "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6",
      "黑方象在 g7 长斜线遥控中心,配合 ...d5 突破,比标准龙式更快。"],
    ["B40", "sicilian-defense", "e4 c5 Nf3 e6"],
    ["B41", "sicilian-defense-kan-variation", "e4 c5 Nf3 e6 d4 cxd4 Nxd4 a6",
      "...a6 先手防住 Nb5,为 ...b5 侧翼扩张与 ...Bb7 长斜线做准备。"],
    ["B50", "sicilian-defense", "e4 c5 Nf3 d6"],
    ["B70", "sicilian-defense-dragon-variation", "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6",
      "黑象走 g7 形成「龙」,双方各攻一翼:白方冲 h 兵攻王,黑方沿 c 线反扑。"],
    ["B80", "sicilian-defense-scheveningen-variation", "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6",
      "黑方筑起小而结实的 d6+e6 兵阵,把子力藏在后面,伺机 ...d5 或 ...b5 反击。"],
    ["B90", "sicilian-defense-najdorf-variation", "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6",
      "...a6 是纳伊道夫的灵魂:防住 b5 格,准备 ...e5 抢中心与 ...b5 后翼扩张。"],
    // —— 1.15: semi-open main lines, deep enough to drill ——
    ["B01", "scandinavian-defence-main-line", "e4 d5 exd5 Qxd5 Nc3 Qa5 d4 Nf6 Nf3 c6 Bc4 Bf5 Bd2 e6 Qe2 Bb4",
      "黑方第一回合就挑战中心,代价是后要挨一步 Nc3。好处是局面简单、路数少,黑方几乎不会被开局准备打死。"],
    ["B02", "alekhines-defence-four-pawns-attack", "e4 Nf6 e5 Nd5 d4 d6 c4 Nb6 f4 dxe5 fxe5 Nc6 Be3 Bf5 Nc3 e6 Nf3 Be7",
      "白方把四个中心兵全部推上去,要么碾过黑方,要么这条兵链自己塌掉。阿廖欣防御想要的就是这个。"],
    ["B05", "alekhines-defence-modern-main-line", "e4 Nf6 e5 Nd5 d4 d6 Nf3 Bg4 Be2 e6 O-O Be7 c4 Nb6 Nc3 O-O",
      "黑方故意让马被追着跑,引白方兵越推越前,再回头去啃这条过度伸展的兵链。是「诱敌深入」在开局里的样子。"],
    ["B06", "modern-defence-austrian-attack", "e4 g6 d4 Bg7 Nc3 d6 f4 a6 Nf3 b5 Bd3 Nd7 O-O Bb7 Qe1 e6",
      "比皮尔茨更晚出马:黑方先把象放上长斜线和后翼铺开,把出马的时机留到看清白方阵型之后。"],
    ["B08", "pirc-defence-classical", "e4 d6 d4 Nf6 Nc3 g6 Nf3 Bg7 Be2 O-O O-O c6 a4 Nbd7 h3 e5",
      "黑方不争中心,先让白方占满,再用 ...c6 ...e5 从侧面顶回去。需要耐心,也需要对被挤压的局面不害怕。"],
    ["B12", "caro-kann-advance", "e4 c6 d4 d5 e5 Bf5 Nf3 e6 Be2 Nd7 O-O Ne7 Nbd2 Ng6 Nb3 Be7 a4 O-O",
      "白方关住中心抢空间。黑方的关键是先把白格象放到 f5——它一旦被 e6 关在里面,这盘棋就没法下了。象出去之后 ...Ne7-g6 回头来啃 e5。"],
    ["B14", "caro-kann-panov-attack", "e4 c6 d4 d5 exd5 cxd5 c4 Nf6 Nc3 e6 Nf3 Be7 cxd5 Nxd5 Bd3 Nc6",
      "白方把卡罗-康变成孤兵局面:d4 是孤兵,换来的是子力活跃和 e5、c5 两个前哨。孤兵怎么下,这里是标准教材。"],
    ["B18", "caro-kann-classical-short-castles", "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 Nf3 Nd7 Bd3 Bxd3 Qxd3 e6 O-O Ngf6",
      "白方不推 h4,选择安稳出子短易位。局面比 h4-h5 那支平静得多,黑方也更容易走。"],
    ["B19", "caro-kann-classical", "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5 Ng3 Bg6 h4 h6 Nf3 Nd7 h5 Bh7",
      "卡罗-康的要点是:白格象在被 e6 关住之前先出去。代价是白方 h4-h5 抢到空间,黑方的象要在 h7 站一会儿。"],
    ["B21", "smith-morra-gambit-main", "e4 c5 d4 cxd4 c3 dxc3 Nxc3 Nc6 Nf3 d6 Bc4 e6 O-O Nf6 Qe2 Be7 Rd1 e5",
      "白方送一个兵,换来 c 线和 d 线的两条开放线,以及比黑方快两步的出子。黑方一旦慢下来就会被冲垮。"],
    ["B22", "sicilian-alapin-2-nf6", "e4 c5 c3 Nf6 e5 Nd5 d4 cxd4 Nf3 Nc6 cxd4 d6 Bc4 Nb6 Bb5 dxe5",
      "白方第二回合就准备 d4 建大中心,避开了西西里全部主线理论。付出的是一步出子的时间。"],
    ["B23", "closed-sicilian-main", "e4 c5 Nc3 Nc6 g3 g6 Bg2 Bg7 d3 d6 f4 e6 Nf3 Nge7 O-O O-O",
      "白方不换中心兵,把西西里下成王翼印度式的对攻:f4-f5 冲王翼,黑方 ...b5 冲后翼。不用背理论。"],
    ["B31", "sicilian-rossolimo-nd4", "e4 c5 Nf3 Nc6 Bb5 g6 O-O Bg7 Re1 Nf6 c3 O-O d4 cxd4 cxd4 d5 e5 Ne4",
      "黑方不让白方换马,直接易位出子。白方推 d4-e5 建中心,局面变成兵链对抗。"],
    ["B33", "sicilian-sveshnikov", "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5 Ndb5 d6 Bg5 a6 Na3 b5 Nd5 Be7 Bxf6 Bxf6",
      "黑方主动在 d5 留一个永久的洞,换来 e5 的空间、两象和 ...b5 的后翼推进。二十年前被认为是自杀,现在是主流。"],
    ["B36", "accelerated-dragon-maroczy-bind", "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6 c4 Nf6 Nc3 d6 Be2 Nxd4 Qxd4 Bg7",
      "白方用 c4+e4 两个兵把 d5 死死锁住,黑方一时推不动 ...d5 和 ...b5。破束缚要靠换子——这一课很多人是在这里学会的。"],
    ["B47", "sicilian-taimanov", "e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6 Nc3 Qc7 Be3 a6 Be2 Nf6 O-O Bb4 Na4 O-O",
      "黑方先不定 d 兵和王象的位置,后早早到 c7 施压 c 线和 e4。灵活是它最大的本钱。"],
    ["B51", "sicilian-rossolimo", "e4 c5 Nf3 Nc6 Bb5 g6 Bxc6 dxc6 d3 Bg7 h3 Nf6 Nc3 O-O Be3 b6 Qd2 e5",
      "白方第三回合就换掉黑马,不进西西里主线的理论海。黑方得两象,白方得干净的兵型和简单的计划。"],
    ["B78", "sicilian-dragon-yugoslav-attack", "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6 Be3 Bg7 f3 O-O Qd2 Nc6 Bc4 Bd7 O-O-O",
      "两边异侧易位,各推各的兵,谁先攻到谁赢。黑方那只 g7 象顺着长斜线一直看到 b2,白方就是冲着它去的。"],
    ["B84", "sicilian-scheveningen", "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6 Be2 Be7 O-O O-O f4 Nc6 Be3 Bd7",
      "d6+e6 的「小中心」很矮但没有弱点,黑方等白方推兵推出破绽再反击。是西西里里最讲究耐心的一支。"],
    ["B90", "sicilian-najdorf", "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3 e5 Nb3 Be6 f3 Be7 Qd2 O-O",
      "...a6 看着像慢棋,其实是为 ...b5 和把白子挡在 b5 外面做的准备。黑方甘愿在 d5 留个洞,换来后翼的全部主动权。"],
    // C — open games & French
    ["C00", "french-defense", "e4 e6"],
    ["C01", "french-defense-exchange-variation", "e4 e6 d4 d5 exd5 exd5",
      "兵型对称、易位方向相同,谁的子力更活跃、谁能先在 e 线施压,谁就占优。"],
    ["C02", "french-defense-advance-variation", "e4 e6 d4 d5 e5"],
    ["C03", "french-defense-tarrasch-variation", "e4 e6 d4 d5 Nd2"],
    ["C10", "french-defense", "e4 e6 d4 d5 Nc3"],
    ["C11", "french-defense-classical-variation", "e4 e6 d4 d5 Nc3 Nf6",
      "黑方直接出马挑战 e4,白方通常 e5 推进封锁,双方围绕 d4/d5 中心兵链角力。"],
    ["C15", "french-defense-winawer-variation", "e4 e6 d4 d5 Nc3 Bb4",
      "黑象钉住 c3 马以直接压迫 e4;白方常用 a3 逼象表态,换来双象与中心兵优势。"],
    ["C20", "kings-pawn-game", "e4 e5"],
    ["C21", "center-game", "e4 e5 d4 exd4"],
    ["C23", "bishops-opening", "e4 e5 Bc4"],
    ["C25", "vienna-game", "e4 e5 Nc3"],
    ["C30", "kings-gambit", "e4 e5 f4"],
    ["C33", "kings-gambit-accepted", "e4 e5 f4 exf4"],
    ["C40", "kings-knight-opening", "e4 e5 Nf3"],
    ["C41", "philidor-defense", "e4 e5 Nf3 d6"],
    ["C42", "russian-petrov-defense", "e4 e5 Nf3 Nf6"],
    ["C44", "scotch-game", "e4 e5 Nf3 Nc6 d4"],
    ["C45", "scotch-game", "e4 e5 Nf3 Nc6 d4 exd4 Nxd4",
      "白方早早打开中心,子力迅速活跃 —— 用结构的对称换取出子速度。"],
    ["C46", "three-knights-game", "e4 e5 Nf3 Nc6 Nc3"],
    ["C47", "four-knights-game", "e4 e5 Nf3 Nc6 Nc3 Nf6",
      "双方对称快速出轻子,是最讲究「开局三原则」的正统开局,适合初学者。"],
    ["C48", "four-knights-game-spanish-variation", "e4 e5 Nf3 Nc6 Nc3 Nf6 Bb5",
      "白方在对称阵型中先加一手 Bb5 施压 c6,试图打破平衡。"],
    ["C50", "italian-game", "e4 e5 Nf3 Nc6 Bc4"],
    ["C50", "italian-game", "e4 e5 Nf3 Nc6 Bc4 Bc5",
      "双方象都瞄准对方最弱的 f 格(f7/f2),典型的「安静意大利」慢速布局。"],
    ["C51", "evans-gambit", "e4 e5 Nf3 Nc6 Bc4 Bc5 b4",
      "白方弃 b 兵抢时间:换来 c3+d4 强大中心与快速出子的猛烈攻势。"],
    ["C53", "italian-game-classical-variation", "e4 e5 Nf3 Nc6 Bc4 Bc5 c3",
      "c3 为 d4 做准备:白方要建起中心兵阵,把象的火力转成实实在在的空间。"],
    ["C55", "two-knights-defense", "e4 e5 Nf3 Nc6 Bc4 Nf6",
      "黑马反击 e4 而不守 e5,把局面引向战术复杂的路线。"],
    ["C57", "two-knights-defense-knight-attack", "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5",
      "白马直扑 f7 —— 最古老的陷阱之一;黑方须用 ...d5 反击而非慌忙救兵。"],
    ["C60", "ruy-lopez-spanish-opening", "e4 e5 Nf3 Nc6 Bb5"],
    ["C65", "ruy-lopez-berlin-defense", "e4 e5 Nf3 Nc6 Bb5 Nf6",
      "黑方不理会 a6,直接出马压 e4;交换后走向少子、结构稳固的残局型局面。"],
    ["C68", "ruy-lopez-exchange-variation", "e4 e5 Nf3 Nc6 Bb5 a6 Bxc6",
      "白方主动换掉好象,换来黑方双兵结构受损,目标是残局取胜。"],
    ["C70", "ruy-lopez", "e4 e5 Nf3 Nc6 Bb5 a6 Ba4",
      "白象退守 a4 保持钉马的压力,黑方获得 ...b5 的反击资源 —— 西班牙的主干路口。"],
    ["C84", "ruy-lopez-closed-variation", "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7",
      "双方完成出子与易位,白方准备 c3+d4 建中心,黑方伺机 ...d5 或后翼扩张。"],
    // —— 1.15: open-game main lines, deep enough to drill ——
    ["C00", "french-defence-kings-indian-attack", "e4 e6 d3 d5 Nd2 Nf6 Ngf3 c5 g3 Nc6 Bg2 Be7 O-O O-O Re1 b5 e5 Nd7",
      "白方不进法兰西的理论森林,改摆王翼印度攻击的形状:e4-e5 关中心,然后所有子力朝王翼走。"],
    ["C01", "french-exchange-symmetrical", "e4 e6 d4 d5 exd5 exd5 Nf3 Nf6 Bd3 Bd6 O-O O-O Re1 Bg4 Nbd2 Nbd7 c3 c6",
      "最对称的法兰西:两边形状一模一样。想赢就得自己先打破平衡,而那一步永远是有代价的。"],
    ["C02", "french-advance", "e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 a3 Nh6 b4 cxd4 cxd4 Nf5 Bb2 Bd7",
      "中心一锁死,棋就变成两侧各打各的:白方在王翼,黑方在 d4 和 c 线。黑方的白格象是这盘棋里最难安置的一个子。"],
    ["C07", "french-tarrasch-open-variation", "e4 e6 d4 d5 Nd2 c5 exd5 Qxd5 Ngf3 cxd4 Bc4 Qd6 O-O Nf6 Nb3 Nc6 Nbxd4 Nxd4",
      "白方用 Nd2 避开 ...Bb4 的钉子,代价是马挡住了自己的象。局面容易开放,常常变成孤兵结构。"],
    ["C11", "french-classical", "e4 e6 d4 d5 Nc3 Nf6 e5 Nfd7 f4 c5 Nf3 Nc6 Be3 cxd4 Nxd4 Bc5 Qd2 O-O",
      "白方兵推到 e5 抢空间,黑方马退回 d7 再从 c5 打兵链根部。典型的兵链对攻:一边冲王翼,一边啃底部。"],
    ["C19", "french-winawer", "e4 e6 d4 d5 Nc3 Bb4 e5 c5 a3 Bxc3+ bxc3 Ne7 Nf3 Nbc6 Be2 Qa5 Bd2 O-O",
      "黑方用象换马,把白方兵型打成 c3 双兵,再全力去啃 d4。白方拿到的是两象和王翼的进攻权。"],
    ["C24", "bishops-opening-berlin-defence", "e4 e5 Bc4 Nf6 d3 c6 Nf3 d5 Bb3 Bd6 Nc3 dxe4 Ng5 O-O Ncxe4 Nxe4 Nxe4 Be7",
      "白方先出象再出马,可以转成意大利、维也纳或者本身的独立路数。是绕开彼得罗夫防御的一条常用小路。"],
    ["C26", "vienna-game-mieses", "e4 e5 Nc3 Nf6 g3 d5 exd5 Nxd5 Bg2 Nxc3 bxc3 Bc5 Nf3 O-O O-O Nc6 d3 Re8",
      "白方不去争 d5,让黑方换掉马之后,用 g2 象和半开的 b 线做长期文章。安静,但每一步都在为中局铺路。"],
    ["C29", "vienna-gambit", "e4 e5 Nc3 Nf6 f4 d5 fxe5 Nxe4 Nf3 Be7 d4 O-O Bd3 f5 exf6 Bxf6",
      "王翼弃兵的稳健版:先出马再推 f4,黑方 ...d5 是唯一正确的反击。"],
    ["C39", "kings-gambit-kieseritzky", "e4 e5 f4 exf4 Nf3 g5 h4 g4 Ne5 Nf6 d4 d6 Nd3 Nxe4 Bxf4 Qe7",
      "浪漫时代的主线:白方第二回合就送掉 f 兵去换中心和 f 线。今天不算最佳,但每个学棋的人都该下过一次。"],
    ["C41", "philidor-defence-classical", "e4 e5 Nf3 d6 d4 Nf6 Nc3 Nbd7 Bc4 Be7 O-O O-O Re1 c6 a4 Qc7",
      "黑方用兵而不是用马来守 e5,格局窄但结实。要小心的是 f7 —— 白方的象和车都盯着它。"],
    ["C42", "petrov-defence", "e4 e5 Nf3 Nf6 Nxe5 d6 Nf3 Nxe4 d4 d5 Bd3 Be7 O-O Nc6 c4 Nb4",
      "黑方不去守 e5,而是对称地吃回来。局面容易变得平衡而干净,是黑方求稳的经典选择。"],
    ["C44", "scotch-gambit", "e4 e5 Nf3 Nc6 d4 exd4 Bc4 Bc5 c3 Nf6 e5 d5 Bb5 Ne4 cxd4 Bb6 Nc3 O-O",
      "白方不吃回 d4,直接出象抢时间。第七回合 e5 赶马、Bb5 钉马,双方都要算清楚——这条线里慢一步就是慢一个子。"],
    ["C45", "scotch-game-classical", "e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5 Be3 Qf6 c3 Nge7 Bc4 Ne5 Be2 Qg6",
      "第三回合就把中心兵换掉,局面立刻开放。白方不追求慢慢挤压,而是要在出子速度上抢一步。"],
    ["C47", "four-knights-scotch", "e4 e5 Nf3 Nc6 Nc3 Nf6 d4 exd4 Nxd4 Bb4 Nxc6 bxc6 Bd3 d5 exd5 cxd5 O-O O-O Bg5 c6",
      "四马阵里最省记忆的白方选择:d4 把中心兑开,黑方得到 d5 通兵形的同时背上孤立倾向的兵。双方都清楚自己在下什么。"],
    ["C49", "four-knights-game-main", "e4 e5 Nf3 Nc6 Nc3 Nf6 Bb5 Bb4 O-O O-O d3 d6 Bg5 Bxc3 bxc3 Qe7",
      "四个马先出来,局面对称而安静。它教的是「出子、易位、再想计划」这个顺序本身。"],
    ["C50", "italian-game-giuoco-pianissimo", "e4 e5 Nf3 Nc6 Bc4 Bc5 d3 Nf6 O-O d6 c3 a6 Bb3 Ba7 Re1 O-O Nbd2 Ne7",
      "「最慢的棋」——白方不急着推 d4,先把每个子摆到最好的格子上。适合不想背理论、想学摆子的人。"],
    ["C52", "evans-gambit-main", "e4 e5 Nf3 Nc6 Bc4 Bc5 b4 Bxb4 c3 Ba5 d4 exd4 O-O Nge7 cxd4 d5",
      "白方用 b 兵换一个抢先手:c3 和 d4 一步到位建成大中心,象也回到了 c4 的斜线上。十九世纪的进攻武器,今天仍然锋利。"],
    ["C54", "italian-game-giuoco-piano", "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O Re1 a6 Nbd2 Ba7",
      "两边都把象放到最长的斜线上,再慢慢准备 d4。现代的下法是 d3 而不是 d4——先摆好,再推。"],
    ["C58", "two-knights-defence", "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Na5 Bb5+ c6 dxc6 bxc6 Be2 h6",
      "黑方弃一兵把白马赶回家,换来领先的出子和 e 线、d 线的两条开放线。是初学者第一次尝到「弃兵抢速度」的地方。"],
    ["C65", "ruy-lopez-berlin-anti-berlin", "e4 e5 Nf3 Nc6 Bb5 Nf6 d3 Bc5 c3 O-O O-O d6 Nbd2 a6 Ba4 Ba7 h3 Ne7",
      "白方用 d3 回避柏林残局,把棋留在中局。近十年最高水平的常见选择——不换后,继续下棋。"],
    ["C67", "ruy-lopez-berlin-endgame", "e4 e5 Nf3 Nc6 Bb5 Nf6 O-O Nxe4 d4 Nd6 Bxc6 dxc6 dxe5 Nf5 Qxd8+ Kxd8",
      "后早早下台,黑方失去易位权却得到两象和极难攻破的兵型。它把西班牙变成一盘残局——这也是它在最高水平被大量使用的原因。"],
    ["C69", "ruy-lopez-exchange-main-line", "e4 e5 Nf3 Nc6 Bb5 a6 Bxc6 dxc6 O-O f6 d4 exd4 Nxd4 c5",
      "白方主动破坏黑方兵型换来残局优势:黑方双兵在 c 线,残局里白方王翼四对三是干净的多数兵。代价是黑方得到两象。"],
    ["C88", "ruy-lopez-closed-main-line", "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3",
      "西班牙的主干。白方 c3 撑起 d4、h3 先防 ...Bg4,把兵推进准备得滴水不漏再动手;黑方 ...b5 ...d6 稳住 e5,双方都不急,棋在中局才开始。"],
    ["C89", "ruy-lopez-marshall-attack", "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 O-O c3 d5",
      "黑方在第八回合弃掉 e 兵,换来 e 线、d5 中心和直指王翼的子力。一百年来白方都没能证明这个兵白吃。"],
    // D — closed games & Grünfeld
    ["D00", "queens-pawn-game", "d4 d5"],
    ["D00", "london-system", "d4 d5 Bf4"],
    ["D01", "richter-veresov-attack", "d4 d5 Nc3 Nf6 Bg5"],
    ["D02", "queens-pawn-game", "d4 d5 Nf3"],
    ["D02", "london-system", "d4 d5 Nf3 Nf6 Bf4"],
    ["D04", "colle-system", "d4 d5 Nf3 Nf6 e3"],
    ["D06", "queens-gambit", "d4 d5 c4"],
    ["D07", "chigorin-defense", "d4 d5 c4 Nc6"],
    ["D08", "albin-countergambit", "d4 d5 c4 e5"],
    ["D10", "slav-defense", "d4 d5 c4 c6"],
    ["D15", "slav-defense", "d4 d5 c4 c6 Nf3 Nf6 Nc3",
      "黑方用 c6 支撑 d5,同时保留 c8 象的出路 —— 比后翼弃兵更灵活的守中心方案。"],
    ["D20", "queens-gambit-accepted", "d4 d5 c4 dxc4"],
    ["D30", "queens-gambit-declined", "d4 d5 c4 e6"],
    ["D35", "queens-gambit-declined-exchange-variation", "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5",
      "交换后形成经典的「少子进攻」结构:白方在后翼用兵推进,黑方在王翼找机会。"],
    ["D37", "queens-gambit-declined", "d4 d5 c4 e6 Nc3 Nf6 Nf3",
      "双方稳步出子不急于交换,白方保持中心张力,黑方等待 ...dxc4 或 ...c5 的时机。"],
    ["D43", "semi-slav-defense", "d4 d5 c4 e6 Nc3 Nf6 Nf3 c6",
      "黑方保留 ...dxc4 抢兵与 ...b5 扩张的双重可能,是理论最深的路线之一。"],
    ["D80", "grunfeld-defense", "d4 Nf6 c4 g6 Nc3 d5",
      "黑方让白方建起大中心,再用 ...c5 和 g7 象从侧面把它拆掉 —— 典型的「超现代」思路。"],
    ["D85", "grunfeld-defense-exchange-variation", "d4 Nf6 c4 g6 Nc3 d5 cxd5 Nxd5",
      "白方获得理想的大中心兵阵,黑方全部筹码押在拆解这个中心上。"],
    // —— 1.15: queen-pawn main lines, deep enough to drill ——
    ["D02", "london-system-main-line", "d4 d5 Nf3 Nf6 Bf4 e6 e3 c5 c3 Nc6 Nbd2 Bd6 Bg3 O-O Bd3 b6 O-O Bb7",
      "白方几乎不看黑方走什么,固定摆出 d4-Nf3-Bf4-e3-c3-Nbd2 这套形状。要背的东西极少,代价是不逼黑方做任何难题。"],
    ["D10", "slav-defence-exchange", "d4 d5 c4 c6 cxd5 cxd5 Nc3 Nf6 Nf3 Nc6 Bf4 Bf5 e3 e6 Bb5 Nd7 O-O Be7",
      "完全对称的兵型,白方只多一步先手。看着像和棋,实际上先手方那一步在这类局面里很难兑现,但也从不消失。"],
    ["D19", "slav-defence-main-line", "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Bb4 O-O O-O Qe2 Bg6",
      "...c6 先给白格象留好 f5 这个出口,再吃 c4。这就是斯拉夫比后翼弃兵舒服的地方——象不会被自己的兵关住。"],
    ["D27", "queens-gambit-accepted-main", "d4 d5 c4 dxc4 Nf3 Nf6 e3 e6 Bxc4 c5 O-O a6 dxc5 Qxd1 Rxd1 Bxc5 b3 Nbd7",
      "黑方不打算守住那个兵,而是用它换出 ...c5 的时间去打中心。开局早早换后,是想直接进一个舒服的残局。"],
    ["D31", "semi-slav-noteboom", "d4 d5 c4 e6 Nc3 c6 Nf3 dxc4 e3 b5 a4 Bb4 Bd2 a5 axb5 Bxc3 Bxc3 cxb5",
      "黑方吃住 c4 并用 ...b5 保住它,得到后翼两个连兵;白方得到中心和两象。两种优势直接对撞。"],
    ["D34", "tarrasch-defence", "d4 d5 c4 e6 Nc3 c5 cxd5 exd5 Nf3 Nc6 g3 Nf6 Bg2 Be7 O-O O-O Bg5 cxd4",
      "黑方主动接受孤兵,换来子力全部畅通和 e4、c4 两个前哨。子力活跃能不能补偿一个结构弱点——这盘棋就在问这个。"],
    ["D36", "qgd-exchange-minority-attack", "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5 Bg5 c6 Qc2 Be7 e3 Nbd7 Bd3 O-O Nge2 Re8",
      "白方换掉 c 兵定型,准备后翼小兵推进(b4-b5)去啃 c6。这个计划有名字,叫「少数派进攻」。"],
    ["D45", "semi-slav-anti-meran", "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7 Qc2 Bd6 Bd3 O-O O-O dxc4 Bxc4 b5 Bd3 Bb7",
      "白方用 Qc2 提前盯住 e4 和 h7,不让黑方舒舒服服地下梅兰。慢一点,但更结实。"],
    ["D47", "semi-slav-meran", "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3 Nbd7 Bd3 dxc4 Bxc4 b5 Bd3 Bb7 O-O a6 e4 c5",
      "黑方吃 c4 再 ...b5 ...c5,在后翼上抢出两个兵的空间;白方用 e4 在中心还击。双方都很快,谁慢一步就输。"],
    ["D59", "queens-gambit-declined-tartakower", "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3 h6 Bh4 b6 cxd5 Nxd5 Bxe7 Qxe7 Nxd5 exd5",
      "黑方用 ...b6 把最难受的那个白格象放到长斜线上,再换掉两对子力松口气。后翼弃兵拒绝的现代标准处理。"],
    ["D85", "grunfeld-defence-modern-exchange", "d4 Nf6 c4 g6 Nc3 d5 cxd5 Nxd5 e4 Nxc3 bxc3 Bg7 Nf3 c5 Rb1 O-O Be2 cxd4 cxd4",
      "白方把车调到 b1 提前防住 ...Qa5,再用 Be2 稳稳出子。是交换变例里现在最主流的一支。"],
    ["D87", "grunfeld-exchange-classical", "d4 Nf6 c4 g6 Nc3 d5 cxd5 Nxd5 e4 Nxc3 bxc3 Bg7 Bc4 c5 Ne2 Nc6 Be3 O-O",
      "黑方让白方建起一个大中心,然后从 g7 象和 ...c5 两个方向去拆它。「先让他建,再拆掉」是格林菲尔德的全部思想。"],
    // E — Indian defences
    ["E00", "indian-defense", "d4 Nf6 c4 e6"],
    ["E01", "catalan-opening", "d4 Nf6 c4 e6 g3 d5 Bg2",
      "白象走 g2 遥控长斜线,把压力压在 d5 上,是稳健又灵活的现代体系。"],
    ["E11", "bogo-indian-defence", "d4 Nf6 c4 e6 Nf3 Bb4+ Bd2 Qe7 g3 Nc6 Bg2 Bxd2+ Nbxd2 d6 O-O O-O e4 e5",
      "用一次将军把白方的象引到 d2,再从容换掉它:黑方少了一对象,换来的是一个白方很难攻破的 e5-d6 堡垒。"],
    ["E12", "queens-indian-defense", "d4 Nf6 c4 e6 Nf3 b6",
      "黑象走 b7 遥控 e4 格,与马配合牢牢控住中心的关键格。"],
    ["E20", "nimzo-indian-defense", "d4 Nf6 c4 e6 Nc3 Bb4",
      "黑象钉住 c3 马来争夺 e4 格 —— 用一个象的活跃换白方的双象优势。"],
    ["E32", "nimzo-indian-defense-classical-variation", "d4 Nf6 c4 e6 Nc3 Bb4 Qc2",
      "白后走 c2 提前防住黑方破坏兵型,保住双象优势。"],
    ["E40", "nimzo-indian-defense-rubinstein-system", "d4 Nf6 c4 e6 Nc3 Bb4 e3",
      "白方以最朴素的方式出子,接受可能的兵型缺陷,换取中心与双象。"],
    ["E60", "kings-indian-defense", "d4 Nf6 c4 g6"],
    ["E70", "kings-indian-defense", "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6",
      "黑方让出中心再用 ...e5 或 ...c5 反击,王翼易位后全力猛攻 —— 极其锋利的体系。"],
    // —— 1.15: Indian-defence main lines, deep enough to drill ——
    ["E06", "catalan-opening-closed", "d4 Nf6 c4 e6 g3 d5 Bg2 Be7 Nf3 O-O O-O dxc4 Qc2 a6 Qxc4 b5 Qc2 Bb7",
      "白方把象放到 g2 的长斜线上,允许黑方吃 c4,然后花几步把兵要回来——要回来的时候,象已经站好了。"],
    ["E15", "queens-indian-defence", "d4 Nf6 c4 e6 Nf3 b6 g3 Ba6 b3 Bb4+ Bd2 Be7 Bg2 c6 Bc3 d5 Ne5 Nfd7",
      "c3 已经被 Nf3 占了,黑方就改用 ...b6 从远处控制 e4。全局都在争 e4 这一个格子。"],
    ["E32", "nimzo-indian-classical", "d4 Nf6 c4 e6 Nc3 Bb4 Qc2 O-O a3 Bxc3+ Qxc3 b6 Bg5 Bb7 f3 h6 Bh4 d5",
      "白方用后去接象,吃回来时兵型不受损——代价是后早早暴露,而且出子慢了两步。"],
    ["E53", "nimzo-indian-rubinstein", "d4 Nf6 c4 e6 Nc3 Bb4 e3 O-O Bd3 d5 Nf3 c5 O-O Nc6 a3 Bxc3 bxc3 dxc4",
      "黑方第三回合就用象钉住 c3 马,准备换掉它、给白方留下 c3 双兵。用象换马来定结构,这是最经典的一例。"],
    ["E60", "kings-indian-fianchetto", "d4 Nf6 c4 g6 g3 Bg7 Bg2 O-O Nf3 d6 O-O Nbd7 Nc3 e5 e4 c6 h3 Qb6",
      "白方也把象放到长斜线上,提前把黑方 g7 象的火力挡住。是对付国王印度最稳的一套。"],
    // —— 1.23: 两个已有家族里缺掉的主流变例 ——
    ["A95", "dutch-defence-stonewall", "d4 f5 g3 Nf6 Bg2 e6 Nf3 d5 O-O Bd6 c4 c6 b3 Qe7",
      "黑方用 d5-e6-f5-c6 砌一堵墙,把 e4 彻底焊死,然后把子力全部调到王翼去。代价是 e5 格和白格象一辈子憋在墙后面 —— 这是一笔算得清清楚楚的买卖。"],
    ["E81", "kings-indian-defence-samisch", "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f3 O-O Be3 e5 d5 Nh5",
      "白方先用 f3 把 e4 顶死,再摆开阵势推 g4-h4 直接冲王翼。国王印度里最不客气的一套:双方各冲一边,谁慢一步谁挨杀。"],
    ["E97", "kings-indian-defence-classical", "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5 O-O Nc6 d5 Ne7 Nd2 a5",
      "中心一锁,两边就分头推兵:白方 c4-c5 冲后翼,黑方 ...f5-f4-g5 冲白方的王。棋盘上少有这么泾渭分明的对攻。"],
  ];

  /**
   * Chinese names, keyed by the same id.
   *
   * Until 1.25 the name *was* the key: openings-en.js and openings-ja.js were
   * both dictionaries from Chinese name to translation. That made a rename a
   * silent breakage — change one Chinese string here and both translations
   * stop matching, so the name falls back to the Chinese original in every
   * language, and nothing fails. An id keyed table cannot do that: a rename is
   * now a rename, and a missing translation is a test failure.
   */
  export const CHESS_OPENING_NAMES = {
    "polish-sokolsky-opening": "波兰开局（索科尔斯基）",
    "grobs-attack": "格罗布开局",
    "hungarian-opening": "匈牙利开局",
    "van-t-kruijs-opening": "范特克鲁伊斯开局",
    "dunst-opening": "邓斯特开局",
    "larsens-opening": "拉尔森开局",
    "birds-opening": "伯德开局",
    "reti-opening": "列蒂开局",
    "kings-indian-attack": "王翼印度攻击",
    "english-opening": "英国式开局",
    "english-opening-symmetrical-variation": "英国式开局·对称变例",
    "queens-pawn-opening": "后兵开局",
    "old-benoni-defense": "老贝诺尼防御",
    "indian-defense": "印度防御",
    "trompowsky-attack": "特龙波夫斯基进攻",
    "london-system": "伦敦体系",
    "budapest-gambit": "布达佩斯弃兵",
    "old-indian-defense": "老印度防御",
    "benoni-defense": "贝诺尼防御",
    "benko-volga-gambit": "沃尔加-贝科弃兵",
    "modern-benoni": "现代贝诺尼",
    "dutch-defense": "荷兰防御",
    "kings-indian-attack-main-line": "王翼印度攻击·主变",
    "reti-opening-main-line": "列蒂开局·主变",
    "english-opening-reversed-sicilian": "英国式开局·反西西里",
    "english-symmetrical-main-line": "英国式开局·对称主变",
    "trompowsky-attack-main-line": "特龙波夫斯基进攻·主变",
    "london-system-vs-kings-indian": "伦敦体系·对国王印度",
    "benko-gambit-accepted": "贝科弃兵·接受",
    "modern-benoni-main-line": "现代贝诺尼·主变",
    "dutch-defence-leningrad": "荷兰防御·列宁格勒变例",
    "dutch-defence-classical": "荷兰防御·古典变例",
    "kings-pawn-opening": "王兵开局",
    "nimzowitsch-defense": "尼姆佐维奇防御",
    "scandinavian-defense": "斯堪的纳维亚防御",
    "alekhines-defense": "阿廖欣防御",
    "alekhines-defense-modern-variation": "阿廖欣防御·现代变例",
    "modern-defense": "现代防御",
    "pirc-defense": "皮尔茨防御",
    "caro-kann-defense": "卡罗-卡恩防御",
    "caro-kann-defense-advance-variation": "卡罗-卡恩防御·前进变例",
    "caro-kann-defense-exchange-variation": "卡罗-卡恩防御·交换变例",
    "caro-kann-defense-classical-variation": "卡罗-卡恩防御·经典变例",
    "sicilian-defense": "西西里防御",
    "smith-morra-gambit": "史密斯-莫拉弃兵",
    "sicilian-defense-alapin-variation": "西西里防御·阿拉平变例",
    "closed-sicilian": "封闭西西里",
    "sicilian-defense-sveshnikov-variation": "西西里防御·斯维什尼科夫变例",
    "sicilian-defense-accelerated-dragon": "西西里防御·加速龙式",
    "sicilian-defense-kan-variation": "西西里防御·卡恩变例",
    "sicilian-defense-dragon-variation": "西西里防御·龙式变例",
    "sicilian-defense-scheveningen-variation": "西西里防御·谢文宁根变例",
    "sicilian-defense-najdorf-variation": "西西里防御·纳伊道夫变例",
    "scandinavian-defence-main-line": "斯堪的纳维亚防御·主变",
    "alekhines-defence-four-pawns-attack": "阿廖欣防御·四兵攻击",
    "alekhines-defence-modern-main-line": "阿廖欣防御·现代主变",
    "modern-defence-austrian-attack": "现代防御·奥地利攻击",
    "pirc-defence-classical": "皮尔茨防御·古典变例",
    "caro-kann-advance": "卡罗-康防御·进攻变例",
    "caro-kann-panov-attack": "卡罗-康防御·帕诺夫进攻",
    "caro-kann-classical-short-castles": "卡罗-康防御·古典·短易位",
    "caro-kann-classical": "卡罗-康防御·古典变例",
    "smith-morra-gambit-main": "西西里防御·史密斯-莫拉弃兵",
    "sicilian-alapin-2-nf6": "西西里防御·阿拉平·2...Nf6",
    "closed-sicilian-main": "西西里防御·封闭变例",
    "sicilian-rossolimo-nd4": "西西里防御·罗索利莫·保象变例",
    "sicilian-sveshnikov": "西西里防御·斯维什尼科夫",
    "accelerated-dragon-maroczy-bind": "西西里防御·加速龙·马洛奇束缚",
    "sicilian-taimanov": "西西里防御·泰马诺夫",
    "sicilian-rossolimo": "西西里防御·罗索利莫",
    "sicilian-dragon-yugoslav-attack": "西西里防御·龙式·南斯拉夫攻击",
    "sicilian-scheveningen": "西西里防御·舍维宁根",
    "sicilian-najdorf": "西西里防御·纳伊道夫",
    "french-defense": "法兰西防御",
    "french-defense-exchange-variation": "法兰西防御·交换变例",
    "french-defense-advance-variation": "法兰西防御·前进变例",
    "french-defense-tarrasch-variation": "法兰西防御·塔拉什变例",
    "french-defense-classical-variation": "法兰西防御·经典变例",
    "french-defense-winawer-variation": "法兰西防御·维纳韦尔变例",
    "kings-pawn-game": "王兵对局",
    "center-game": "中心对局",
    "bishops-opening": "主教开局",
    "vienna-game": "维也纳开局",
    "kings-gambit": "王翼弃兵",
    "kings-gambit-accepted": "王翼弃兵·接受",
    "kings-knight-opening": "王马开局",
    "philidor-defense": "菲利多尔防御",
    "russian-petrov-defense": "俄罗斯防御（彼得罗夫）",
    "scotch-game": "苏格兰开局",
    "three-knights-game": "三马开局",
    "four-knights-game": "四马开局",
    "four-knights-game-spanish-variation": "四马开局·西班牙变例",
    "italian-game": "意大利开局",
    "evans-gambit": "埃文斯弃兵",
    "italian-game-classical-variation": "意大利开局·经典变例",
    "two-knights-defense": "双马防御",
    "two-knights-defense-knight-attack": "双马防御·骑士进攻",
    "ruy-lopez-spanish-opening": "西班牙开局（鲁伊·洛佩斯）",
    "ruy-lopez-berlin-defense": "西班牙开局·柏林防御",
    "ruy-lopez-exchange-variation": "西班牙开局·交换变例",
    "ruy-lopez": "西班牙开局",
    "ruy-lopez-closed-variation": "西班牙开局·封闭变例",
    "french-defence-kings-indian-attack": "法兰西防御·王翼印度式",
    "french-exchange-symmetrical": "法兰西防御·交换·对称变例",
    "french-advance": "法兰西防御·进攻变例",
    "french-tarrasch-open-variation": "法兰西防御·塔拉什·开放变例",
    "french-classical": "法兰西防御·古典变例",
    "french-winawer": "法兰西防御·温纳瓦尔",
    "bishops-opening-berlin-defence": "主教开局·柏林防御",
    "vienna-gambit": "维也纳开局·弃兵变例",
    "kings-gambit-kieseritzky": "王翼弃兵·基泽利茨基",
    "philidor-defence-classical": "菲利多尔防御·古典变例",
    "petrov-defence": "彼得罗夫防御",
    "scotch-gambit": "苏格兰弃兵",
    "scotch-game-classical": "苏格兰开局·古典变例",
    "four-knights-game-main": "四马防御",
    "four-knights-scotch": "四马防御·苏格兰式",
    "vienna-game-mieses": "维也纳开局·米泽斯变例",
    "caro-kann-exchange-main": "卡罗-康防御·交换主线",
    "bogo-indian-defence": "博戈印度防御",
    "italian-game-giuoco-pianissimo": "意大利开局·极慢变例",
    "evans-gambit-main": "意大利开局·埃文斯弃兵",
    "italian-game-giuoco-piano": "意大利开局·朱奥科·皮亚诺",
    "two-knights-defence": "意大利开局·两马防御",
    "ruy-lopez-berlin-anti-berlin": "西班牙开局·柏林·反柏林",
    "ruy-lopez-berlin-endgame": "西班牙开局·柏林残局",
    "ruy-lopez-exchange-main-line": "西班牙开局·交换主变",
    "ruy-lopez-closed-main-line": "西班牙开局·封闭主变",
    "ruy-lopez-marshall-attack": "西班牙开局·马歇尔攻击",
    "queens-pawn-game": "后兵对局",
    "richter-veresov-attack": "里希特-维列索夫进攻",
    "colle-system": "科列体系",
    "queens-gambit": "后翼弃兵",
    "chigorin-defense": "奇戈林防御",
    "albin-countergambit": "阿尔宾反弃兵",
    "slav-defense": "斯拉夫防御",
    "queens-gambit-accepted": "后翼弃兵·接受",
    "queens-gambit-declined": "后翼弃兵·拒绝",
    "queens-gambit-declined-exchange-variation": "后翼弃兵·交换变例",
    "semi-slav-defense": "半斯拉夫防御",
    "grunfeld-defense": "格林菲尔德防御",
    "grunfeld-defense-exchange-variation": "格林菲尔德防御·交换变例",
    "london-system-main-line": "伦敦体系·主变",
    "slav-defence-exchange": "斯拉夫防御·交换变例",
    "slav-defence-main-line": "斯拉夫防御·主变",
    "queens-gambit-accepted-main": "后翼弃兵接受",
    "semi-slav-noteboom": "半斯拉夫防御·诺特博姆",
    "tarrasch-defence": "塔拉什防御",
    "qgd-exchange-minority-attack": "后翼弃兵·交换·少数派进攻",
    "semi-slav-anti-meran": "半斯拉夫防御·反梅兰",
    "semi-slav-meran": "半斯拉夫防御·梅兰变例",
    "queens-gambit-declined-tartakower": "后翼弃兵·塔尔塔科维尔",
    "grunfeld-defence-modern-exchange": "格林菲尔德防御·现代交换",
    "grunfeld-exchange-classical": "格林菲尔德防御·交换·古典",
    "catalan-opening": "卡塔兰开局",
    "queens-indian-defense": "新印度防御",
    "nimzo-indian-defense": "尼姆佐-印度防御",
    "nimzo-indian-defense-classical-variation": "尼姆佐-印度防御·经典变例",
    "nimzo-indian-defense-rubinstein-system": "尼姆佐-印度防御·鲁宾斯坦体系",
    "kings-indian-defense": "王翼印度防御",
    "catalan-opening-closed": "加泰罗尼亚开局·封闭变例",
    "queens-indian-defence": "后翼印度防御",
    "nimzo-indian-classical": "尼姆佐-印度防御·古典变例",
    "nimzo-indian-rubinstein": "尼姆佐-印度防御·鲁宾斯坦",
    "kings-indian-fianchetto": "国王印度防御·菲安凯托变例",
    "dutch-defence-stonewall": "荷兰防御·石墙变例",
    "kings-indian-defence-samisch": "国王印度防御·萨米什变例",
    "kings-indian-defence-classical": "国王印度防御·古典变例",
  };
