/**
 * English opening names, keyed by the Chinese name in openings.js.
 *
 * openings.js stays the single source of truth for the ECO code and the move
 * order; this file only renames. The key is the Chinese name rather than the
 * ECO code because several entries share a code (A00 alone covers five flank
 * openings), so the code is not unique enough to translate by.
 *
 * scripts/test-chess.mjs checks every distinct name in openings.js has an
 * entry here and that nothing here is orphaned.
 * @module openings-en
 */
(function (global) {
  global.CHESS_OPENINGS_EN = {
    // A — flank openings
    "波兰开局（索科尔斯基）": "Polish (Sokolsky) Opening",
    "格罗布开局": "Grob's Attack",
    "匈牙利开局": "Hungarian Opening",
    "范特克鲁伊斯开局": "Van 't Kruijs Opening",
    "邓斯特开局": "Dunst Opening",
    "拉尔森开局": "Larsen's Opening",
    "伯德开局": "Bird's Opening",
    "列蒂开局": "Réti Opening",
    "王翼印度攻击": "King's Indian Attack",
    "英国式开局": "English Opening",
    "英国式开局·对称变例": "English Opening: Symmetrical Variation",
    // A — queen's pawn sidelines and Indian defences
    "后兵开局": "Queen's Pawn Opening",
    "老贝诺尼防御": "Old Benoni Defense",
    "印度防御": "Indian Defense",
    "特龙波夫斯基进攻": "Trompowsky Attack",
    "伦敦体系": "London System",
    "布达佩斯弃兵": "Budapest Gambit",
    "老印度防御": "Old Indian Defense",
    "贝诺尼防御": "Benoni Defense",
    "沃尔加-贝科弃兵": "Benko (Volga) Gambit",
    "现代贝诺尼": "Modern Benoni",
    "荷兰防御": "Dutch Defense",
    // B — semi-open games
    "王兵开局": "King's Pawn Opening",
    "尼姆佐维奇防御": "Nimzowitsch Defense",
    "斯堪的纳维亚防御": "Scandinavian Defense",
    "阿廖欣防御": "Alekhine's Defense",
    "阿廖欣防御·现代变例": "Alekhine's Defense: Modern Variation",
    "现代防御": "Modern Defense",
    "皮尔茨防御": "Pirc Defense",
    "卡罗-卡恩防御": "Caro-Kann Defense",
    "卡罗-卡恩防御·前进变例": "Caro-Kann Defense: Advance Variation",
    "卡罗-卡恩防御·交换变例": "Caro-Kann Defense: Exchange Variation",
    "卡罗-卡恩防御·经典变例": "Caro-Kann Defense: Classical Variation",
    "西西里防御": "Sicilian Defense",
    "史密斯-莫拉弃兵": "Smith-Morra Gambit",
    "西西里防御·阿拉平变例": "Sicilian Defense: Alapin Variation",
    "封闭西西里": "Closed Sicilian",
    "西西里防御·斯维什尼科夫变例": "Sicilian Defense: Sveshnikov Variation",
    "西西里防御·加速龙式": "Sicilian Defense: Accelerated Dragon",
    "西西里防御·卡恩变例": "Sicilian Defense: Kan Variation",
    "西西里防御·龙式变例": "Sicilian Defense: Dragon Variation",
    "西西里防御·谢文宁根变例": "Sicilian Defense: Scheveningen Variation",
    "西西里防御·纳伊道夫变例": "Sicilian Defense: Najdorf Variation",
    // C — open games and the French
    "法兰西防御": "French Defense",
    "法兰西防御·交换变例": "French Defense: Exchange Variation",
    "法兰西防御·前进变例": "French Defense: Advance Variation",
    "法兰西防御·塔拉什变例": "French Defense: Tarrasch Variation",
    "法兰西防御·经典变例": "French Defense: Classical Variation",
    "法兰西防御·维纳韦尔变例": "French Defense: Winawer Variation",
    "王兵对局": "King's Pawn Game",
    "中心对局": "Center Game",
    "主教开局": "Bishop's Opening",
    "维也纳开局": "Vienna Game",
    "王翼弃兵": "King's Gambit",
    "王翼弃兵·接受": "King's Gambit Accepted",
    "王马开局": "King's Knight Opening",
    "菲利多尔防御": "Philidor Defense",
    "俄罗斯防御（彼得罗夫）": "Russian (Petrov) Defense",
    "苏格兰开局": "Scotch Game",
    "三马开局": "Three Knights Game",
    "四马开局": "Four Knights Game",
    "四马开局·西班牙变例": "Four Knights Game: Spanish Variation",
    "意大利开局": "Italian Game",
    "埃文斯弃兵": "Evans Gambit",
    "意大利开局·经典变例": "Italian Game: Classical Variation",
    "双马防御": "Two Knights Defense",
    "双马防御·骑士进攻": "Two Knights Defense: Knight Attack",
    "西班牙开局（鲁伊·洛佩斯）": "Ruy Lopez (Spanish Opening)",
    "西班牙开局·柏林防御": "Ruy Lopez: Berlin Defense",
    "西班牙开局·交换变例": "Ruy Lopez: Exchange Variation",
    "西班牙开局": "Ruy Lopez",
    "西班牙开局·封闭变例": "Ruy Lopez: Closed Variation",
    // D/E — closed games and Indian defences
    "后兵对局": "Queen's Pawn Game",
    "里希特-维列索夫进攻": "Richter-Veresov Attack",
    "科列体系": "Colle System",
    "后翼弃兵": "Queen's Gambit",
    "奇戈林防御": "Chigorin Defense",
    "阿尔宾反弃兵": "Albin Countergambit",
    "斯拉夫防御": "Slav Defense",
    "后翼弃兵·接受": "Queen's Gambit Accepted",
    "后翼弃兵·拒绝": "Queen's Gambit Declined",
    "后翼弃兵·交换变例": "Queen's Gambit Declined: Exchange Variation",
    "半斯拉夫防御": "Semi-Slav Defense",
    "格林菲尔德防御": "Grünfeld Defense",
    "格林菲尔德防御·交换变例": "Grünfeld Defense: Exchange Variation",
    "卡塔兰开局": "Catalan Opening",
    "新印度防御": "Queen's Indian Defense",
    "尼姆佐-印度防御": "Nimzo-Indian Defense",
    "尼姆佐-印度防御·经典变例": "Nimzo-Indian Defense: Classical Variation",
    "尼姆佐-印度防御·鲁宾斯坦体系": "Nimzo-Indian Defense: Rubinstein System",
    "王翼印度防御": "King's Indian Defense",
  };
})(typeof window !== "undefined" ? window : globalThis);
