/**
 * The personas' names and their two lines, in the three languages
 * (v8-0-plan B4). Content, like a lesson's text, not interface: it ships in
 * the opponents chunk (opponents-chunk.js) rather than in the first-paint
 * dictionary, and scripts/test-chess.mjs holds it to what the dictionary
 * checks hold keys to — every persona in every language, and 7.8's rule:
 * the lines state facts (the rung, the style, the opening, what was counted),
 * never a judgement of the player or a feeling of the machine.
 *
 * `bye` is filled with {0} the opening, {1} the moves, {2} the engine's
 * captures, {3} its checks; a persona without its own says the shared one.
 * @module opponents-lines
 */
export const OP_LINES = {
  "zh-CN": {
    say: "{0}：{1}", bye: "本局开局：{0}，共 {1} 回合。", noOpening: "未收录的开局",
    seg: ["入门", "进阶", "高手"], segAria: "按水平分段",
    pip: { name: "皮普", hello: "新手档，不带风格：会主动犯错，常常丢子。" },
    tomo: { name: "托莫", hello: "休闲档，不带风格：比新手准，仍会丢子。", bye: "本局开局：{0}，共 {1} 回合，托莫吃子 {2} 次。" },
    lina: { name: "莉娜", hello: "练习档，重原则：抢中心、出轻子、早易位。" },
    kai: { name: "凯", hello: "进步档，爱进攻：子力往你的王那边压。", bye: "本局开局：{0}；凯将军 {3} 次。" },
    ada: { name: "艾达", hello: "稳健档，不带风格：算三步，很少大失误。" },
    remy: { name: "雷米", hello: "扎实档，重原则：开局按三原则出子。" },
    ben: { name: "本", hello: "初级档，不带风格：等级分 1320。" },
    nico: { name: "尼可", hello: "初级+ 档，不带风格：等级分 1420，不总走最好的那一步。", bye: "本局开局：{0}；尼可吃子 {2} 次。" },
    vera: { name: "薇拉", hello: "中级− 档，不带风格：等级分 1542。", bye: "本局开局：{0}；薇拉将军 {3} 次。" },
    sol: { name: "索尔", hello: "中级档，不带风格：等级分 1700。" },
    leo: { name: "利奥", hello: "中级+ 档，不带风格：等级分 1797。" },
    ivy: { name: "艾薇", hello: "高级− 档，不带风格：等级分 1876。" },
    max: { name: "马克斯", hello: "高级档，不带风格：等级分 1982。", bye: "本局开局：{0}；马克斯将军 {3} 次。" },
    iris: { name: "艾瑞丝", hello: "高级+ 档，不带风格：等级分 2104。" },
    otto: { name: "奥托", hello: "专家档，不带风格：等级分 2239。", bye: "本局开局：{0}；奥托吃子 {2} 次。" },
    hugo: { name: "雨果", hello: "专家+ 档，不带风格：等级分 2339。" },
    zoe: { name: "佐伊", hello: "大师档，不带风格：等级分 2460。", bye: "本局开局：{0}；佐伊将军 {3} 次。" },
    lars: { name: "拉尔斯", hello: "大师+ 档，不带风格：等级分 2574，出手快，想得浅。" },
    nora: { name: "诺拉", hello: "强力档，不带风格：等级分 2683，比大师+ 想得深。" },
    kit: { name: "基特", hello: "强力+ 档，不带风格：等级分 2807，想得更深。", bye: "本局开局：{0}；基特吃子 {2} 次。" },
    fish: { name: "Stockfish", hello: "全力档：不设限的 Stockfish 19，每步想 1.2 秒，等级分 2877。" },
  },
  "en": {
    say: "{0}: {1}", bye: "Opening: {0}. {1} moves.", noOpening: "an opening not in the book",
    seg: ["Starter", "Club", "Expert"], segAria: "Opponents by level",
    pip: { name: "Pip", hello: "Gentle, no style: makes mistakes on purpose and often drops a piece." },
    tomo: { name: "Tomo", hello: "Casual, no style: sharper than Gentle, still drops pieces.", bye: "Opening: {0}. {1} moves; Tomo captured {2} times." },
    lina: { name: "Lina", hello: "Practice, by the book: centre first, minor pieces out, castle early." },
    kai: { name: "Kai", hello: "Improving, attacker: keeps bringing pieces toward your king.", bye: "Opening: {0}. Kai gave check {3} times." },
    ada: { name: "Ada", hello: "Steady, no style: looks three moves ahead and seldom blunders." },
    remy: { name: "Remy", hello: "Solid, by the book: develops by the three opening principles." },
    ben: { name: "Ben", hello: "Novice, no style: rated 1320." },
    nico: { name: "Nico", hello: "Novice+, no style: rated 1420; does not always play the best move.", bye: "Opening: {0}. Nico captured {2} times." },
    vera: { name: "Vera", hello: "Intermediate−, no style: rated 1542.", bye: "Opening: {0}. Vera gave check {3} times." },
    sol: { name: "Sol", hello: "Intermediate, no style: rated 1700." },
    leo: { name: "Leo", hello: "Intermediate+, no style: rated 1797." },
    ivy: { name: "Ivy", hello: "Advanced−, no style: rated 1876." },
    max: { name: "Max", hello: "Advanced, no style: rated 1982.", bye: "Opening: {0}. Max gave check {3} times." },
    iris: { name: "Iris", hello: "Advanced+, no style: rated 2104." },
    otto: { name: "Otto", hello: "Expert, no style: rated 2239.", bye: "Opening: {0}. Otto captured {2} times." },
    hugo: { name: "Hugo", hello: "Expert+, no style: rated 2339." },
    zoe: { name: "Zoe", hello: "Master, no style: rated 2460.", bye: "Opening: {0}. Zoe gave check {3} times." },
    lars: { name: "Lars", hello: "Master+, no style: rated 2574; moves quickly and looks only a short way ahead." },
    nora: { name: "Nora", hello: "Strong, no style: rated 2683; looks further ahead than Master+." },
    kit: { name: "Kit", hello: "Strong+, no style: rated 2807; looks further ahead still.", bye: "Opening: {0}. Kit captured {2} times." },
    fish: { name: "Stockfish", hello: "Strongest: Stockfish 19 with no limit, 1.2 seconds a move; rated 2877." },
  },
  "ja": {
    say: "{0}：{1}", bye: "序盤：{0}。{1} 手。", noOpening: "定跡集にない序盤",
    seg: ["入門", "中堅", "強豪"], segAria: "レベル別の対戦相手",
    pip: { name: "ピップ", hello: "やさしい、スタイルなし：わざとミスをし、よく駒を落とす。" },
    tomo: { name: "トモ", hello: "お気軽、スタイルなし：やさしいより正確だが、まだ駒を落とす。", bye: "序盤：{0}。{1} 手、トモが駒を取ったのは {2} 回。" },
    lina: { name: "リナ", hello: "練習、定跡どおり：中央、小駒の展開、早めのキャスリング。" },
    kai: { name: "カイ", hello: "上達、攻め好み：駒をあなたの王のほうへ寄せ続ける。", bye: "序盤：{0}。カイのチェックは {3} 回。" },
    ada: { name: "エイダ", hello: "堅実、スタイルなし：3 手先まで読み、大きなミスはまれ。" },
    remy: { name: "レミー", hello: "手堅い、定跡どおり：序盤の三原則どおりに駒を出す。" },
    ben: { name: "ベン", hello: "初級、スタイルなし：レーティング 1320。" },
    nico: { name: "ニコ", hello: "初級+、スタイルなし：レーティング 1420。いつも最善手を指すとは限らない。", bye: "序盤：{0}。ニコが駒を取ったのは {2} 回。" },
    vera: { name: "ヴェラ", hello: "中級−、スタイルなし：レーティング 1542。", bye: "序盤：{0}。ヴェラのチェックは {3} 回。" },
    sol: { name: "ソル", hello: "中級、スタイルなし：レーティング 1700。" },
    leo: { name: "レオ", hello: "中級+、スタイルなし：レーティング 1797。" },
    ivy: { name: "アイビー", hello: "上級−、スタイルなし：レーティング 1876。" },
    max: { name: "マックス", hello: "上級、スタイルなし：レーティング 1982。", bye: "序盤：{0}。マックスのチェックは {3} 回。" },
    iris: { name: "アイリス", hello: "上級+、スタイルなし：レーティング 2104。" },
    otto: { name: "オットー", hello: "エキスパート、スタイルなし：レーティング 2239。", bye: "序盤：{0}。オットーが駒を取ったのは {2} 回。" },
    hugo: { name: "ユーゴ", hello: "エキスパート+、スタイルなし：レーティング 2339。" },
    zoe: { name: "ゾーイ", hello: "マスター、スタイルなし：レーティング 2460。", bye: "序盤：{0}。ゾーイのチェックは {3} 回。" },
    lars: { name: "ラース", hello: "マスター+、スタイルなし：レーティング 2574。指すのは速いが、読みは浅い。" },
    nora: { name: "ノーラ", hello: "強力、スタイルなし：レーティング 2683。マスター+ より深く読む。" },
    kit: { name: "キット", hello: "強力+、スタイルなし：レーティング 2807。さらに深く読む。", bye: "序盤：{0}。キットが駒を取ったのは {2} 回。" },
    fish: { name: "Stockfish", hello: "全力：制限なしの Stockfish 19、1 手 1.2 秒。レーティング 2877。" },
  },
};
