/**
 * The personas' names and their two lines, in the three languages
 * (v8-0-plan B4). Content, like a lesson's text, not interface: it ships in
 * the opponents chunk (opponents-chunk.js) rather than in the first-paint
 * dictionary, and scripts/test-chess.mjs holds it to what the dictionary
 * checks hold keys to — every persona in every language, and 7.8's rule:
 * the lines state facts (the rung, the style, the opening, what was counted),
 * never a judgement of the player or a feeling of the machine.
 *
 * `bye` is filled with {0} the opening, {1} the moves, {2} the engine's
 * captures, {3} its checks; a persona without its own says the shared one.
 * @module opponents-lines
 */
export const OP_LINES = {
  "zh-CN": {
    say: "{0}：{1}", bye: "本局开局：{0}，共 {1} 回合。", noOpening: "未收录的开局",
    seg: ["入门", "进阶", "高手"], segAria: "按水平分段",
    pip: { name: "皮普", hello: "新手档，不带风格：会主动犯错，常常丢子。" },
    tomo: { name: "托莫", hello: "休闲档，不带风格：比新手准，仍会丢子。", bye: "本局开局：{0}，共 {1} 回合，托莫吃子 {2} 次。" },
    lina: { name: "莉娜", hello: "练习档，重原则：抢中心、出轻子、早易位。" },
    kai: { name: "凯", hello: "进步档，爱进攻：子力往你的王那边压。", bye: "本局开局：{0}；凯将军 {3} 次。" },
    ada: { name: "艾达", hello: "稳健档，不带风格：算三步，很少大失误。" },
    remy: { name: "雷米", hello: "扎实档，重原则：开局按三原则出子。" },
    juno: { name: "朱诺", hello: "老练档，不带风格：算五步，按胜率损失挑着。" },
    ben: { name: "本", hello: "初级档，不带风格：Stockfish 限制在 UCI_Elo 1320。" },
    nico: { name: "尼可", hello: "初级+ 档，不带风格：Stockfish 限制在 UCI_Elo 1500，从 6 个候选着里挑。", bye: "本局开局：{0}；尼可吃子 {2} 次。" },
    vera: { name: "薇拉", hello: "中级− 档，不带风格：Stockfish 限制在 UCI_Elo 1500。", bye: "本局开局：{0}；薇拉将军 {3} 次。" },
    sol: { name: "索尔", hello: "中级档，不带风格：Stockfish 限制在 UCI_Elo 1700。" },
    leo: { name: "利奥", hello: "中级+ 档，不带风格：Stockfish 限制在 UCI_Elo 1840。" },
    max: { name: "马克斯", hello: "高级档，不带风格：Stockfish 限制在 UCI_Elo 2290。", bye: "本局开局：{0}；马克斯将军 {3} 次。" },
    iris: { name: "艾瑞丝", hello: "高级+ 档，不带风格：Stockfish 限制在 UCI_Elo 2450。" },
    otto: { name: "奥托", hello: "专家档，不带风格：Stockfish 限制在 UCI_Elo 2570。", bye: "本局开局：{0}；奥托吃子 {2} 次。" },
    hugo: { name: "雨果", hello: "专家+ 档，不带风格：Stockfish 限制在 UCI_Elo 2670。" },
    zoe: { name: "佐伊", hello: "大师档，不带风格：Stockfish 限制在 UCI_Elo 2750。", bye: "本局开局：{0}；佐伊将军 {3} 次。" },
    lars: { name: "拉尔斯", hello: "大师+ 档，不带风格：满强度的 Stockfish，每步约 400 个节点。" },
    nora: { name: "诺拉", hello: "强力档，不带风格：满强度的 Stockfish，每步约 2 千个节点。" },
    kit: { name: "基特", hello: "强力+ 档，不带风格：满强度的 Stockfish，每步约 1 万个节点。", bye: "本局开局：{0}；基特吃子 {2} 次。" },
    vik: { name: "维克", hello: "顶级档，不带风格：满强度的 Stockfish，每步约 5 万个节点。" },
    fish: { name: "Stockfish", hello: "不限档：满强度的 Stockfish 19，每步 1.2 秒。" },
  },
  "en": {
    say: "{0}: {1}", bye: "Opening: {0}. {1} moves.", noOpening: "an opening not in the book",
    seg: ["Starter", "Club", "Expert"], segAria: "Opponents by level",
    pip: { name: "Pip", hello: "Gentle, no style: makes mistakes on purpose and often drops a piece." },
    tomo: { name: "Tomo", hello: "Casual, no style: sharper than Gentle, still drops pieces.", bye: "Opening: {0}. {1} moves; Tomo captured {2} times." },
    lina: { name: "Lina", hello: "Practice, by the book: centre first, minor pieces out, castle early." },
    kai: { name: "Kai", hello: "Improving, attacker: keeps bringing pieces toward your king.", bye: "Opening: {0}. Kai gave check {3} times." },
    ada: { name: "Ada", hello: "Steady, no style: looks three moves ahead and seldom blunders." },
    remy: { name: "Remy", hello: "Solid, by the book: develops by the three opening principles." },
    juno: { name: "Juno", hello: "Seasoned, no style: looks five moves ahead and picks by the win chance a move gives away." },
    ben: { name: "Ben", hello: "Novice, no style: Stockfish limited to UCI_Elo 1320." },
    nico: { name: "Nico", hello: "Novice+, no style: Stockfish limited to UCI_Elo 1500, choosing among 6 candidate moves.", bye: "Opening: {0}. Nico captured {2} times." },
    vera: { name: "Vera", hello: "Intermediate−, no style: Stockfish limited to UCI_Elo 1500.", bye: "Opening: {0}. Vera gave check {3} times." },
    sol: { name: "Sol", hello: "Intermediate, no style: Stockfish limited to UCI_Elo 1700." },
    leo: { name: "Leo", hello: "Intermediate+, no style: Stockfish limited to UCI_Elo 1840." },
    max: { name: "Max", hello: "Advanced, no style: Stockfish limited to UCI_Elo 2290.", bye: "Opening: {0}. Max gave check {3} times." },
    iris: { name: "Iris", hello: "Advanced+, no style: Stockfish limited to UCI_Elo 2450." },
    otto: { name: "Otto", hello: "Expert, no style: Stockfish limited to UCI_Elo 2570.", bye: "Opening: {0}. Otto captured {2} times." },
    hugo: { name: "Hugo", hello: "Expert+, no style: Stockfish limited to UCI_Elo 2670." },
    zoe: { name: "Zoe", hello: "Master, no style: Stockfish limited to UCI_Elo 2750.", bye: "Opening: {0}. Zoe gave check {3} times." },
    lars: { name: "Lars", hello: "Master+, no style: Stockfish at full strength, about 400 nodes a move." },
    nora: { name: "Nora", hello: "Strong, no style: Stockfish at full strength, about 2,000 nodes a move." },
    kit: { name: "Kit", hello: "Strong+, no style: Stockfish at full strength, about 10,000 nodes a move.", bye: "Opening: {0}. Kit captured {2} times." },
    vik: { name: "Vik", hello: "Top, no style: Stockfish at full strength, about 50,000 nodes a move." },
    fish: { name: "Stockfish", hello: "Unrated: Stockfish 19 at full strength, 1.2 seconds a move." },
  },
  "ja": {
    say: "{0}：{1}", bye: "序盤：{0}。{1} 手。", noOpening: "定跡集にない序盤",
    seg: ["入門", "中堅", "強豪"], segAria: "レベル別の対戦相手",
    pip: { name: "ピップ", hello: "やさしい、スタイルなし：わざとミスをし、よく駒を落とす。" },
    tomo: { name: "トモ", hello: "お気軽、スタイルなし：やさしいより正確だが、まだ駒を落とす。", bye: "序盤：{0}。{1} 手、トモが駒を取ったのは {2} 回。" },
    lina: { name: "リナ", hello: "練習、定跡どおり：中央、小駒の展開、早めのキャスリング。" },
    kai: { name: "カイ", hello: "上達、攻め好み：駒をあなたの王のほうへ寄せ続ける。", bye: "序盤：{0}。カイのチェックは {3} 回。" },
    ada: { name: "エイダ", hello: "堅実、スタイルなし：3 手先まで読み、大きなミスはまれ。" },
    remy: { name: "レミー", hello: "手堅い、定跡どおり：序盤の三原則どおりに駒を出す。" },
    juno: { name: "ジュノ", hello: "熟練、スタイルなし：5 手先まで読み、勝率の損失で手を選ぶ。" },
    ben: { name: "ベン", hello: "初級、スタイルなし：UCI_Elo 1320 に制限した Stockfish。" },
    nico: { name: "ニコ", hello: "初級+、スタイルなし：UCI_Elo 1500 に制限した Stockfish、6 つの候補手から選ぶ。", bye: "序盤：{0}。ニコが駒を取ったのは {2} 回。" },
    vera: { name: "ヴェラ", hello: "中級−、スタイルなし：UCI_Elo 1500 に制限した Stockfish。", bye: "序盤：{0}。ヴェラのチェックは {3} 回。" },
    sol: { name: "ソル", hello: "中級、スタイルなし：UCI_Elo 1700 に制限した Stockfish。" },
    leo: { name: "レオ", hello: "中級+、スタイルなし：UCI_Elo 1840 に制限した Stockfish。" },
    max: { name: "マックス", hello: "上級、スタイルなし：UCI_Elo 2290 に制限した Stockfish。", bye: "序盤：{0}。マックスのチェックは {3} 回。" },
    iris: { name: "アイリス", hello: "上級+、スタイルなし：UCI_Elo 2450 に制限した Stockfish。" },
    otto: { name: "オットー", hello: "エキスパート、スタイルなし：UCI_Elo 2570 に制限した Stockfish。", bye: "序盤：{0}。オットーが駒を取ったのは {2} 回。" },
    hugo: { name: "ユーゴ", hello: "エキスパート+、スタイルなし：UCI_Elo 2670 に制限した Stockfish。" },
    zoe: { name: "ゾーイ", hello: "マスター、スタイルなし：UCI_Elo 2750 に制限した Stockfish。", bye: "序盤：{0}。ゾーイのチェックは {3} 回。" },
    lars: { name: "ラース", hello: "マスター+、スタイルなし：全力の Stockfish、1 手あたり約 400 ノード。" },
    nora: { name: "ノーラ", hello: "強力、スタイルなし：全力の Stockfish、1 手あたり約 2 千ノード。" },
    kit: { name: "キット", hello: "強力+、スタイルなし：全力の Stockfish、1 手あたり約 1 万ノード。", bye: "序盤：{0}。キットが駒を取ったのは {2} 回。" },
    vik: { name: "ヴィク", hello: "トップ、スタイルなし：全力の Stockfish、1 手あたり約 5 万ノード。" },
    fish: { name: "Stockfish", hello: "無制限：全力の Stockfish 19、1 手 1.2 秒。" },
  },
};
