/**
 * English puzzle prose.
 *
 * Same split as lessons-en.js: puzzles.js owns the chess (FEN, solution,
 * material gain) and this file owns only the words. A translation therefore
 * cannot drift into describing a different puzzle, and a missing entry falls
 * back to the Chinese name rather than blanking the label.
 *
 * Shape: { [puzzleId]: { name, motif? } } — motif only where puzzles.js sets
 * one. scripts/test-chess.mjs checks every puzzle id is covered and that no
 * entry names an id that does not exist.
 * @module puzzles-en
 */
(function (global) {
  global.CHESS_PUZZLES_EN = {
    // —— mate in one ——
    "m1-backrank-r": { name: "Back-rank mate" },
    "m1-q-knight": { name: "Queen and knight mate" },
    "m1-smother": { name: "Smothered mate" },
    "m1-ladder": { name: "Ladder mate" },
    "m1-kq-box": { name: "King and queen mate" },
    "m1-epaulette": { name: "Epaulette mate" },
    "m1-pawn-q": { name: "Queen backed by a pawn" },
    "m1-edge-r": { name: "Rook mate on the edge" },
    "m1-br-queen": { name: "Back-rank mate (queen)" },
    "m1-kq-g7": { name: "Queen kiss mate" },
    "m1-bishops": { name: "Two-bishop mate" },
    "m1-q-backrank": { name: "Capture the rook, mate on the back rank" },
    "m1-promo": { name: "Promotion mate" },
    "m1-arabian": { name: "Arabian mate" },
    // —— mate in two ——
    "m2-corner-h8": { name: "Quiet move, cornered" },
    "m2-corner-a1": { name: "Quiet move, cornered III" },
    "m2-corner-rook": { name: "King and rook corner mate" },
    "m2-ladder-rank": { name: "Two rooks drive the king" },
    "m2-ladder-file": { name: "Two rooks drive the king II" },
    "m2-rr-sac": { name: "Doubled rooks force the back rank" },
    "m2-q-sac": { name: "Queen sacrifice, back-rank mate" },
    // —— mate in three ——
    "m3-ladder-b": { name: "Ladder mate in three" },
    "m3-ladder-m": { name: "Ladder mate in three III" },
    "m3-kq-corner": { name: "Queen and king corner the enemy in three" },
    "m3-kr-corner": { name: "Rook and king corner the enemy in three" },
    "m3-promo": { name: "Promotion mate in three" },
    // —— win material ——
    "w-hangq": { name: "Take the hanging queen" },
    "w-forkdone": { name: "Check, fork, win the rook" },
    "w-pawntakes": { name: "A pawn takes a bishop" },
    "w-cornerrook": { name: "Accept the rook in the corner" },
    "w-looseknight": { name: "Take the loose knight" },
    "w-smallbest": { name: "A small profit beats a loss" },
    "w-loosebishop": { name: "Rook sweeps up a loose bishop" },
    "w-discovered": { name: "Discovered attack wins the queen" },
    "w-hangrook": { name: "Take the hanging rook" },
    "w-nfork-rr": { name: "Knight takes the corner rook" },
    "w-qxbishop": { name: "Queen takes a loose bishop" },
    "w-rxrook": { name: "Rook takes a loose rook" },
    "w-bxqueen": { name: "Bishop takes a loose queen" },
    "w-nxqueen": { name: "Knight takes a loose queen" },
    "w-pxrook": { name: "A pawn takes a rook" },
    "w-royalfork": { name: "Knight forks king and queen" },
    "w-royalfork2": { name: "Knight forks king and queen II" },
    // —— tactical motifs ——
    "t-skewer-h": { name: "Skewer wins the queen (file)", motif: "skewer" },
    "t-deflect-r": { name: "Deflect the rook off the file", motif: "deflection" },
    "t-remove-n": { name: "Take the knight that guards the rook", motif: "removing the defender" },
    "t-remove-b": { name: "Take the bishop that guards the rook", motif: "removing the defender" },
    "t-overload-r": { name: "Make the overloaded rook choose", motif: "overloading" },
    "t-disco-q": { name: "Discovered check nets the queen", motif: "discovered check" },
    "t-disco-r": { name: "Discovered check nets the rook", motif: "discovered check" },
    "t-disco-b": { name: "Discovered check nets the queen (bishop)", motif: "discovered check" },
    "t-skewer-d": { name: "Skewer wins the queen (d-file)", motif: "skewer" },
    "t-pin-e": { name: "Pin and pile on (e-file)", motif: "pin" },
    "t-pin-diag": { name: "Pin and pile on (diagonal)", motif: "pin" },
    "t-fork-n": { name: "Knight forks king and queen", motif: "fork" },
    "t-double-q": { name: "Queen's double attack", motif: "double attack" },

    // —— generated set (v1.6): named patterns, verified by the solver ——
    "m1-damiano": { name: "Damiano's mate" },
    "w-gen-rxq": { name: "Rook takes a loose queen" },
    "w-gen-rxq2": { name: "Rook takes a loose queen II" },
    "w-gen-bxr": { name: "Bishop takes a loose rook" },
    "w-gen-bxr2": { name: "Bishop takes a loose rook II" },
    "w-gen-nxr": { name: "Knight takes a loose rook" },
    "w-gen-nxr2": { name: "Knight takes a loose rook II" },
    "w-gen-qxr": { name: "Queen takes a loose rook" },
    "w-gen-qxr2": { name: "Queen takes a loose rook II" },
    "w-gen-rxb": { name: "Rook takes a loose bishop" },
    "w-gen-rxb2": { name: "Rook takes a loose bishop II" },
    "w-gen-rxn": { name: "Rook takes a loose knight" },
    "w-gen-rxn2": { name: "Rook takes a loose knight II" },
    "w-gen-bxn": { name: "Bishop takes a loose knight" },
    "w-gen-bxn2": { name: "Bishop takes a loose knight II" },
    "w-gen-nxb": { name: "Knight takes a loose bishop" },
    "w-gen-nxb2": { name: "Knight takes a loose bishop II" },
    "w-gen-pxn": { name: "A pawn takes a knight" },
    "w-gen-pxn2": { name: "A pawn takes a knight II" },
    "w-gen-qxn": { name: "Queen takes a loose knight" },
    "w-gen-qxn2": { name: "Queen takes a loose knight II" },
    "t-gen-disco-q": { name: "Knight steps aside: discovered check wins the queen", motif: "discovered check" },
    "t-gen-disco-q2": { name: "Knight steps aside: discovered check wins the queen II", motif: "discovered check" },
    "t-gen-disco-r": { name: "Knight steps aside: discovered check wins the rook", motif: "discovered check" },
    "t-gen-disco-r2": { name: "Knight steps aside: discovered check wins the rook II", motif: "discovered check" },
    "t-gen-disco-n": { name: "Bishop steps aside: discovered check wins the knight", motif: "discovered check" },
    "t-gen-disco-n2": { name: "Bishop steps aside: discovered check wins the knight II", motif: "discovered check" },
    "t-gen-disco-b": { name: "Knight steps aside: discovered check wins the bishop", motif: "discovered check" },
    "t-gen-disco-b2": { name: "Knight steps aside: discovered check wins the bishop II", motif: "discovered check" },

    // regenerated mate set (v1.7): key move is always a piece, never the king
    "m2-net-rr": { name: "Rook closes the net in two" },
    "m2-net-rr2": { name: "Rook closes the net in two II" },
    "m2-net-qn": { name: "Knight closes the net in two" },
    "m2-net-qn2": { name: "Queen closes the net in two" },
    "m2-net-rb": { name: "Rook closes the net in two III" },
    "m2-net-rb2": { name: "Rook closes the net in two IV" },
    "m2-net-qb": { name: "Queen closes the net in two II" },
    "m2-net-qb2": { name: "Queen closes the net in two III" },
    "m2-net-rn": { name: "Knight closes the net in two II" },
    "m2-net-rn2": { name: "Knight closes the net in two III" },
    "m2-net-qr": { name: "Rook closes the net in two V" },
    "m2-net-qr2": { name: "Rook closes the net in two VI" },
    "m3-hunt-rr": { name: "Rook hunts the king in three" },
    "m3-hunt-rr2": { name: "Rook hunts the king in three II" },
    "m3-hunt-qr": { name: "Queen hunts the king in three" },
    "m3-hunt-qr2": { name: "Rook hunts the king in three III" },
    "m3-hunt-qb": { name: "Bishop hunts the king in three" },
    "m3-hunt-qb2": { name: "Queen hunts the king in three II" },
    "m3-hunt-qn": { name: "Queen hunts the king in three III" },
    "m3-hunt-qn2": { name: "Queen hunts the king in three IV" },
    // —— parry the threat ——
    "d-battery-only": { name: "Bishop-and-queen battery: the only block" },
    "d-battery-eat": { name: "Bishop-and-queen battery: take the queen" },
    "d-battery-two": { name: "Bishop-and-queen battery: plug g2" },
    "d-back-luft": { name: "Back-rank mate: give the king air" },
    "d-back-eat": { name: "Back-rank mate: remove the helper first" },
    "d-back-step": { name: "Back-rank mate: the king can step aside too" },
    "d-qe1": { name: "Queen mates on e1" },
    "d-qd1": { name: "Queen mates on d1" },
    "d-qe3-eat": { name: "A pawn takes the queen: the cheapest answer" },
    "d-qa1": { name: "Queen on the long diagonal" },
    "d-qf1": { name: "A king in the corner is in more danger" },
    "d-qd1-h1": { name: "King in the corner: take the attacker" },
    "d-re1": { name: "A rook mates on the back rank too" },
    "d-knights": { name: "Two knights closing on f2" },
    "d-knights-eat": { name: "Two knights: take the nearer one" },
    "d-queenside": { name: "Castled queenside: still needs air" },
    "d-queenside2": { name: "Castled queenside: the long diagonal" },
    "d-gpawn-eat": { name: "After the g-pawn has moved" },
    "d-gpawn-step": { name: "After the g-pawn has moved II" },
    "d-qg4": { name: "The queen comes in from the side" },
    // —— saving the draw ——
    "dr-a1-rook": { name: "Stalemate in the corner: give up the rook" },
    "dr-a1-bishop": { name: "Stalemate in the corner: bishop check sacrifice" },
    "dr-a1-knight": { name: "Stalemate in the corner: give up the knight" },
    "dr-a1-rook2": { name: "Stalemate in the corner: the king can be far away" },
    "dr-a1-bish2": { name: "Stalemate in the corner: the bishop comes a long way" },
    "dr-a1-knt2": { name: "Stalemate in the corner: the knight jumps in" },
    "dr-a1-b3r": { name: "Stalemate on b3: give up the rook" },
    "dr-a1-b3b": { name: "Stalemate on b3: give up the bishop" },
    "dr-a1-b3n": { name: "Stalemate on b3: give up the knight" },
    "dr-h1-rook": { name: "Stalemate on the other side: give up the rook" },
    "dr-h1-bishop": { name: "Stalemate on the other side: bishop check sacrifice" },
    "dr-h1-knight": { name: "Stalemate on the other side: give up the knight" },
    "dr-h1-rook2": { name: "Stalemate on the other side: the king far off" },
    "dr-h1-g3r": { name: "Stalemate on g3: give up the rook" },
    "dr-h1-g3b": { name: "Stalemate on g3: give up the bishop" },
    "dr-h1-g3n": { name: "Stalemate on g3: give up the knight" },
    "dr-a8-rook": { name: "Stalemate in the top corner: give up the rook" },
    // real-game tactics (1.17) — numbered on purpose: naming the motif
    // would give the answer away, which is the one thing this set is for
    "r-01": { name: "Real game 01" },
    "r-02": { name: "Real game 02" },
    "r-03": { name: "Real game 03" },
    "r-04": { name: "Real game 04" },
    "r-05": { name: "Real game 05" },
    "r-06": { name: "Real game 06" },
    "r-07": { name: "Real game 07" },
    "r-08": { name: "Real game 08" },
    "r-09": { name: "Real game 09" },
    "r-10": { name: "Real game 10" },
    "r-11": { name: "Real game 11" },
    "r-12": { name: "Real game 12" },
    "r-13": { name: "Real game 13" },
    "r-14": { name: "Real game 14" },
    "r-15": { name: "Real game 15" },
    "r-16": { name: "Real game 16" },
    "r-17": { name: "Real game 17" },
    "r-18": { name: "Real game 18" },
    "r-19": { name: "Real game 19" },
    "r-20": { name: "Real game 20" },
    "r-21": { name: "Real game 21" },
    "r-22": { name: "Real game 22" },
    "r-23": { name: "Real game 23" },
    "dr-a8-bishop": { name: "Stalemate in the top corner: bishop check sacrifice" },
    "dr-a8-knight": { name: "Stalemate in the top corner: give up the knight" },
    "dr-h8-rook": { name: "Stalemate in the far corner: give up the rook" },
  };
})(typeof window !== "undefined" ? window : globalThis);
