/**
 * English puzzle prose.
 *
 * Same split as lessons-en.js: puzzles.js owns the chess (FEN, solution,
 * material gain) and this file owns only the words. A translation therefore
 * cannot drift into describing a different puzzle, and a missing entry falls
 * back to the Chinese name rather than blanking the label.
 *
 * Shape: { [puzzleId]: { name, motif? } } — motif only where puzzles.js sets
 * one. scripts/test-chess.mjs checks every puzzle id is covered and that no
 * entry names an id that does not exist.
 * @module puzzles-en
 */
(function (global) {
  global.CHESS_PUZZLES_EN = {
    // —— mate in one ——
    "m1-backrank-r": { name: "Back-rank mate" },
    "m1-q-knight": { name: "Queen and knight mate" },
    "m1-smother": { name: "Smothered mate" },
    "m1-ladder": { name: "Ladder mate" },
    "m1-kq-box": { name: "King and queen mate" },
    "m1-epaulette": { name: "Epaulette mate" },
    "m1-pawn-q": { name: "Queen backed by a pawn" },
    "m1-edge-r": { name: "Rook mate on the edge" },
    "m1-br-rook": { name: "Back-rank mate (rook)" },
    "m1-br-queen": { name: "Back-rank mate (queen)" },
    "m1-kq-g7": { name: "Queen kiss mate" },
    "m1-bishops": { name: "Two-bishop mate" },
    "m1-q-backrank": { name: "Capture the rook, mate on the back rank" },
    "m1-promo": { name: "Promotion mate" },
    "m1-arabian": { name: "Arabian mate" },
    // —— mate in two ——
    "m2-corner-h8": { name: "Quiet move, cornered" },
    "m2-corner-a8": { name: "Quiet move, cornered II" },
    "m2-corner-a1": { name: "Quiet move, cornered III" },
    "m2-corner-rook": { name: "King and rook corner mate" },
    "m2-ladder-rank": { name: "Two rooks drive the king" },
    "m2-ladder-file": { name: "Two rooks drive the king II" },
    "m2-rr-sac": { name: "Doubled rooks force the back rank" },
    "m2-q-sac": { name: "Queen sacrifice, back-rank mate" },
    // —— mate in three ——
    "m3-ladder-b": { name: "Ladder mate in three" },
    "m3-ladder-c": { name: "Ladder mate in three II" },
    "m3-ladder-m": { name: "Ladder mate in three III" },
    "m3-kq-corner": { name: "Queen and king corner the enemy in three" },
    "m3-kr-corner": { name: "Rook and king corner the enemy in three" },
    "m3-promo": { name: "Promotion mate in three" },
    // —— win material ——
    "w-hangq": { name: "Take the hanging queen" },
    "w-forkdone": { name: "Check, fork, win the rook" },
    "w-pawntakes": { name: "A pawn takes a bishop" },
    "w-cornerrook": { name: "Accept the rook in the corner" },
    "w-looseknight": { name: "Take the loose knight" },
    "w-smallbest": { name: "A small profit beats a loss" },
    "w-loosebishop": { name: "Rook sweeps up a loose bishop" },
    "w-discovered": { name: "Discovered attack wins the queen" },
    "w-hangrook": { name: "Take the hanging rook" },
    "w-nfork-rr": { name: "Knight takes the corner rook" },
    "w-qxbishop": { name: "Queen takes a loose bishop" },
    "w-rxrook": { name: "Rook takes a loose rook" },
    "w-bxqueen": { name: "Bishop takes a loose queen" },
    "w-nxqueen": { name: "Knight takes a loose queen" },
    "w-pxrook": { name: "A pawn takes a rook" },
    "w-royalfork": { name: "Knight forks king and queen" },
    "w-royalfork2": { name: "Knight forks king and queen II" },
    // —— tactical motifs ——
    "t-skewer-h": { name: "Skewer wins the queen (file)", motif: "skewer" },
    "t-skewer-a": { name: "Skewer wins the queen (a-file)", motif: "skewer" },
    "t-skewer-e": { name: "Skewer wins the queen (centre)", motif: "skewer" },
    "t-disco-q": { name: "Discovered check nets the queen", motif: "discovered check" },
    "t-disco-r": { name: "Discovered check nets the rook", motif: "discovered check" },
    "t-disco-b": { name: "Discovered check nets the queen (bishop)", motif: "discovered check" },
    "t-skewer-b": { name: "Skewer wins the queen (b-file)", motif: "skewer" },
    "t-skewer-d": { name: "Skewer wins the queen (d-file)", motif: "skewer" },
    "t-pin-e": { name: "Pin and pile on (e-file)", motif: "pin" },
    "t-pin-diag": { name: "Pin and pile on (diagonal)", motif: "pin" },
    "t-fork-n": { name: "Knight forks king and queen", motif: "fork" },
    "t-double-q": { name: "Queen's double attack", motif: "double attack" },

    // —— generated set (v1.6): named patterns, verified by the solver ——
    "m1-damiano": { name: "Damiano's mate" },
    "m2-gen-rr": { name: "Two rooks close the net" },
    "m2-gen-rr2": { name: "Two rooks close the net II" },
    "m2-gen-qn": { name: "Queen and knight in two" },
    "m2-gen-qn2": { name: "Queen and knight in two II" },
    "m2-gen-rb": { name: "Rook and bishop in two" },
    "m2-gen-rb2": { name: "Rook and bishop in two II" },
    "m2-gen-qb": { name: "Queen and bishop in two" },
    "m2-gen-qb2": { name: "Queen and bishop in two II" },
    "m2-gen-rn": { name: "Rook and knight in two" },
    "m2-gen-rn2": { name: "Rook and knight in two II" },
    "m2-gen-rp": { name: "Rook and pawn in two" },
    "m2-gen-rp2": { name: "Rook and pawn in two II" },
    "m3-gen-rr": { name: "Two rooks drive the king in three" },
    "m3-gen-rr2": { name: "Two rooks drive the king in three II" },
    "m3-gen-rr3": { name: "Two rooks drive the king in three III" },
    "m3-gen-qr": { name: "Queen and rook in three" },
    "m3-gen-qr2": { name: "Queen and rook in three II" },
    "m3-gen-qr3": { name: "Queen and rook in three III" },
    "m3-gen-rn": { name: "Rook and knight in three" },
    "m3-gen-rn2": { name: "Rook and knight in three II" },
    "m3-gen-qb": { name: "Queen and bishop in three" },
    "m3-gen-qb2": { name: "Queen and bishop in three II" },
    "m3-gen-qb3": { name: "Queen and bishop in three III" },
    "w-gen-rxq": { name: "Rook takes a loose queen" },
    "w-gen-rxq2": { name: "Rook takes a loose queen II" },
    "w-gen-bxr": { name: "Bishop takes a loose rook" },
    "w-gen-bxr2": { name: "Bishop takes a loose rook II" },
    "w-gen-nxr": { name: "Knight takes a loose rook" },
    "w-gen-nxr2": { name: "Knight takes a loose rook II" },
    "w-gen-qxr": { name: "Queen takes a loose rook" },
    "w-gen-qxr2": { name: "Queen takes a loose rook II" },
    "w-gen-rxb": { name: "Rook takes a loose bishop" },
    "w-gen-rxb2": { name: "Rook takes a loose bishop II" },
    "w-gen-rxn": { name: "Rook takes a loose knight" },
    "w-gen-rxn2": { name: "Rook takes a loose knight II" },
    "w-gen-bxn": { name: "Bishop takes a loose knight" },
    "w-gen-bxn2": { name: "Bishop takes a loose knight II" },
    "w-gen-nxb": { name: "Knight takes a loose bishop" },
    "w-gen-nxb2": { name: "Knight takes a loose bishop II" },
    "w-gen-pxn": { name: "A pawn takes a knight" },
    "w-gen-pxn2": { name: "A pawn takes a knight II" },
    "w-gen-qxn": { name: "Queen takes a loose knight" },
    "w-gen-qxn2": { name: "Queen takes a loose knight II" },
    "t-gen-disco-q": { name: "Discovered check wins the queen", motif: "discovered check" },
    "t-gen-disco-q2": { name: "Discovered check wins the queen II", motif: "discovered check" },
    "t-gen-disco-r": { name: "Discovered check wins the rook", motif: "discovered check" },
    "t-gen-disco-r2": { name: "Discovered check wins the rook II", motif: "discovered check" },
    "t-gen-disco-n": { name: "Discovered check wins the knight", motif: "discovered check" },
    "t-gen-disco-n2": { name: "Discovered check wins the knight II", motif: "discovered check" },
    "t-gen-disco-b": { name: "Discovered check wins the bishop", motif: "discovered check" },
    "t-gen-disco-b2": { name: "Discovered check wins the bishop II", motif: "discovered check" },
  };
})(typeof window !== "undefined" ? window : globalThis);
