/**
 * Puzzles mined from engine self-play — generated by scripts/mine-puzzles.mjs, do not edit.
 *
 * Source: games the vendored Stockfish 18 lite played against itself at low
 * UCI skill levels; each entry is the position after a blunder, with the
 * full-strength refutation as the solution. Every entry is white to move
 * (black-to-move positions were mirrored, see scripts/import-puzzles.mjs)
 * and has passed scripts/lib/puzzle-gate.mjs, the same proof the hand-written
 * set is held to. `rating` is an estimate (see mine-puzzles.mjs); the app's
 * Glicko-2 takes over from the first answer.
 *
 * 17 puzzles from 17 candidate positions; per theme ≤ 150, per 200-point band ≤ 80.
 * @module puzzles-mined
 */
export const MINED_PUZZLES = [
  {id: "mn-99-2-38", cat: "m1", fen: "5k1r/4b1pp/1p2bp2/1Q2P2B/4p3/P4Nn1/2qN1PPP/1RB1K2R w K - 3 21", solution: ["Qe8#"], rating: 1000, src: "mined"},
  {id: "mn-11-2-66", cat: "m2", fen: "1k2b3/1p6/p3rqNp/P1QN1ppP/2P5/3pP1P1/1R6/1KR5 w - - 3 35", solution: ["Qc7+", "Ka7", "Qxb7#"], rating: 1450, src: "mined"},
  {id: "mn-11-0-39", cat: "tac", motif: "pin", fen: "2bq1rk1/4np1p/4p1p1/P2pb3/2pP1P2/n3P1P1/6BP/1RQ1K2R w K - 0 23", solution: ["Qxa3"], gain: 3, rating: 1400, src: "mined"},
  {id: "mn-21-1-36", cat: "tac", fen: "r1b1k2r/1p2b3/3n1Pp1/p1p4p/3PB3/1PP5/P2BNP1P/R3K1R1 w Q - 1 22", solution: ["Bxg6+"], gain: 1, rating: 1400, src: "mined"},
  {id: "mn-21-4-64", cat: "tac", motif: "pin", fen: "2bkn3/3n4/1pQ4r/3P1p1p/2PR2pq/2B2PbP/P3B1P1/7K w - - 2 34", solution: ["Qxh6"], gain: 5, rating: 1400, src: "mined"},
  {id: "mn-21-4-71", cat: "tac", fen: "7k/p3bQp1/5p1p/2pr2P1/3pBPbP/1q6/2KN4/2B1N3 w - - 0 38", solution: ["Nxb3"], gain: 9, rating: 1400, src: "mined"},
  {id: "mn-99-2-34", cat: "tac", motif: "skewer", fen: "4rk1r/2q1b1pp/1pB1bp2/1Q2Pn2/4p3/P4N2/3N1PPP/1RB1K2R w K - 2 19", solution: ["Bxe4"], gain: 1, rating: 1400, src: "mined"},
  {id: "mn-21-5-62", cat: "tac", fen: "7k/1Q4b1/2P4p/3p1b2/3pr3/2P2NPP/RB1N1K2/8 w - - 1 35", solution: ["Ra8+", "Re8", "Rxe8+"], gain: 5, rating: 1500, src: "mined"},
  {id: "mn-11-1-28", cat: "tac", motif: "pin", fen: "3qk2r/3nrp1p/b3pbp1/p1pP4/7P/P1P2Q2/B2P1PP1/R1B1K1NR w KQk - 5 18", solution: ["d6", "O-O", "dxe7"], gain: 4, rating: 1650, src: "mined"},
  {id: "mn-21-1-78", cat: "tac", fen: "2k5/8/8/2p2r1p/p1KP4/2P5/P6P/1R1BR3 w - - 0 43", solution: ["d5", "Rf6", "Kxc5"], gain: 1, rating: 1650, src: "mined"},
  {id: "mn-21-3-38", cat: "tac", fen: "2r1k2r/2n5/1p2pRP1/p1pp4/N1PPb3/P5Q1/1P2N1P1/R3KB2 w Q d6 0 23", solution: ["g7", "Ke7", "gxh8=R"], gain: 4, rating: 1650, src: "mined"},
  {id: "mn-21-4-73", cat: "tac", fen: "7k/p3bQp1/5p1p/2pr2P1/3pBP1P/1K6/3N4/2BbN3 w - - 1 39", solution: ["Ka2", "Bh5", "Qxe7"], gain: 3, rating: 1650, src: "mined"},
  {id: "mn-11-0-80", cat: "win", fen: "3b4/5k2/2q1p1p1/2Pp1p1p/3P1P2/r2BP1PP/R3Q2K/2r1B3 w - - 0 43", solution: ["Rxa3"], gain: 5, rating: 1200, src: "mined"},
  {id: "mn-21-0-7", cat: "win", fen: "rn1qkb1r/1pp2ppp/3p4/p3p3/4n3/2N3PN/PPPP1P1P/R1BQK2R w KQkq - 0 7", solution: ["Nxe4"], gain: 3, rating: 1200, src: "mined"},
  {id: "mn-21-2-25", cat: "win", fen: "r3k2r/1pqbbppp/2p1p2n/p2pP3/nP1P1P2/P1NB2P1/2PBN2P/R1Q1K2R w KQkq - 1 16", solution: ["Nxa4"], gain: 3, rating: 1200, src: "mined"},
  {id: "mn-21-2-41", cat: "win", fen: "2kr2r1/2q1bppp/1pb1p3/1NppPP2/1P1P4/3BB1PP/2P1N3/R1Q1K2R w KQ - 4 24", solution: ["Nxc7"], gain: 6, rating: 1200, src: "mined"},
  {id: "mn-99-2-33", cat: "win", fen: "1rb1k2r/3n1ppp/p4n2/4P3/1q2pN2/1Pb1BP2/2Q1B1PP/R4K1R w k - 1 18", solution: ["exf6"], gain: 2, rating: 1200, src: "mined"},
];
