/**
 * 日本語のパズル文言。
 *
 * lessons-ja.js と同じ分担で、puzzles.js が盤面・解手順・得点を持ち、
 * このファイルは言葉だけを持つ。したがって訳が別のパズルを説明してしまう
 * ことはあり得ず、項目が欠けても中国語名にフォールバックするだけで
 * ラベルが空になることはない。
 *
 * 形: { [puzzleId]: { name, motif? } } —— motif は puzzles.js が持つものだけ。
 * scripts/test-chess.mjs が全 id の網羅と、存在しない id を指す項目がない
 * ことを検査する。
 * @module puzzles-ja
 */
  export const CHESS_PUZZLES_JA = {
    "m1-backrank-r": { name: "バックランク・メイト" },
    "m1-q-knight": { name: "クイーンとナイトのメイト" },
    "m1-smother": { name: "スマザード・メイト" },
    "m1-ladder": { name: "ラダー・メイト" },
    "m1-kq-box": { name: "キングとクイーンのメイト" },
    "m1-epaulette": { name: "エポーレット・メイト" },
    "m1-pawn-q": { name: "ポーンに支えられたクイーンのメイト" },
    "m1-edge-r": { name: "盤端でのルーク・メイト" },
    "m1-br-queen": { name: "バックランク・メイト（クイーン）" },
    "m1-kq-g7": { name: "クイーンの密着メイト" },
    "m1-bishops": { name: "二枚のビショップのメイト" },
    "m1-q-backrank": { name: "ルークを取ってバックランク・メイト" },
    "m1-promo": { name: "プロモーション・メイト" },
    "m1-arabian": { name: "アラビアン・メイト" },
    "m2-corner-h8": { name: "静かな手で角に閉じ込める" },
    "m2-corner-a1": { name: "静かな手で角に閉じ込める III" },
    "m2-corner-rook": { name: "キングとルークで角に詰める" },
    "m2-ladder-rank": { name: "二枚のルークで王を追う" },
    "m2-ladder-file": { name: "二枚のルークで王を追う II" },
    "m2-rr-sac": { name: "重ねたルークでバックランクを制圧" },
    "m2-q-sac": { name: "クイーンを捨ててバックランク・メイト" },
    "m3-ladder-b": { name: "3 手のラダー・メイト" },
    "m3-ladder-m": { name: "3 手のラダー・メイト III" },
    "m3-kq-corner": { name: "クイーンとキングで 3 手で角へ" },
    "m3-kr-corner": { name: "ルークとキングで 3 手で角へ" },
    "m3-promo": { name: "3 手のプロモーション・メイト" },
    "w-hangq": { name: "浮いたクイーンをただで取る" },
    "w-forkdone": { name: "王手フォークでルークを得る" },
    "w-pawntakes": { name: "ポーンがビショップを取る" },
    "w-cornerrook": { name: "角のルークをありがたく頂く" },
    "w-looseknight": { name: "浮いたナイトを取る" },
    "w-smallbest": { name: "小さな得でも損よりまし" },
    "w-loosebishop": { name: "ルークが浮いたビショップをさらう" },
    "w-discovered": { name: "ディスカバード・アタックでクイーンを得る" },
    "w-hangrook": { name: "浮いたルークをただで取る" },
    "w-nfork-rr": { name: "ナイトが角のルークを取る" },
    "w-qxbishop": { name: "クイーンが浮いたビショップを取る" },
    "w-rxrook": { name: "ルークが浮いたルークを取る" },
    "w-bxqueen": { name: "ビショップが浮いたクイーンを取る" },
    "w-nxqueen": { name: "ナイトが浮いたクイーンを取る" },
    "w-pxrook": { name: "ポーンがルークを取る" },
    "w-royalfork": { name: "ナイトがキングとクイーンをフォーク" },
    "w-royalfork2": { name: "ナイトがキングとクイーンをフォーク II" },
    "t-skewer-h": { name: "スキュアーでクイーンを得る（縦線）", motif: "スキュアー" },
    "t-deflect-r": { name: "ルークを筋から引き離す", motif: "デフレクション" },
    "t-remove-n": { name: "ルークを守るナイトを取る", motif: "守り駒の排除" },
    "t-remove-b": { name: "ルークを守るビショップを取る", motif: "守り駒の排除" },
    "t-overload-r": { name: "二役のルークに二択を迫る", motif: "オーバーロード" },
    "t-disco-q": { name: "ディスカバード・チェックでクイーンを捕らえる", motif: "ディスカバード・チェック" },
    "t-disco-r": { name: "ディスカバード・チェックでルークを捕らえる", motif: "ディスカバード・チェック" },
    "t-disco-b": { name: "ディスカバード・チェックでクイーンを捕らえる（ビショップ）", motif: "ディスカバード・チェック" },
    "t-skewer-d": { name: "スキュアーでクイーンを得る（d 線）", motif: "スキュアー" },
    "t-pin-e": { name: "ピンして集中攻撃（e 線）", motif: "ピン" },
    "t-pin-diag": { name: "ピンして集中攻撃（斜線）", motif: "ピン" },
    "t-fork-n": { name: "ナイトがキングとクイーンをフォーク", motif: "フォーク" },
    "t-double-q": { name: "クイーンの二重攻撃", motif: "フォーク" },
    "m1-damiano": { name: "ダミアーノのメイト" },
    "w-gen-bxn": { name: "ビショップが浮いたナイトを取る" },
    "w-gen-bxn2": { name: "ビショップが浮いたナイトを取る II" },
    "w-gen-bxr": { name: "ビショップが浮いたルークを取る" },
    "w-gen-bxr2": { name: "ビショップが浮いたルークを取る II" },
    "w-gen-nxb": { name: "ナイトが浮いたビショップを取る" },
    "w-gen-nxb2": { name: "ナイトが浮いたビショップを取る II" },
    "w-gen-nxr": { name: "ナイトが浮いたルークを取る" },
    "w-gen-nxr2": { name: "ナイトが浮いたルークを取る II" },
    "w-gen-pxn": { name: "ポーンが浮いたナイトを取る" },
    "w-gen-pxn2": { name: "ポーンが浮いたナイトを取る II" },
    "w-gen-qxn": { name: "クイーンが浮いたナイトを取る" },
    "w-gen-qxn2": { name: "クイーンが浮いたナイトを取る II" },
    "w-gen-qxr": { name: "クイーンが浮いたルークを取る" },
    "w-gen-qxr2": { name: "クイーンが浮いたルークを取る II" },
    "w-gen-rxb": { name: "ルークが浮いたビショップを取る" },
    "w-gen-rxb2": { name: "ルークが浮いたビショップを取る II" },
    "w-gen-rxn": { name: "ルークが浮いたナイトを取る" },
    "w-gen-rxn2": { name: "ルークが浮いたナイトを取る II" },
    "w-gen-rxq": { name: "ルークが浮いたクイーンを取る" },
    "w-gen-rxq2": { name: "ルークが浮いたクイーンを取る II" },
    "t-gen-disco-b": { name: "ナイトがどく：ディスカバード・チェックでビショップを得る", motif: "ディスカバード・チェック" },
    "t-gen-disco-b2": { name: "ナイトがどく：ディスカバード・チェックでビショップを得る II", motif: "ディスカバード・チェック" },
    "t-gen-disco-n": { name: "ビショップがどく：ディスカバード・チェックでナイトを得る", motif: "ディスカバード・チェック" },
    "t-gen-disco-n2": { name: "ビショップがどく：ディスカバード・チェックでナイトを得る II", motif: "ディスカバード・チェック" },
    "t-gen-disco-q": { name: "ディスカバード・チェックでクイーンを得る（ナイトがどく）", motif: "ディスカバード・チェック" },
    "t-gen-disco-q2": { name: "ディスカバード・チェックでクイーンを得る（ナイトがどく）II", motif: "ディスカバード・チェック" },
    "t-gen-disco-r": { name: "ディスカバード・チェックでルークを得る（ナイトがどく）", motif: "ディスカバード・チェック" },
    "t-gen-disco-r2": { name: "ディスカバード・チェックでルークを得る（ナイトがどく）II", motif: "ディスカバード・チェック" },
    "m2-net-rr": { name: "ルークが 2 手で網を閉じる" },
    "m2-net-rr2": { name: "ルークが 2 手で網を閉じる II" },
    "m2-net-qn": { name: "ナイトが 2 手で網を閉じる" },
    "m2-net-qn2": { name: "クイーンが 2 手で網を閉じる" },
    "m2-net-rb": { name: "ルークが 2 手で網を閉じる III" },
    "m2-net-rb2": { name: "ルークが 2 手で網を閉じる IV" },
    "m2-net-qb": { name: "クイーンが 2 手で網を閉じる II" },
    "m2-net-qb2": { name: "クイーンが 2 手で網を閉じる III" },
    "m2-net-rn": { name: "ナイトが 2 手で網を閉じる II" },
    "m2-net-rn2": { name: "ナイトが 2 手で網を閉じる III" },
    "m2-net-qr": { name: "ルークが 2 手で網を閉じる V" },
    "m2-net-qr2": { name: "ルークが 2 手で網を閉じる VI" },
    "m3-hunt-rr": { name: "ルークが 3 手で王を追い詰める" },
    "m3-hunt-rr2": { name: "ルークが 3 手で王を追い詰める II" },
    "m3-hunt-qr": { name: "クイーンが 3 手で王を追い詰める" },
    "m3-hunt-qr2": { name: "ルークが 3 手で王を追い詰める III" },
    "m3-hunt-qb": { name: "ビショップが 3 手で王を追い詰める" },
    "m3-hunt-qb2": { name: "クイーンが 3 手で王を追い詰める II" },
    "m3-hunt-qn": { name: "クイーンが 3 手で王を追い詰める III" },
    "m3-hunt-qn2": { name: "クイーンが 3 手で王を追い詰める IV" },
    "r-01": { name: "実戦 01" },
    "r-02": { name: "実戦 02" },
    "r-03": { name: "実戦 03" },
    "r-04": { name: "実戦 04" },
    "r-05": { name: "実戦 05" },
    "r-06": { name: "実戦 06" },
    "r-07": { name: "実戦 07" },
    "r-08": { name: "実戦 08" },
    "r-09": { name: "実戦 09" },
    "r-10": { name: "実戦 10" },
    "r-11": { name: "実戦 11" },
    "r-12": { name: "実戦 12" },
    "r-13": { name: "実戦 13" },
    "r-14": { name: "実戦 14" },
    "r-15": { name: "実戦 15" },
    "r-16": { name: "実戦 16" },
    "r-17": { name: "実戦 17" },
    "r-18": { name: "実戦 18" },
    "r-19": { name: "実戦 19" },
    "r-20": { name: "実戦 20" },
    "r-21": { name: "実戦 21" },
    "r-22": { name: "実戦 22" },
    "r-23": { name: "実戦 23" },
    "d-battery-only": { name: "ビショップとクイーンの砲列：受けは一つだけ" },
    "d-battery-eat": { name: "ビショップとクイーンの砲列：クイーンを取る" },
    "d-battery-two": { name: "ビショップとクイーンの砲列：g2 をふさぐ" },
    "d-back-luft": { name: "バックランク・メイト：王に空気穴を開ける" },
    "d-back-eat": { name: "バックランク・メイト：まず加担している駒を取る" },
    "d-back-step": { name: "バックランク・メイト：王が自分でどく手もある" },
    "d-qe1": { name: "クイーンによる e1 のバックランク・メイト" },
    "d-qd1": { name: "クイーンによる d1 のバックランク・メイト" },
    "d-qe3-eat": { name: "ポーンでクイーンを取る：最も安上がりな受け" },
    "d-qa1": { name: "大斜線上のクイーン" },
    "d-qf1": { name: "角の王はいっそう危ない" },
    "d-qd1-h1": { name: "角の王：取ってしまう" },
    "d-re1": { name: "ルークでもバックランクは詰む" },
    "d-knights": { name: "二枚のナイトが f2 に迫る" },
    "d-knights-eat": { name: "二枚のナイト：近い方を取る" },
    "d-queenside": { name: "クイーンサイド・キャスリング：やはり空気穴が要る" },
    "d-queenside2": { name: "クイーンサイド・キャスリング：大斜線" },
    "d-gpawn-eat": { name: "g ポーンが動いたあと" },
    "d-gpawn-step": { name: "g ポーンが動いたあと II" },
    "d-qg4": { name: "クイーンが横から迫る" },
    "dr-a1-rook": { name: "角のステイルメイト：ルークを捨てる" },
    "dr-a1-bishop": { name: "角のステイルメイト：ビショップを捨てて王手" },
    "dr-a1-knight": { name: "角のステイルメイト：ナイトを捨てる" },
    "dr-a1-rook2": { name: "角のステイルメイト：王が遠くても同じ" },
    "dr-a1-bish2": { name: "角のステイルメイト：ビショップを遠くから捨てる" },
    "dr-a1-knt2": { name: "角のステイルメイト：ナイトをクイーンの口へ跳ね込む" },
    "dr-a1-b3r": { name: "b3 のステイルメイト：ルークを捨てる" },
    "dr-a1-b3b": { name: "b3 のステイルメイト：ビショップを捨てる" },
    "dr-a1-b3n": { name: "b3 のステイルメイト：ナイトを捨てる" },
    "dr-h1-rook": { name: "右の角のステイルメイト：ルークを捨てる" },
    "dr-h1-bishop": { name: "右の角のステイルメイト：ビショップを捨てて王手" },
    "dr-h1-knight": { name: "右の角のステイルメイト：ナイトを捨てる" },
    "dr-h1-rook2": { name: "右の角のステイルメイト：王が遠くにいる場合" },
    "dr-h1-g3r": { name: "g3 のステイルメイト：ルークを捨てる" },
    "dr-h1-g3b": { name: "g3 のステイルメイト：ビショップを捨てる" },
    "dr-h1-g3n": { name: "g3 のステイルメイト：ナイトを捨てる" },
    "dr-a8-rook": { name: "上の角のステイルメイト：ルークを捨てる" },
    "dr-a8-bishop": { name: "上の角のステイルメイト：ビショップを捨てて王手" },
    "dr-a8-knight": { name: "上の角のステイルメイト：ナイトを捨てる" },
    "dr-h8-rook": { name: "右上の角のステイルメイト：ルークを捨てる" },
  };
