/**
 * GENERATED by scripts/build-explorer.mjs — do not edit (v8-0-plan C3 step 2).
 * Source: https://database.lichess.org/standard/lichess_db_standard_rated_2026-08.pgn.zst (Lichess, CC0).
 * Params: --month 2026-08 --min-elo 2200 --speeds Blitz,Rapid,Classical --games 120000 --plies 16 --min-games 2 --bucket-bytes 600000 --seed 1
 * Read 7096686 games, counted 120000; kept 82529 positions, 122279 moves.
 */
export const EXPLORER_MASTERS = {"source":"lichess_db_standard_rated_2026-08","licence":"CC0","minElo":2200,"speeds":["Blitz","Rapid","Classical"],"plies":16,"minGames":2,"games":120000,"read":7096686,"positions":82529,"moves":122279,"buckets":[[0,7],[8,9],[10,11],[12,12],[13,14],[15,15]],"bytes":[547358,494378,588867,304630,575853,255803]};
