/**
 * Generate src/web/js/eco.js — the full ECO table keyed by *position*.
 *
 * The curated book in openings.js matches by SAN prefix, so a transposition
 * (1.e4 e5 2.Bc4 Nc6 3.Nf3 is still the Italian) and a game started from a
 * `[FEN]` are both nameless. The lichess table (~3 800 lines) keyed by the
 * position they end in fixes both; v6-plan Q2.7.
 *
 * Source: https://github.com/lichess-org/chess-openings (CC0-1.0), the five
 * TSVs a.tsv … e.tsv with columns eco / name / pgn. Each pgn is played out with
 * the vendored chess.js and the final position becomes the key — the same key
 * fide.js uses for repetition (no move counters, ep only when a capture is
 * actually legal), so eco-lookup.js can reuse that function.
 *
 * The output is committed, not built: the app has no network and package.sh
 * should not depend on GitHub being up. Re-run this to refresh it.
 *
 *   node scripts/gen-eco.mjs            regenerate from scripts/cache/ (downloads once if empty)
 *   node scripts/gen-eco.mjs --refresh  re-download, then regenerate
 *
 * scripts/cache/ is gitignored; the upstream commit is recorded next to the
 * TSVs so the generated header can name it offline.
 */
import fs from "fs";
import path from "path";
import { spawnSync } from "child_process";
import vm from "vm";
import { fileURLToPath } from "url";
import { compileModuleSync } from "./bundle.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
// the app's own chess.js and fide.js, loaded the way every scripts/test-*.mjs
// loads them, so the key written here is the key the app computes
const ctx = { console };
ctx.globalThis = ctx;
ctx.window = ctx;
vm.createContext(ctx);
for (const m of ["chess.js", "fide.js"]) {
  vm.runInContext(compileModuleSync(path.join(root, "src/web/js", m)), ctx, { filename: m });
}
const { Chess, ChessFide } = ctx;
const CACHE = path.join(root, "scripts/cache");
const OUT = path.join(root, "src/web/js/eco.js");
const REPO = "lichess-org/chess-openings";
const RAW = `https://raw.githubusercontent.com/${REPO}/master/`;
const VOLUMES = ["a", "b", "c", "d", "e"];
const REFRESH = process.argv.includes("--refresh");

async function download() {
  fs.mkdirSync(CACHE, { recursive: true });
  for (const v of VOLUMES) {
    const res = await fetch(RAW + v + ".tsv");
    if (!res.ok) throw new Error(`${v}.tsv: HTTP ${res.status}`);
    fs.writeFileSync(path.join(CACHE, v + ".tsv"), await res.text());
  }
  // the commit the TSVs came from, so the generated header can cite it
  const ls = spawnSync("git", ["ls-remote", `https://github.com/${REPO}.git`, "HEAD"], { encoding: "utf8" });
  const sha = (ls.stdout || "").split(/\s/)[0] || "unknown";
  fs.writeFileSync(path.join(CACHE, "HEAD.txt"), `${sha} ${new Date().toISOString().slice(0, 10)}\n`);
}

const cached = () => VOLUMES.every((v) => fs.existsSync(path.join(CACHE, v + ".tsv")));
if (REFRESH || !cached()) await download();

const [sha, date] = (fs.existsSync(path.join(CACHE, "HEAD.txt"))
  ? fs.readFileSync(path.join(CACHE, "HEAD.txt"), "utf8").trim().split(" ")
  : ["unknown", "unknown"]);

/** "1. e4 e5 2. Nf3" → ["e4", "e5", "Nf3"] */
const sansOf = (pgn) => pgn.split(/\s+/).filter((t) => t && !/^\d+\.+$/.test(t));

const table = new Map();
let rows = 0, dup = 0;
for (const v of VOLUMES) {
  const lines = fs.readFileSync(path.join(CACHE, v + ".tsv"), "utf8").split("\n");
  for (const line of lines.slice(1)) {
    if (!line.trim()) continue;
    const [eco, name, pgn] = line.split("\t");
    rows++;
    const g = new Chess();
    for (const san of sansOf(pgn)) {
      if (!g.move(san)) throw new Error(`${eco} ${name}: illegal "${san}" in "${pgn}"`);
    }
    const key = ChessFide.positionKey(g.fen(), g);
    // upstream lists a few positions twice under different move orders; the
    // first spelling wins and the count is printed so a jump is noticed
    if (table.has(key)) { dup++; continue; }
    table.set(key, [eco, name]);
  }
}

const entries = [...table.entries()].sort((a, b) => (a[1][0] < b[1][0] ? -1 : a[1][0] > b[1][0] ? 1 : a[0] < b[0] ? -1 : 1));
const body = entries.map(([k, [eco, name]]) => `  ${JSON.stringify(k)}: ${JSON.stringify([eco, name])},`).join("\n");
const text = `/**
 * ECO opening table keyed by position — GENERATED by scripts/gen-eco.mjs,
 * and committed so the app builds offline. Do not edit by hand; re-run the
 * generator instead.
 *
 * Upstream: ${REPO}@${sha} (fetched ${date}), licence CC0-1.0
 * (public domain). ${entries.length} positions from ${rows} TSV rows
 * (${dup} duplicate positions dropped).
 *
 * Key = board, side to move, castling, en-passant (ep kept only when a
 * capture is legal) — ChessFide.positionKey(). Value = [eco, English name].
 * Reading it goes through eco-lookup.js.
 * @module eco
 */
  export const ECO_BY_KEY = {
${body}
  };
`;
fs.writeFileSync(OUT, text);
console.log(`eco.js: ${entries.length} positions (${rows} rows, ${dup} duplicates) → ${(text.length / 1024).toFixed(0)} KB`);
